### ISSUE TITLE
Creating Themes from a Pattern-First Mindset

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#1]
Already drafted on the blog
[Public Preview](https://developer.wordpress.org/news/?p=20&preview=1&_ppp=442da77b4a)

**Comment by justintadlock** [comment]
I edited the draft, added a screenshot, and cleaned up some of the broken bits.  It's ready to go, pending any review notes from others.  

New public preview link (last one expired): https://developer.wordpress.org/news/?p=20&preview=1&_ppp=9160cc35fe

**Comment by bph** [comment]
Just updated the preview link: https://developer.wordpress.org/news/?p=20&preview=1&_ppp=0d1d669a0b

**Comment by abhansnuk** [comment]
Hello @justintadlock and @bph I have been through the draft a few times in the last few weeks as we work on the style and guidance for writers. Thank you for putting together this really interesting piece Justin. I have made some edits to bring it into the style of the blog and to help those reading it for whom English is not their primary language or who may be translating the piece for their locale. 

Two things I would ask to collaborate with you on Justin. In the third par, could you please rephrase the second half of this sentence to help more people follow the meaning and for those translating it as they read. "Patterns very much fit into this same mold, but most WordPress block themes have not squeezed everything out of the system that they can."

The style for the blog is to follow core and documentation posts, and avoid references to 'we', 'I' and opinion in general pieces. Could you please look at this section: "When I was first perusing the underlying template code from Twenty Twenty-Two several months ago.. differences." I have removed these references in other parts of the post.

We are also looking at how to use title for code blocks for the blog, so if you have any suggestions on this, they would be very welcome.

Once we have the above areas finalized, I will add the categories etc. Please do feel free to add an excerpt for the piece, and suggestions for keywords. 

Thanks again for this piece and I am looking forward to your future posts for the blog.

**Comment by francescamarano** [comment]
Hey hey hey, can you regenerate the public link? Thanks!

**Comment by bph** [comment]
@francescamarano You should have access to the blog. remove the string `&preview=1&_ppp=0d1d669a0b` from the URL and you should be able to login and look at it.

**Comment by bph** [comment]
New link anyway :-) https://developer.wordpress.org/news/?p=20&preview=1&_ppp=cf3c304d7d

**Comment by justintadlock** [comment]
Hi, @abhansnuk.  Thank you for the feedback.  Great job with editing!  

I have a few thoughts and questions below.  Mostly, I want to make sure I have clarification about what we're doing.  I plan to regularly contribute, and the following is about getting on the same page.

> I have made some edits to bring it into the style of the blog and to help those reading it for whom English is not their primary language or who may be translating the piece for their locale.

I understand, but I'd also like us to avoid this venture becoming a dry blog with language that's too technical.  I'd hate to take the fun out of writing and for readers to miss out on the occasional gem or two.  We have handbooks available for those who are prefer to read things on the lifeless end of the spectrum. 😄

For example, the following paragraph is one of my favorites from the entire piece.  Now it's just kind of boring:

> **Original:**\
> However, it did not go far enough in showing off the potential for patterns. Of course, it was the first official default block theme to launch for WordPress, and we now have that magical ability of hindsight.
>
> **New:**\
> This was the first official block theme to launch for WordPress. More of the potential for patterns is to come.

The new version doesn't even carry the same meaning.  I can give you a dryer version of the original if needed, but it's missing the entire context of being able to look back and view TT2 and theming through a new lens.

> In the third par, could you please rephrase the second half of this sentence to help more people follow the meaning and for those translating it as they read. "Patterns very much fit into this same mold, but most WordPress block themes have not squeezed everything out of the system that they can."

Sure.  Something like this work? "but most WordPress block themes have underutilized patterns."

> The style for the blog is to follow core and documentation posts, and avoid references to 'we', 'I' and opinion in general pieces.

This entire post is an opinion piece.

Are we not publishing opinion pieces at all?  Or, was this post mis-categorized as a general, non-opinion piece?  I'm asking so that there is some clarity going forward.  I don't mind either way, but I can save the opinion pieces for other blogs if needed.

> We are also looking at how to use title for code blocks for the blog, so if you have any suggestions on this, they would be very welcome.

I don't understand what you mean by "how to use title for code blocks."

**Comment by bph** [comment]
Thank you so much for starting the review process @abhansnuk @justintadlock  and keeping the discussion public! We can all learn so much from you too! 

"no opinion piece" isn't really a dogma. Is there really a blog post that is NOT an opinion?  Taking a look at something from a different perspective and see how that changes the approach especially with something like building a theme, and design, is well within the realm of the blog. Not using "i" or "we" doesn't mean, there isn't an opinion expressed or everything needs to be passive mode. 

Before bigger edits, where a whole section is changed like the above example, prior warning should be extended. Another option to change the "we now have that magical ability of hindsight" could be something like  'a year later, one is left with the magical ability of hindsight.'

As for **title for code blocks**, @justintadlock 

The code block as a setting in the sidebar for to add a title, see screenshot. I didn't know until going over Dev Notes that accessibility is increased when code blocks have titles that are read by screen readers. 

![Screen Shot 2022-10-28 at 16 12 36](https://user-images.githubusercontent.com/39980/198725795-8fd906d9-9ff4-431f-8bac-18defb5c1bb8.png)

**Comment by justintadlock** [comment]
> As for title for code blocks, @justintadlock
>
> The code block as a setting in the sidebar for to add a title, see screenshot. I didn't know until going over Dev Notes that accessibility is increased when code blocks have titles that are read by screen readers.

That is interesting.  I'll have to give it some thought.  It feels a bit odd to give a specific written title.  

My really quick gut feeling is that, if it's an a11y issue, the paragraph text before the code block lands needs to better explain what's upcoming.  Adding a title feels like trying to solve the problem of missing context.  Personally, I try to do something like this (though, I don't always remember):

> this XYZ thing that we're doing is shown in the following code snippet:
>
> [code block]

With that said, I'm not an a11y expert, so I will leave that to others.  I'm happy to follow whatever system is best for our readers.

**Comment by bph** [comment]
@justintadlock I try to connect with the a11y team to get clarification on this part, hopefully before the meeting.

**Comment by abhansnuk** [comment]
Hello @justintadlock thanks for helping in the discussion on style for the dev blog. We had to use the initial three posts already in the CMS as pilots for the review process and the guidelines being produced for writers, so really appreciate your participation in evolving this together. I had not seen your comments above until today, so apologies for a delay in replying. This GitHub is not sending me notifications for comments, and I only discovered it during the dev blog meeting today. Apologies in advance for a longer answer to your questions, but I value your input as we finalize the tips for writers and reviewers, and I thought you might like to see the discussions around developing a style and information for writers and reviewers. The approach differs so much across the project, which is probably not surprising for an open source, evolving project. Trying to get clarity for writers and reviewers of the dev blog is our aim and thank you for your help with this.

I completely agree with you that the dev blog needs to avoid becoming dry. I enjoyed your article. As a side note to our docs colleagues, documentation for WordPress does not have to be 'lifeless' and there have been some good and interestingly presented content that is coming through in docs and training to keep the reader's interest. I think you will find there is positive change happening in these areas, and the dev blog will considerably help with this.

Back to the dev blog, by making sure we are avoiding terms or expressions that non-English speakers may find difficult if they are translating in their minds as they read or if they are translating a piece to use in their locale does not have to mean the content has to become dry. Hopefully by being creative and be conscious of this need, we can really engage even more readers globally.

**In terms of the example you reference above. "However, it did not go far enough in showing off the potential for patterns..."**
I had checked that this piece was a general piece and not an opinion piece before I started editing it, as I was unsure from first reading it. My edits were therefore based on this. We will have a label in future to mark pieces on GitHub as 'case study'. Whether this label will be enough to cover posts like yours, which is now set as an opinion piece, I am unsure. At the start, getting clarity will be important both for the writer and editor, and be a time saver too.

In terms of your specific example, I think a slight tweak of your phrase could be made to bring out that reflective view and looking at a new lens without it becoming dry. Perhaps a tweak of the first half and incorporating Birgit's version of like 'a year later, one is left with the magical ability of hindsight.'

I have covered in more depth the pilot process, the changes we are making as we have content to test the edit and review process, and my reasoning (bear in mind I also understood this was a general piece and not an opinion piece when editing).

------------
This edit was also based on the information provided in the previous discussions on opinion and style focused on testing the draft editorial process. Your queries were helpful with further discussions and my own queries from editing yours as a test piece which I felt needed further discussion in the October editorial meeting. The final agreed approach will go in the tips for writers and help information/ checklist for reviewers. This will also evolve with time as we get more content and new situations which generate queries for writing/ editing. Your input into this will be very welcome too as you come across examples on style to use.

'Opinion' covers a very broad area in my editing experience and from working in different environments, including within the WordPress project, What we need to be clear on for the dev blog is **what will be opinion or personal comment**, and also about how a comment is worded to avoid misinterpretation/ misunderstanding of context particularly as there is a global audience where English may not be the first language. I based my rephrasing on what I have seen and been told when editing in the past in different parts of the project, plus the discussion in the first editorial meeting. This particular phrase fell under the examples I have seen edited of opinion / comment that could be potentially misinterpreted. I appreciate your sentence was not a criticism of what had been done. It was a reflection. It was also one of the examples I had identified for further discussion at the editorial meeting on how we write/ edit reflective points about the project to bring out more of the reflective aspects.

**How we continue to develop the draft process for editing** 
On a related note, in our meeting today we also further discussed how we were going to highlight significant edits when items are already in the CMS, a topic I raised at the previous editorial meeting, Writers can view the previous and edit version side by side in history, with changes marked up. This is what I had followed in the pilot edit of your post, and from my notes, I had added a query to highlight that paragraph in the revision note field in the CMS. Apologies if did not fill that field in correctly on your post and you could not see this. I will look into this. 

Unfortunately, the revision plugin which allows for comments to be visible in addition to an edit does not work for new posts. 

**Future:** There are issues with easily marking up, editing and comparing originals and edits in the CMS. 
For the dev blog, we will in future use the GitHub card to highlight significant suggestions in a similar way to a google doc. 

I know this is not ideal as it can be difficult to find the particular paragraph or phrase in a long post. It also does not allow for highlighting a particular phrase as we can in a google doc. 

But it does mean as a plus that we can have an area we can actually have a discussion/ collaborate or find alternative phrasing together and avoids having to add an additional google doc phase, and its associated changes in formatting.

**Comment by abhansnuk** [comment]
@justintadlock thanks for the rephrase suggestions. On the third par phrase:
- your reword is ideal. Yes please if you can change it to this.
"but most WordPress block themes have underutilized patterns."

On **code block**, this is also a question that came up with dev notes in 6.1. @bph has asked in Accessibility team.

For all posts, we have agreed today, how to add **categories, excerpts, references, and credits stylistically**.
If you would like to add an excerpt to your post, once you are finished editing, I can add the final categories etc prior to publication. 
If you have any suggestion for categories, below are ones we have identified so far:
- CSS
- PHP
- JavaScript
- (user level)  beginners, intermediate, advanced 
- a category yet to be named: represent presentation as opposed to business logic: tutorial,. 
- Design
- Themes
- Plugin
- Media and Assets
- Block Editor (not Gutenberg)
- Templates
- Patterns 

Thanks so much and really looking forward to reading your next article.

**Comment by bph** [comment]
Just published the post. I used the "Themes" category for it, and added the tags "patterns" and "block themes"
