### ISSUE TITLE
Create an About Page 

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#10]
Write summary about the purpose from the proposal of the blog and link to additional pages. 
The proposal to [create a Developer Blog](https://make.wordpress.org/core/2022/02/25/proposal-to-start-a-news-blog-on-developer-wordpress-org/) was published in February 2022

In July 2022, the [proposal for the editorial processes](https://make.wordpress.org/core/2022/07/06/proposed-editorial-process-for-the-new-developer-blog/) was published.

And link to 
How to contribute
Tips and Guidelines for Writers.

**Comment by abhansnuk** [comment]
@bph do you want a hand with this page content?

**Comment by bph** [comment]
That would be great, @abhansnuk 🤗

**Comment by bph** [comment]
@abhansnuk I created [a draft to the blog](https://developer.wordpress.org/news/?page_id=166&preview=1&_ppp=b0b9aefe14)

**Comment by abhansnuk** [comment]
Updated [link](https://developer.wordpress.org/news/?page_id=166&preview=1&_ppp=6cd47e5246). I have been through it and reviewed for typos, spelling, grammar.

**Comment by bph** [comment]
Thank you :-)

**Comment by bph** [comment]
Published https://developer.wordpress.org/news/about/
