### ISSUE TITLE
What's new for developers? (May 2023)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#101]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Google Doc: https://docs.google.com/document/d/14Kz5W5j2I53bAqe7DzUurTKD1Ey7Oc6nAnggWrAXQNw/edit?usp=sharing

Resources to track:

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by justintadlock** [comment]
The first draft is now ready for review: https://docs.google.com/document/d/14Kz5W5j2I53bAqe7DzUurTKD1Ey7Oc6nAnggWrAXQNw/edit#

**Comment by justintadlock** [comment]
The post is scheduled to go live at 9am UTC+0.

**Comment by bph** [comment]
Published: [What’s new for developers? (May 2023)](https://developer.wordpress.org/news/2023/05/whats-new-for-developers-may-2023/)
