### ISSUE TITLE
Navigating the Block Editor Handbook

### ISSUE THREAD

**Issue by mburridge** [WordPress/developer-blog-content#110]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** April  6, 2023</sup>
The [Block Editor Handbook](https://developer.wordpress.org/block-editor/) can be intimidating even for an experienced developer, and is especially so for those new to block development.

There's a wealth of information in the handbook, but key knowledge is distributed across several different sections and can be difficult to find.

Furthermore, there is no clear guide to where stuff is or how to find your way through the handbook to build up your knowledge whilst ensuring that you don't miss anything crucial.

I propose an article that provides a roadmap or path through the handbook that ensures that new users don't miss anything crucial  and that helps them to become familiar with the structure of the handbook so that they will find it easier to use and are able to find the information they need when they need it as they go on to work on real-world projects.

---

_**Note:** this article is already largely written. It was written for another purpose, but is now not going to be used so it can be re-purposed as a post. So turnaround for this is likely to be very quick._</div>

**Comment by mburridge** [comment]
An [initial draft](https://docs.google.com/document/d/19sV6GnaXUf_z2rATdRvRwSwPpBuQPAi7CL_nIDypXlc/edit#) is ready for review. Your feedback and comments are very welcome.

Is there something important that I might have missed and that you think should be mentioned?

**Comment by marybaum** [comment]
I’m off the court! Home in 20 minutes.... from my phoneOn Jun 5, 2023, at 10:30 AM, Michael Burridge ***@***.***> wrote:﻿
An initial draft is ready for review. Your feedback and comments are very welcome.
Is there something important that I might have missed and that you think should be mentioned?

**Comment by marybaum** [comment]
Done and out of the Gdocs tab!

**Comment by mburridge** [comment]
- [x] Post Title in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identified?
- [x]  Is there an explicit Excerpt?
- [x]  Props added?
- [x] 🙌 Publish! 📗
- [x]  add Props for reviews to #props channel in WP Slack
- [x]  close the issue with a comment to link to the published post
- [x]  close the accompanying discussion with w link to the published post.

**Comment by mburridge** [comment]
The [public preview](https://developer.wordpress.org/news/?p=1509&preview=1&_ppp=5f95c3b27b) is now available for second review

**Comment by justintadlock** [comment]
Everything looks good to me, @mburridge. Publish whenever you're ready.

**Comment by mburridge** [comment]
Thanks @justintadlock. The post is now [published](https://developer.wordpress.org/news/2023/06/navigating-the-block-editor-handbook/).
