### ISSUE TITLE
How to add starter content to WordPress themes

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#114]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/102

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** April 18, 2023</sup>
This would be a tutorial on using the Starter Content feature for themes. Despite having been around [since WordPress 4.7](https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/), it's still a relatively unused feature. For classic themes, there is direct integration with the customizer. For themes shared in the theme repository, the starter content is integrated into the theme preview system. The [WordPress Playground](https://developer.wordpress.org/playground/) will also likely be used to launch full previews in the near-_ish_ future. Now is a good time to explore what's possible with this feature.

I haven't fully researched what this looks like with block themes yet.</div>

**Comment by justintadlock** [comment]
After discussing this with @bph last week, we decided that the feature wasn't really in a state to write a tutorial on. When I first proposed this, there was some chatter about changes to the upcoming theme preview system (via the WP Playground project) making more use starter content. However, we could be a ways out from this happening.

Outside of that, not much has happened with starter content in a long while to warrant a current article. If we want to revisit this, we can open a new topic idea discussion.
