### ISSUE TITLE
Tutorial on building block-based templates in classic themes

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#116]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** May  4, 2023</sup>
I've written an [existing post](https://gutenbergtimes.com/building-a-block-based-header-template-in-a-classic-theme/) on building a block-based header template in a classic theme for Gutenberg Times. We could look into tweaking/updating that post and porting it over.

Alternatively, we could explore some other examples. One that was passed along to me was the need to add a customizable block (cookie banner block in this instance) to a classic theme.

Regardless of the content, it'd be good to have a walk-through of using more blocks within classic themes on the Dev Blog.</div>

**Comment by bph** [comment]
Looking at the [Roadmap for 6.5](https://make.wordpress.org/core/2023/12/07/roadmap-to-6-5/) it seems to be a focus on development, too. 

- Support for Appearance Tools in Classic Themes
- Improved Pattern management with Classic Themes

**Comment by justintadlock** [comment]
Closing this one as stale. We can reopen if anyone wants to pick it up again.
