### ISSUE TITLE
What's new for developers (June 2023)

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#117]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Google Doc: https://docs.google.com/document/d/13xF6AZQxdgV_MHWeSzVTSuttA788ExJvLKJkwEbiEDo/edit#

Resources to track:

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by bph** [comment]
Resource to check: [Changelog for WP minor release: 6.2.1 ](https://make.wordpress.org/core/2023/05/09/wordpress-6-2-1-rc1-is-now-available/)

**Comment by justintadlock** [comment]
Finally finished the first draft! https://docs.google.com/document/d/13xF6AZQxdgV_MHWeSzVTSuttA788ExJvLKJkwEbiEDo/edit?usp=sharing

It's a little later than I'd planned, but we're still shooting for a June 10th publication date if we can get this cleaned up in time.

**Comment by justintadlock** [comment]
@bph, @ndiego, and @thatdevgirl have provided feedback, but we could still use a solid copyediting round.

**Comment by marybaum** [comment]
I’m on it. Gimme a few minutes to get home and eat something.(On today’s That’s Incredible: I held serve. Twice.😜🎾)... from my phoneOn Jun 8, 2023, at 5:54 PM, Justin Tadlock ***@***.***> wrote:﻿
Finally finished the first draft! https://docs.google.com/document/d/13xF6AZQxdgV_MHWeSzVTSuttA788ExJvLKJkwEbiEDo/edit?usp=sharing
It's a little later than I'd planned, but we're still shooting for a June 10th publication date if we can get this cleaned up in time.

**Comment by marybaum** [comment]
Done and out! Edits suggested, as always; as The Band sang, take what you need and leave the rest. In this case, though, you ARE welcome to the best!

https://youtu.be/jREUrbGGrgM

**Comment by justintadlock** [comment]
Thanks, @marybaum. Great job, as always! 

Also, I haven't heard that song in a long while. :)

**Comment by marybaum** [comment]
Thank you kindly! 

There is generally a rock 'n roll song in my head. Most get new lyrics that are NOTHING LIKE the originals

**Comment by justintadlock** [comment]
Thanks, everyone, for making this happen. Post will go live on the 10th: https://developer.wordpress.org/news/?p=1496&preview=1&_ppp=1d892d9b01

**Comment by justintadlock** [comment]
Post is now live! https://developer.wordpress.org/news/2023/06/whats-new-for-developers-june-2023/
