### ISSUE TITLE
Using CSS custom properties in a block.

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#124]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/123

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** May 31, 2023</sup>
The `Block Supports` API allows you add colour and spacing settings to your block with a simple definition in `block.json`. However, this only allows "block level" styling, and is fine for simple blocks. If your block is more complex and consists of a hierarchy of HTML elements which need to be styled using the CSS cascade, and you want to allow users to have control over that styling, then another solution needs to be sought.

This solution is not immediately obvious and involves using CSS custom properties (also called CSS variables) which get their values from the block attributes and passes them to the block's wrapping element's `useBlockProps` hook. A similar task can be done with `render.php` in a dynamic block, where the CSS custom properties are instead passed to the `get_block_wrapper_attributes` function.

The proposed post is a tutorial that illustrates using CSS custom properties in a block project.</div>

**Comment by justintadlock** [comment]
This is a great topic! Here's a sample of using custom properties while allowing themes to add support (from one of my plugins): https://github.com/x3p0-dev/x3p0-progress/blob/1.0.0/resources/css/style.scss#L15-L31

**Comment by mburridge** [comment]
A [draft of this post](https://docs.google.com/document/d/14YIZnXxbhKPbb8NFBqypNLkJb88-kNA0tH-qDEnZJAU/edit) is now ready for review.

**Comment by bph** [comment]
Good morning. To help others to review, please open up the Google doc to comment for those with a link.

**Comment by mburridge** [comment]
> To help others to review, please open up the Google doc to comment for those with a lin

Good call. I keep forgetting to do that. 🤦‍♂️

**Comment by abhansnuk** [comment]
Started review and will finish after the editorial meeting today. Thanks Michael

**Comment by bph** [comment]
I left some comments on the docs, see if they work for you. 
I like the flow of the article: Great job.  It could use some more tightening though: 

You might want to consider shortening the example code to just one answer displayed. As you mentioned, the content would come from the CPT and you wouldn't have the user style more than one block at a time. 

To liven up the text heavy tutorial add screenshots of the Editor view of your example with the controls.

**Comment by mburridge** [comment]
The [public preview](https://developer.wordpress.org/news/?p=1794&preview=true) of this post is now available for review.

**Comment by justintadlock** [comment]
@mburridge - This looks like it's about ready to publish. The images need alt text, and the post needs a custom excerpt. Other than that, it's good to go.

**Comment by mburridge** [comment]
> You might want to consider shortening the example code to just one answer displayed. As you mentioned, the content would come from the CPT and you wouldn't have the user style more than one block at a time.

@bph I appreciate the thought but I think I'd like to show several FAQs so it's obvious that if the user is able to style say `details .answer` then a single styling option will apply to all the elements that match.

> To liven up the text heavy tutorial add screenshots of the Editor view of your example with the controls.

Added

**Comment by mburridge** [comment]
Pre and post publishing checklist: 

- [x] Post Title in Sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Props added? 
🙌 Publish! 📗
- [x] add Props for reviews to #props channel in WP Slack 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with w link to the publish post.

**Comment by mburridge** [comment]
Now published: [Styling blocks: empowering users with CSS custom properties](https://developer.wordpress.org/news/2023/08/styling-blocks-empowering-users-with-css-custom-properties/)
