### ISSUE TITLE
How to manage block governance

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#126]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **annezazu** May  4, 2023</sup>
Pulling out of this issue: https://github.com/WordPress/gutenberg/issues/49592#top I think the topic of governance cuts across many audiences from higher ed to enterprise to agencies. Knowing what methods are reliable and how granular you can get is incredibly important. I think having a post outlining tried and true methods, along with perhaps a call for feedback, would help more folks save time in approaching adopting blocks in a way that works for them/their use case. This might also help us cycle feedback into the project so we can continue to improve the developer experience of managing these various pieces. </div>

**Comment by ndiego** [comment]
I think we can close out this topic, since it will be partially covered in #148 and the proposed [Block Library](https://make.wordpress.org/core/2023/07/10/block-library/) will address this as well.
