### ISSUE TITLE
Adding custom color options for blocks

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#129]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** May  2, 2023</sup>
Sometimes, block developers need to add custom color options that are not available as the default Text, Background, and Link color supports, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/1816309/235693287-f7313578-9d35-44ac-99d3-ebb5a39959f0.png)

This question pops up from time to time, and it'd be good to have a solid resource on how to accomplish it. I've already written code for this in a plugin of my own: https://github.com/x3p0-dev/x3p0-progress/blob/1.0/resources/js/color/panel-color.js

Some things to note:

- You cannot add colors to the default "Color" panel. You must build a custom panel.
- You can add individual colors to other custom panels.</div>

**Comment by justintadlock** [comment]
I'll be working on this tutorial from this Google Doc: https://docs.google.com/document/d/1Gh1YnnUWm6Q_WCSglglsmlbTMml23d3-D-pH0VF6bn0/edit?usp=sharing

**Comment by justintadlock** [comment]
Here's the repo that I'll be building the code examples in: https://github.com/justintadlock/custom-block-color-settings

I'll transfer it to the Learn organization once it's finalized.

**Comment by justintadlock** [comment]
The draft for this post is now finished and ready for review: https://docs.google.com/document/d/1Gh1YnnUWm6Q_WCSglglsmlbTMml23d3-D-pH0VF6bn0/edit?usp=sharing

**Comment by marybaum** [comment]
Got it!

**Comment by abhansnuk** [comment]
Hi @justintadlock a great tutorial. I have done a review and added some comments to the doc. Look forward to building following your steps.

**Comment by justintadlock** [comment]
Props to @juanmaguitar for second review. We're ready to publish now.

**Comment by justintadlock** [comment]
And we're live! https://developer.wordpress.org/news/2023/11/how-to-add-custom-color-options-to-blocks/

**Social copy:**

> Have you ever needed to add extra color options to your custom blocks? If so, check out this tutorial on the WordPress Developer Blog to find out how: 
>
> https://developer.wordpress.org/news/2023/11/how-to-add-custom-color-options-to-blocks/

**Comment by ndiego** [comment]
Social post scheduled.
