### ISSUE TITLE
How to build performant block themes

### ISSUE THREAD

**Issue by annezazu** [WordPress/developer-blog-content#14]
Performance is a key topic to continually address and having content that particularly addresses this for block themes seems advantageous along with particularly relevant to a developer audience.

**Comment by bph** [comment]
Thank @annezazu for the suggestion. Performance is people's thoughts. It is also quite a broad concept. 

I can see the following approaches, I am not done thinking, though.. 

1. Performance of the final product (= theme) and what mistakes result in decreased performance? 
2. Performance in contrast to classic themes? as a comparison or load times? Web vitals on server everything else being equal? 
3. Performance in terms of time spent designing and developing a theme? More a workflow and process case study, that describes the Design in Site editor and export and let the developer do the rest of it. 

Does one meet more your idea than the other?

**Comment by annezazu** [comment]
Ohhh I could see all of these being useful! In particular, I was thinking about the former two items and what we can compare there. Otherwise, I also like the idea of making things more performant when it comes to process/workflow too.

**Comment by justintadlock** [comment]
Google Docs link for a post that covers theme.json and per-block stylesheets: https://docs.google.com/document/d/1R38OrhuBEWxdfCVz7j7OOGsjJ6VsZ2hngCsmSZrWdmM/edit?usp=sharing

I can move this over to a draft on the Dev Blog before copyediting, but I'll await any feedback on the overall content of the post first.

**Comment by juanmaguitar** [comment]
Great article @justintadlock.
I've left a few comments and suggestions.
@mtias @annezazu We'd love to get your feedback on this version of the post as it reflects the final perspective to talk about performance in block themes.

**Comment by justintadlock** [comment]
> ...as it reflects the final perspective to talk about performance in block themes.

Just noting that this doesn't necessarily need to be the _final_ perspective.  @bph had some other [great suggestions above](https://github.com/WordPress/developer-blog-content/issues/14#issuecomment-1272624911) that are likely worthy of their own posts.

**Comment by annezazu** [comment]
I'll review it this week!

**Comment by annezazu** [comment]
Reviewed! It reads so well and very easy to understand. Left some comments throughout. I'd dig seeing this out there sooner rather than later so we can keep building on this big topic.

**Comment by justintadlock** [comment]
Updated [the document today](https://docs.google.com/document/d/1R38OrhuBEWxdfCVz7j7OOGsjJ6VsZ2hngCsmSZrWdmM/edit#) based on current feedback.  My next step is to put the draft on the Dev Blog for further review and to get it ready for publishing.

**Comment by justintadlock** [comment]
I've put the post on the Dev Blog as a draft, and it is ready to go, pending any feedback.  Public preview URL: https://developer.wordpress.org/news/?p=194&preview=1&_ppp=296ac91c2d

We're still requesting feedback on the post title.  Current notes on that are in the Google Doc: https://docs.google.com/document/d/1R38OrhuBEWxdfCVz7j7OOGsjJ6VsZ2hngCsmSZrWdmM/edit#

**Comment by bph** [comment]
Updated the public preview link: [Leveraging theme.json and Per-Block Styles for More Performant Themes](https://developer.wordpress.org/news/?p=194&preview=1&_ppp=3985755682)

**Comment by abhansnuk** [comment]
Second review completed as requested at today's meeting @bph.

This will be a really helpful article @justintadlock and very easy to follow for a wide audience. Thanks so much for doing this. It will be really appreciated I am sure.

Would it be possible to add another sub head in the final long section?

I think the new title is much clearer than the original in GitHub. 

@bph just tags and excerpt to add. 
Once we know about the code block field from accessibility, we can go back and add anything we need to the articles which are published.

**Comment by justintadlock** [comment]
> Would it be possible to add another sub head in the final long section?

I don't see many places for a sub-heading there since it's one continuous section.  But, if I had to add one, it'd probably be just before the `wp_enqueue_block_style()` introduction:

> That is where `wp_enqueue_block_style()` comes in...

I wouldn't be against adding something there entirely, but it could break of the flow from the previous paragraph to the next.

We could also add an `<h2>` heading before the concluding paragraph instead of an `<hr>`, but I don't think a heading is necessary there (though, I'd like to see a prettier `<hr>` design, TBH).

**Comment by bph** [comment]
I converted all heading to sentence case rather than title case… as per [our guidelines on the dev blog](https://developer.wordpress.org/news/tips-and-guidelines-for-writers/). 


I feel this post is ready for publishing @justintadlock once props are added :-)

**Comment by bph** [comment]
🎉 Published: [Leveraging theme.json and per-block styles for more performant themes](https://developer.wordpress.org/news/2022/12/07/leveraging-theme-json-and-per-block-styles-for-more-performant-themes/)
