### ISSUE TITLE
Exploring the future of web development with WebAssembly and PHP

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#143]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **adamziel** June 21, 2023</sup>
Since Playground and WebAssembly are only going to more important, the https://developer.wordpress.org/news/ audience could be interested in an article exploring the current state and future implications of this technology.

I co-authored the following article with Angel De Miguel and Rafael Fernández López from wasmlabs.dev. It is not published yet and we'd be happy to contribute it to developer.wordpress.org/news/ – what do you think?

[Exploring the future of web development with WebAssembly and PHP](https://docs.google.com/document/d/1NlPLW1V6GzgHz3tWV0MWTL1_7w_Qy3pgNaJw_XEQtdg/edit#heading=h.q2wjhw6qz0fm)</div>

**Comment by Angelmmiguel** [comment]
Hello @bph,

Thank you for creating the issue! I'm happy the article is moving forward. I know Adam is now on holidays, so if you can assign the issue to me, I will work on any required change on the article 😄.

**Comment by bph** [comment]
Thank you @Angelmmiguel for taking this on. 

Here are a few [tips and.guidlines for writers](https://developer.wordpress.org/news/tips-and-guidelines-for-writers/) on the Developer Blog. 


On the page, [How to contribute](https://developer.wordpress.org/news/how-to-contribute/) you'll find an outline of our processes. 

Feel free to connect any time with questions, moving forward with the article. 

Thank you for being prepared to contribute! 🥰

**Comment by Angelmmiguel** [comment]
Hello @bph,

Thank you for the guidance! I took a look at the links you shared to understand better the process and writing guidelines. Adam, @ereslibre and myself already wrote a first draft for the article. Today, I took a second review based on the guidelines you shared.

**I believe the article is ready for a first review 🎉**. You can find the proposal in this Google Docs link: https://docs.google.com/document/d/1w2hwx5TybnyaM205rbAVyoSNehtYG4ZJ3Y-xWzirLv0/edit?usp=sharing.

Also, feel free to ask me for any required step I may missed in the process.

Thank you!

**Comment by bph** [comment]
@Angelmmiguel 
What's your WordPress.org user name? We would need it to invite you to the blog as author, so you can post the article after the 1st review... if you don't have an account yet, [you can create one here, I believe](https://login.wordpress.org/register)

And [here are instructions to connect](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/) your GitHub account to your WordPress.org account.

**Comment by Angelmmiguel** [comment]
Thank you for the reference @bph. I just created my account ([angelmmiguel](https://profiles.wordpress.org/angelmmiguel/)) and linked it to my GitHub account.

**Comment by Angelmmiguel** [comment]
Hello @bph,

Since I'll be on PTO, @ereslibre will take over this issue to apply any feedback on the article. He's an author of this article too, so he's aware of all the content 😄.

He already created a WordPress.org account and linked it to GitHub. His user is `ereslibre`.

Thank you!

**Comment by bph** [comment]
Thank you @Angelmmiguel so much for keeping an eye on this issue and initiating  a  handover. 

Welcome @ereslibre - we will get some more eyes on this post next week after the WordPress 6.3 RC is out.

**Comment by ereslibre** [comment]
Hello @bph,

It's fantastic to be here, thank you! I'm super excited about this blog post.

Thank you

**Comment by bph** [comment]
@ereslibre Rafael, I just added you as author to the Dev Blog: "Invitation email sent to user. A confirmation link must be clicked for them to be added to your site." 

And I did a first review of the post mainly changing formatting 
- Subheaders becoming H2 (makes it easier with the copy/paste into WordPress 
- removed the bolding. 

Also, marked a couple of places we need to revisit regarding our external link policy. (YouTube, personal blogs, 3rd party products) 

@marybaum when you get time would you please review the post, too?

**Comment by ereslibre** [comment]
Thank you @bph. I have accepted the invitation. Thanks for the formatting changes upon the first review.

I am happy to take action on whatever is needed. 👏

**Comment by ereslibre** [comment]
Hello @bph, just double checking. I accepted the invitation, but when logging in I am not able to see the blog post among the others. Am I supposed to be able to see it already? Thank you.

**Comment by bph** [comment]
Ah, I should have checked. Are you familiar with WordPress as content creation tool? We invite our writers to post their article themselves, make sure the post looks good before publishing add alt text to images, an excerpt. Etc and have a 2nd review on site before publishing. 

The task getting the article published was passed on from a WordPress contributor to outside contributors made for some leaky communication. Sorry about that. 

Let's wait for the next step (= posting it to the site) until @marybaum has time to do a copy review via Google docs. 

Afterwards I'd be happy to post the article for you.

**Comment by ereslibre** [comment]
My apologies, didn't see your comments and suggestions on the Google doc. I have addressed all of them I believe. Thanks :)

> Are you familiar with WordPress as content creation tool?

Yes, I have used it in the past.

Thanks for the context and information. If I got it right, we wait until Mary has done a copy review via Google docs, I address all the issues over there, and then start a draft on the Wordpress platform. Then, when it is good to go, you will perform the final publishing to the world. Is this accurate?

Thanks again.

**Comment by justintadlock** [comment]
Can someone open up the Google Doc for comments? This will let us review it. Thanks!

**Comment by ereslibre** [comment]
> Can someone open up the Google Doc for comments? This will let us review it

The [linked document](https://docs.google.com/document/d/1w2hwx5TybnyaM205rbAVyoSNehtYG4ZJ3Y-xWzirLv0/edit?usp=sharing) [here](https://github.com/WordPress/developer-blog-content/issues/143#issuecomment-1625229072) should be open for comments from anyone. Please, let me know if that's not the case. I tried with an incognito session and it worked as expected.

Edit: Note, I just realized that the link on the top-most comment is a different one.

**Comment by justintadlock** [comment]
Ah, got it. Yes, I was trying to open the one in the first post. The second link is open for comments. Thanks, @ereslibre.

**Comment by justintadlock** [comment]
I gave this a quick round of copyediting and left a few suggestions/comments.

Because this post is quite text-heavy, I'd look at ways of incorporating some images into it just to help break things up and capture the reader's imagination a bit more. For example, one image that you could definitely add is of WP Playground in action.

**Comment by ereslibre** [comment]
Thank you for your review @justintadlock! I addressed all your feedback.

> Because this post is quite text-heavy, I'd look at ways of incorporating some images into it just to help break things up and capture the reader's imagination a bit more. For example, one image that you could definitely add is of WP Playground in action.

This is a great idea. Do you prefer to handle this while we move the content to WordPress and layout there, or do you prefer to layout and add this extra content on the collaborative document itself?

**Comment by justintadlock** [comment]
> This is a great idea. Do you prefer to handle this while we move the content to WordPress and layout there, or do you prefer to layout and add this extra content on the collaborative document itself?

It'd be fine to add them in the post editor at this point. But in general, it's best to add them into Google Docs as part of the initial review process.

**Comment by Angelmmiguel** [comment]
> > This is a great idea. Do you prefer to handle this while we move the content to WordPress and layout there, or do you prefer to layout and add this extra content on the collaborative document itself?
> 
> It'd be fine to add them in the post editor at this point. But in general, it's best to add them into Google Docs as part of the initial review process.

Thanks for the suggestion @justintadlock. I will add the new images to the post. I agree the article is text-heavy, so I'll try to find more opportunities to add visual resources 😄

**Comment by Angelmmiguel** [comment]
Hello @bph @justintadlock,

I was about to start moving the content to the WordPress blog for a final review and publishing. I believe I don't have the "author" role in WordPress.org as I couldn't create a new draft. My username is `angelmmiguel`. 

Thank you!

**Comment by marybaum** [comment]
Let me see if I can get that handled for you.

**Comment by justintadlock** [comment]
I sent over an invite. You should see it for the email address you use for WordPress.org.

**Comment by Angelmmiguel** [comment]
I got it! Thank you very much 😄

**Comment by Angelmmiguel** [comment]
Hello 👋 ,

We finally introduced some images and updated some styles in the article. I saved it as a draft, so [you can check it on the WordPress Developer blog](https://developer.wordpress.org/news/?p=1837&preview=true). I believe we're ready for the final review @bph @justintadlock 😄.

I have a question regarding the authors. I created the article, but Adam and Rafael are co-authors. How can I add them to the article?

Thank you very much for all your help and guidance here!

**Comment by bph** [comment]
Thank you @Angelmmiguel for posting a draft. 
I enabled ['public post preview'](https://developer.wordpress.org/news/?p=1837&preview=1&_ppp=24ef60ac02) link 
You can give props to the co-authors and reviewers in a props section on the bottom of the article. 

I will be able to review it further next week.

**Comment by bph** [comment]
For reviewers and writers alike: 

### Pre-publishing checklist: 

- [ ] Post Title in Sentence case
- [ ] Use "Center Column" template
- [ ] Are Category or Categories selected?
- [ ] Are Tags identifies?
- [ ] Is there an explicit Excerpt?
- [ ] Do all images have an alt-text?
- [ ] Props added? 
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
- [x] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post.

**Comment by marybaum** [comment]
On it! Doing my editing at Contributor Day. #WCUS

**Comment by Angelmmiguel** [comment]
Thank you all! From my side:

 - [x] Post Title in Sentence case
 - [x] Use "Center Column" template
 - [x] Are Category or Categories selected?
 - [x] Are Tags identifies?
 - [x] Is there an explicit Excerpt?
 - [x] Do all images have an alt-text?
 - [x] Props added?

**Comment by justintadlock** [comment]
I seemed to have missed this before, but there's a blockquote just before the "Conclusions" section:

> WebAssembly provides a few well-defined features to support maximum flexibility and an incredibly large number of environments.

Who is this quote from?

If this is not a quote and meant to be a note/highlight/tip/etc., this should use the Notice block instead.

**Comment by Angelmmiguel** [comment]
> I seemed to have missed this before, but there's a blockquote just before the "Conclusions" section:
> 
> > WebAssembly provides a few well-defined features to support maximum flexibility and an incredibly large number of environments.
> 
> Who is this quote from?
> 
> If this is not a quote and meant to be a note/highlight/tip/etc., this should use the Notice block instead.

Hey @justintadlock,

Yes, this is a highlight we added when reviewing the article. Thank you for the feedback, I've just updated it to a "Notice Block" 😄

**Comment by bph** [comment]
Published: [Exploring the future of web development with WebAssembly and PHP](https://developer.wordpress.org/news/2023/08/exploring-the-future-of-web-development-with-webassembly-and-php/)

**Comment by adamziel** [comment]
I just returned from my sabbatical and it’s great to see such an amazing collaboration here. Great job everyone 🙌

**Comment by bph** [comment]
Welcome back @adamziel :-)

**Comment by Angelmmiguel** [comment]
Hope you had a wonderful sabbatical @adamziel ! Welcome back :)

**Comment by ereslibre** [comment]
Welcome @adamziel! 👏 Hope you enjoyed your sabbatical :)
