### ISSUE TITLE
Taking advantage of settings.custom in theme.json

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#145]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** June 16, 2023</sup>
From this discussion on the Dev Blog: https://developer.wordpress.org/news/2023/05/customizing-core-block-style-variations-via-theme-json/

I'm wondering if many theme authors know how to utilize the `settings.custom` property in `theme.json` and pair it with custom stylesheets.

For example:

```json
{
	"settings": {
		"custom": {
			"code": {
				"color": "#000000",
				"background": "#fafafa"
			}
		}
	}
}
```

Produces these custom properties:

```css
--wp--custom--code--color: #000000;
--wp--custom--code--background: #fafafa;
```

On its own, that's all it does. The exciting part is using these custom properties to do your own thing.

With the above example, I could style the `<code>` element (for inline code) like this in my `style.css`:

```css
:where( :not( pre ) > code ) {
	color: var( --wp--custom--code--color );
	background: var( --wp--custom--code--background );
}
```

### Why not just stick it all in your CSS file to start with?

Good question. A few reasons:

- It's useful for people who want to manage their styles entirely in `theme.json`.
- It can be customized via `/styles/{stylename}.json` files.
- It can be customized via `theme.json` files in child themes.
- For things like HTML elements like `<code>`, it'd be simple to transfer the JSON code if/when core supports the element in `theme.json`.

### Any other things you can do with it?

It's possible to couple this with Hybrid/Universal themes that use the customizer because you have access to these via PHP. For example, a classic/hybrid theme could set up custom color options in the customizer for users (they don't have Site Editor access, mind you). Then, override these via the PHP filter hooks.

### In need of an example

The above was just a quick example, so I'm opening this up to discuss potential ideas to really show off this feature. The simple use case of customizing the `<code>` element could work, but let's think a little bigger.</div>

**Comment by justintadlock** [comment]
I'm going to start working on this post this week.

**Comment by marybaum** [comment]
Cool!

**Comment by justintadlock** [comment]
I didn't expect to have a first draft ready this soon, but I was inspired: https://docs.google.com/document/d/1K1dno0ZBDwBt1qm3MyDUx1lR84BnCjQJwzqljldKCyQ/edit?usp=sharing

**Comment by marybaum** [comment]
Okey dokey! I can probably get to it sometime before tomorrow noon.

**Comment by justintadlock** [comment]
Sounds good, @marybaum. I just got motivated to write this today, and I have to jump back over to a couple of other projects for a couple of days.

**Comment by justintadlock** [comment]
I've moved this to the Dev Blog as a draft now: https://developer.wordpress.org/news/?p=1941&preview=1&_ppp=1dc0c6b120

There's a few items left (image alt text, excerpt, etc.) that's needed. Expected to publish on Thursday, 8/31.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/news/2023/08/adding-and-using-custom-settings-in-theme-json/
