### ISSUE TITLE
Working with custom slotfills

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#146]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **ryanwelcher** July  4, 2023</sup>
This would be a follow up article to [How to extend WordPress via the SlotFill system](https://developer.wordpress.org/news/2022/11/how-to-extend-wordpress-via-the-slotfill-system/) where we would show how to create a custom SlotFill and use it in an existing codebase.</div>

**Comment by ryanwelcher** [comment]
I wanted to [add my draft here ](https://docs.google.com/document/d/1WbEVYjBokokZk4A7b2ky-CUrN3bXtHOicOHPWnyYE2s/edit?pli=1)if anyone is looking to see where I am so far. It's still VERY rough and incomplete but I am moving it forward

**Comment by ryanwelcher** [comment]
My first draft is [ready for review](https://docs.google.com/document/d/1WbEVYjBokokZk4A7b2ky-CUrN3bXtHOicOHPWnyYE2s/edit)!

**Comment by justintadlock** [comment]
@ryanwelcher - First review in. I'm out of the doc now and will leave the rest to our pro copyeditors. ;)

**Comment by ryanwelcher** [comment]
@justintadlock changes implemented. If anyone else has the time, I'd love more eyes on it. cc @marybaum

**Comment by marybaum** [comment]
I can probably get to it later this afternoon!

**Comment by ryanwelcher** [comment]
> I can probably get to it later this afternoon!

Sounds great! I've started moving it into the post draft but would be happy to get feedback and finish that process off tomorrow. Thank you :)

**Comment by marybaum** [comment]
You are most welcome!

**Comment by marybaum** [comment]
I'm about half done. Now some dinner! If you'd like to finish, the main thing I'm doing is converting the passive verbs — 

"in the example below, the SlotFill component is created ..."

to active verbs —

"Now make a new SlotFill component ..."

I think it's important to use active verbs because we are teaching people to do things themselves, with their own two hands. Passive verbs imply that maybe they aren't going to be quite that responsible, as if someone else is going to come in and do it for them. I don't think that's the case! 😀 So active verbs will light a fire under their glutei maximi ...

**Comment by ryanwelcher** [comment]
Thanks @marybaum! I'm going to start making the changes in in the draft post. I want to publish this by EOW if possible.

**Comment by ryanwelcher** [comment]
I have move the post into draft - https://developer.wordpress.org/news/?p=2502&preview=1&_ppp=376857845f

**Comment by ironnysh** [comment]
Hi team! I can do the second review of the draft over the weekend (if it's not too late).
Just `assign` me if that timeframe works for you, so I'll get a notification.

Happy holiday :-)

**Comment by ryanwelcher** [comment]
@ironnysh thanks for the offer but I have already received a review and aim to publish today.

**Comment by juanmaguitar** [comment]
LGTM! ✅

**Comment by ryanwelcher** [comment]
Published here - https://developer.wordpress.org/news/2023/12/22/extending-plugins-using-custom-slotfills/

#

### Social Copy:
Learn how SlotFills can be used to create extension points in your plugin that can be used both internally and by other plugins.

https://developer.wordpress.org/news/2023/12/22/extending-plugins-using-custom-slotfills/
