### ISSUE TITLE
Attributes: what do the source and selector properties do?

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#147]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** June 29, 2023</sup>
Block attributes are typically stored in the comment delimiter, and the values are fetched from there when the block is parsed to be displayed in the editor. But did you know that attribute values can also be stored in the block content? You can use the `source` and `selector` properties to determine where in the saved block the attribute values are fetched from at parse time.

This post will be an introduction to using and saving attributes - basically a friendlier and more tutorial-based version of the content in the [Attributes page](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/) in the handbook, and with more examples.
</div>

**Comment by mburridge** [comment]
A [draft of this post](https://docs.google.com/document/d/1QVIS7mCZW6Kam2QXlHF06dQoFoy8zWKncbETlP6qyhU/edit?pli=1) is now ready for review.

**Comment by mburridge** [comment]
A public preview of the attributes post is now available for review:
https://developer.wordpress.org/news/?p=1981&preview=1&_ppp=ec5d6c5e35

**Comment by mburridge** [comment]
Pre and post publishing checklist:

- [x] Post Title in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identifies?
- [x]  Is there an explicit Excerpt?
- [x]  Props added?
- [x] 🙌 Publish! 📗
- [x]  add Props for reviews to #props channel in WP Slack
- [x]  close the issue with a comment to link to the published post
- [x]  close the accompanying discussion with w link to the publish post.

**Comment by bph** [comment]
Hi @mburridge 
I really like that you want through the topic one step at a time. This is an excellent post for beginners. 

- added one more subheader at the beginning 
- added a Table of contents. 
- added alt-text to all images (was missing from your copy of the [pre-publish checklist](https://github.com/WordPress/developer-blog-content/issues/19)) 
- uploaded all images from Google doc
- selected the social image. 

I went ahead and published it. 🚢

Hope, you are ok with the small changes. 

Please review your [post-publish check from this issue](https://github.com/WordPress/developer-blog-content/issues/19)

**Comment by mburridge** [comment]
Now published: https://developer.wordpress.org/news/2023/09/understanding-block-attributes/
