### ISSUE TITLE
How to disable specific blocks in WordPress

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#148]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/139

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** June 30, 2023</sup>
"How do I disable the Spacer block?"
"How do I disable certain blocks based on the role of the user?"
"How do I disable certain blocks on posts but not on pages?"

These questions seem to come up often, and there is no comprehensive guide on how to do this and what the current limitations are around controlling blocks. This article would explore this topic and provide examples of how to achieve common use cases. </div>

**Comment by ndiego** [comment]
At long last, this article is ready for its first review: https://docs.google.com/document/d/1jv8boQcy-g_e1bV2ZVbsCtl8RgCfGdESoIWG3dxQhBE/edit?usp=sharing

**Comment by justintadlock** [comment]
First review is done. I didn't even know about using `allowedBlocks` in patterns. I'll definitely be taking advantage of that tip!

**Comment by ndiego** [comment]
**Pre-publishing checklist**

- [x]  Post Title and subheaders in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identified?
- [x]  Is there an explicit Excerpt? (not optional)
- [x]  Do all images have an alt-text?
- [x]  Props added?
- [x]  🙌 Publish! 📗 🎉

**Post-publishing checklist**

- [x]  add Props for reviews to #props channel in WP Slack
- [x]  close the issue with a comment to link to the published post
- [x]  close the accompanying discussion with link to the publish post.

**Comment by ndiego** [comment]
@dansoschin has provided the 2nd review. Thanks Dan!

**Comment by bph** [comment]
@ndiego Congrats for getting ready to publish. 
We have a few more items on the pre-publish check list, though. 

- [x] Are all images files uploaded to the media library
- [x] Assign or upload a featured image
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))

**Comment by ndiego** [comment]
Thanks @bph!

**Comment by ndiego** [comment]
Social copy: 

> Have you ever wanted to disable specific blocks in WordPress? Perhaps to simplify or curate the editing experience? 
>
> The latest Developer Blog article walks you through each available method. Dive in for the details! 
> 
> https://developer.wordpress.org/news/2024/01/29/how-to-disable-specific-blocks-in-wordpress/

Post is published: https://developer.wordpress.org/news/2024/01/29/how-to-disable-specific-blocks-in-wordpress/

**Comment by ndiego** [comment]
Social post scheduled
