### ISSUE TITLE
Type series post 2: the anatomy of a character

### ISSUE THREAD

**Issue by marybaum** [WordPress/developer-blog-content#151]
Next post in the series.

**Comment by marybaum** [comment]
Ready for first review. Finally! 

I would like to add some third-party references.

First, the two pages I cribbed a lot of the terms from:
https://www.canva.com/learn/typography-terms/
https://www.fontshop.com/glossary

I could also see doing an extra piece just on classifications.

**Comment by justintadlock** [comment]
@marybaum - It looks like you forgot the link to the Google Doc. :)

**Comment by marybaum** [comment]
Well dayum. How bout this? https://docs.google.com/document/d/1Z3Rfoy63cKlwYBw2L2DLmvTtqTS2Cwb4-FwnEwsO7rg/edit#heading=h.p5o949hqmvru

**Comment by marybaum** [comment]
Thanks for the catch!

**Comment by justintadlock** [comment]
I just wrapped up a first review. Just a few comments from me. I really like the choice of typefaces!

As for the third-party links, those look OK to me.

**Comment by annezazu** [comment]
Reviewed and left just a few comments here and there. I can't help but also see a few opportunities to touch on some outside resources. For example, perhaps we could link to https://fontreviewjournal.com/ for anyone who wants to go deeper in learning about fonts (it's run by https://profiles.wordpress.org/heckhouse/). Tied to this, I wonder about connecting this post to the work around having a font library and how we can weave that in: https://github.com/WordPress/gutenberg/issues/52698 It's slated for 6.4 so might help tie the series into real world application of WordPress in the future. 

Otherwise, looks good!

**Comment by marybaum** [comment]
Thanks very much! I will add that in. One thing, though: fonts are merely the files we install. The thing that’s interesting to me is type — since the spring of 1975!

**Comment by marybaum** [comment]
Parking this here for now.
https://fonts.google.com/knowledge/introducing_type/making_sense_of_typographic_classifications
Think I'll add a reference section with the links up top, this on classifications and the review journal.

**Comment by marybaum** [comment]
skipping the Font Review Journal. It's actual reviews and design examples of fewer than 100 typefaces (not even whole families) and her WP profile page is blank.

**Comment by marybaum** [comment]
Public preview in the P2: https://developer.wordpress.org/news/?p=1855&preview=1&_ppp=83f668dd29

**Comment by justintadlock** [comment]
@marybaum - This looks good to go now, so publish whenever you're ready.

Jetpack has a new social image feature that we're using, which may be different since the last time you published. You can configure it via the Jetpack (icon) menu item.

**Comment by marybaum** [comment]
Thanks!... from my phoneOn Aug 17, 2023, at 8:19 AM, Justin Tadlock ***@***.***> wrote:﻿
@marybaum - This looks good to go now, so publish whenever you're ready.
Jetpack has a new social image feature that we're using, which may be different since the last time you published. You can configure it via the Jetpack (icon) menu item.

**Comment by marybaum** [comment]
Published!

**Comment by marybaum** [comment]
https://developer.wordpress.org/news/2023/08/the-anatomy-of-a-letterform/

**Comment by marybaum** [comment]
Social copy:

Typography series part 2: The anatomy of a letterform. Letters have parts! See how they combine to give a typeface its voice.
