### ISSUE TITLE
Beyond Block Styles: Part 2

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#152]
This will be Part 2 of a planned three-part series. It will cover laying the foundational design work before integrating it as an editor control in Part 3.

For the full details, see:

- [Approved Topic Idea](https://github.com/WordPress/developer-blog-content/discussions/130)
- [Part 1](https://github.com/WordPress/developer-blog-content/issues/144)

**Comment by justintadlock** [comment]
I'll work on Part 2 in the Google Doc: https://docs.google.com/document/d/1d0vl8-YcbLQtsCC2pgJX1cWqQMMoqg1kL4D-zbLuX4k/edit?usp=sharing

**Comment by justintadlock** [comment]
Part 2 is now ready for review: https://docs.google.com/document/d/1d0vl8-YcbLQtsCC2pgJX1cWqQMMoqg1kL4D-zbLuX4k/edit?usp=sharing

**Comment by marybaum** [comment]
On it!

**Comment by bph** [comment]
Left a few notes. Also tested the code. Works as expected. Can't wait for the next part :-) Maybe that fixed the gradient.

**Comment by marybaum** [comment]
Done with copy review!

**Comment by justintadlock** [comment]
Awesome work, @bph and @marybaum! I'm working through it all.

**Comment by justintadlock** [comment]
All right, the draft is polished and in the system. Just need a final ✅  to publish. Public preview link: https://developer.wordpress.org/news/?p=1723&preview=1&_ppp=9f5e150360

**Comment by justintadlock** [comment]
Note to self: remember to set social image.

**Comment by marybaum** [comment]
Thanks!!... from my phoneOn Jul 27, 2023, at 8:42 AM, Justin Tadlock ***@***.***> wrote:﻿
Awesome work, @bph and @marybaum! I'm working through it all.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/news/2023/07/beyond-block-styles-part-2-building-a-custom-style-for-the-separator-block/

---

Social copy:

> Learn how to create a custom emoji style for the Separator block in the latest of this three-part series on extending the editor from a WordPress theme:
>
> https://developer.wordpress.org/news/2023/07/beyond-block-styles-part-2-building-a-custom-style-for-the-separator-block/

If we wanted to publish a second social post pointing back to Part 1:

> Miss out on Part 1? Check out how to integrate the WordPress scripts package in your theme:
>
> https://developer.wordpress.org/news/2023/07/beyond-block-styles-part-1-using-the-wordpress-scripts-package-with-themes/
