### ISSUE TITLE
A tutorial on how to create block variations

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#155]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** July 30, 2023</sup>
This needs a catchy title, but the article would cover:

- What are block variations
- How to create block variations
- Why you would want to use block variations for your own projects
- 3-4 real-world examples of block variations

Currently, there isn't a dedicated Dev Blog article on block variations. This article would serve as a foundational piece of content. Future articles could explore more sophisticated implementations of variations while referring back to this article for the basics.  </div>

**Comment by ndiego** [comment]
The draft of this article is available here: https://docs.google.com/document/d/1hPgTs4qpcwGqiSQ_2wFqjm3_xP2gHZp7ZGXvaVRh6G0/edit

**Comment by ndiego** [comment]
Thanks @juanmaguitar, @justintadlock, and @mburridge for the first review.

**Comment by rmartinezduque** [comment]
This looks great, @ndiego! I've left some minor suggestions that (I think) might improve its readability and clarity in some sentences. Feel free to accept or reject them as you see fit :)

> Why you would want to use block variations for your own projects.

I see that throughout the article/examples, this point is implied and briefly mentioned in the introduction, but I think it's perhaps the least explicit. It would be great to reiterate some advantages of block variations in the closing paragraphs.

**Comment by juanmaguitar** [comment]
Thanks @rmartinezduque for your review! 🙏

**Comment by ndiego** [comment]
Thanks @rmartinezduque!

**Comment by ndiego** [comment]
Pre-publishing checklist:

- [x]  Post Title and subheaders in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identified?
- [x]  Is there an explicit Excerpt? (not optional)
- [x]  Do all images have an alt-text?
- [ ]  Props added?
- [x] 🙌 Publish! 📗 🎉

Post-publishing checklist

- [x]  add Props for reviews to #props channel in WP Slack
- [x]  close the issue with a comment to link to the published post
- [x]  close the accompanying discussion with link to the publish post.

**Comment by ndiego** [comment]
Published article: https://developer.wordpress.org/news/2023/08/an-introduction-to-block-variations/
