### ISSUE TITLE
How WordPress plugin developers can keep their users content

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#163]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **dartiss** June 23, 2023</sup>
This will be a post based on [the talk of the same name from WCEU 2023](https://europe.wordcamp.org/2023/session/10-things-that-all-wordpress-plugin-developers-should-avoid/). However, I will omit most screenshots where specific plugins are used (I don't want to finger point).

The 10 items will be...

1. Aggressive Promotion
2. Inconsistent and confusing menus
3. Don’t take over the user process
4. Avoid creating your own UI
5. Lack of data validation
6. Loading unnecessary content
7. Leaving content behind
8. Forgetting Accessibility Standards
9. Ignoring code quality checking
10. Getting lost in your translations</div>

**Comment by dartiss** [comment]
Potential re-title, "How WordPress plugin developers can keep their users content", or something similar. My SO is a word-smith so may help me wrangle something better. My plan is to switch around the original WCEU content to be more positive.

**Comment by bph** [comment]
Thank you @dartiss I updated the title of the issue to reflect the new working title.

**Comment by dartiss** [comment]
[Draft is occurring here](https://docs.google.com/document/d/1fpkGatsL8IosD48t2jtRVwxSqbLGmn4RLhG6TyCak-w/edit#heading=h.swha9ceb7u8v). I started this before a lot of the previous discussion happened, so don't panic if reading this soon after I write this 😉

**Comment by dartiss** [comment]
Is there a preferred word count for any articles, @bph (in particular a maximum)?

**Comment by juanmaguitar** [comment]
> [Draft is occurring here](https://docs.google.com/document/d/1fpkGatsL8IosD48t2jtRVwxSqbLGmn4RLhG6TyCak-w/edit#heading=h.swha9ceb7u8v). I started this before a lot of the previous discussion happened, so don't panic if reading this soon after I write this 😉

@dartiss could you provide permission to comment in the doc to anyone accessing with the link?

**Comment by bph** [comment]
Not really. @dartiss  Most post have between 1 - 2000 words but there are also post around 800.

**Comment by dartiss** [comment]
I'll try for the 2000 then 😆

**Comment by dartiss** [comment]
> @dartiss could you provide permission to comment in the doc to anyone accessing with the link?

Of course - now done

**Comment by dartiss** [comment]
Apologies - quick follow up question. My word count is at 1300 and I'm not even half way through. Are you happy if it's bigger than 2000 words, or should I look to be trimming it down to fit round-about that figure?

**Comment by bph** [comment]
Totally ok with a 2000 word count. It just takes a bit longer for reviewers get through 👏💪

**Comment by dartiss** [comment]
So, if it ends up as 3000 words, you'd prefer me to trim it down?

**Comment by bph** [comment]
Well, it's hard to judge without reading it, you can also make it a two-part series. I won't get to reading it until next week, though.

**Comment by dartiss** [comment]
Okay, well the main core of the article is now written (see the link above - you should all have comment access on it). I need to do a read-through and tidy up but happy for comments in the meantime.

**Comment by justintadlock** [comment]
On word counts: we don't have any specific rules. I've got a few that are 2,000+ words and at least one that is 3,000+. But I broke my 7,000-word post into a three-part series.

The one thing that I would add is that it's nicer if you can break those longer posts up a bit by adding media, making liberal use of lists and headings, and doing anything you can to avoid walls of text. People tend to scan blog posts a lot, so those things can help hook them in (and hopefully get them to read the full thing).

**Comment by dartiss** [comment]
Thanks Justin. It's already divided into titled sections but I'll see if I can add any screenshots to use that don't highlight specific plugins.

**Comment by dartiss** [comment]
Read through, tidied up and added some screenshots. I think it's now ready.

**Comment by bph** [comment]
@dartiss I added a few comments, mainly about external links and resources we can add to the post, also some reflexive miniscule 'corrections'. 

You should have received an invitation to join the WordPress Developer Blog as 'author' via email to your .org associated email address. Once you confirm, you should be able to access the blog via https://developer.wordpress.org/news/wp-admin and when you are ready to add your draft post there.

**Comment by dartiss** [comment]
I've addressed all your comments, @bph, and have [now added this to the blog](https://developer.wordpress.org/news/wp-admin/post.php?post=2096&action=edit) as a draft.

**Comment by dartiss** [comment]
2049 words

**Comment by bph** [comment]
Awesome @dartiss 
I forgot to mention: Could you please enable the public post preview link and share here? 
<img width="287" alt="Screenshot 2023-09-20 at 12 07 17" src="https://github.com/WordPress/developer-blog-content/assets/39980/06161439-5cbe-4eb9-b458-a7e12e40f966">
Then reviewers from the #core-dev-blog channel don't have to login for the second review.

**Comment by bph** [comment]
I also want to introduce you to our pre-publish and post publish checklist for after second review. 
### Pre-publishing checklist: 

- [x] Post Title in Sentence case
- [x] Use "Center Column" template
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Do all images have an alt-text?
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
🙌 Publish! 📗

### Post-publishing checklist
- [ ] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
- [ ] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post.

**Comment by dartiss** [comment]
[Done](https://developer.wordpress.org/news/?p=2096&preview=1&_ppp=1cf6834469).

I use that plugin myself for sharing drafts - I've never come across anybody else before that uses it 😊

**Comment by dartiss** [comment]
> I also want to introduce you to our pre-publish and post publish checklist for after second review.

Is this something you want me to do now, as you mention it's "for after second review"?

**Comment by bph** [comment]
Oh, right, I didn't mean it as 'in sequence'. Figured you want to wait for feedback from the second review to get back into the post again, but you can do as you please, as long as you keep the post in draft, until after the second review. :-)

**Comment by dartiss** [comment]
I've now done everything on the pre-publishing checklist (no props, though, as nobody else was involved).

**Comment by bph** [comment]
For reference 
The props.relevant guideline
https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props

**Comment by dartiss** [comment]
Published here: https://developer.wordpress.org/news/2023/09/how-wordpress-developers-can-keep-their-users-satisfied/

---

Social copy:

Learn how WordPress plugin developers can continue to keep their users satisfied, via a number of things that they should make sure we’re doing:

https://developer.wordpress.org/news/2023/09/how-wordpress-developers-can-keep-their-users-satisfied/

**Comment by sybrew** [comment]
Discussion https://github.com/WordPress/developer-blog-content/discussions/136 is locked and limited to collaborators??

Anyway, I think this issue is a good fit to highlight this.

In https://developer.wordpress.org/news/2023/09/how-wordpress-developers-can-keep-their-users-satisfied/ under the heading "Clean up after yourself" (there's no anchor): 

Transients are scheduled to be deleted daily via `delete_expired_transients()`. What was observed prompting that part of the article claiming otherwise was probably a caching plugin's setting messing things up.

**Comment by dartiss** [comment]
You're 100% correct - I've just checked and confirmed this. I was involved with a discussion about transient housekeeping a long time ago and thought this was still lacking.

I've updated the article and will add some props to it for your help - thanks @sybrew
