### ISSUE TITLE
Creating a custom External Template for the @wordpress/create-block package

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#166]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **ryanwelcher** August 28, 2023</sup>
[External Templates](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/packages-create-block-external-template/) are a very powerful tool to allow complete customization of block structure that is not widely known.

The article will focus on the technical steps of creating a template but from the use-case of an extender wanting to add more blocks to an existing plugin with pre-set values.

At the end of the article, I'd like to add a call for templates to allow the extender community to share their templates.</div>

**Comment by ryanwelcher** [comment]
Draft is ready for first review - https://docs.google.com/document/d/1elbSquxQC5yNE-asPeN_l65QWMQfrCxRp4PYtSqtkzM/edit

**Comment by bph** [comment]
Great article. Of course, I had a few comments. 🧐

**Comment by justintadlock** [comment]
@ryanwelcher - This looks like it's had two reviews or is the second review still in progress? I'm not 100% sure, but I'd like to get the ticket status updated.

**Comment by ryanwelcher** [comment]
I'd say the first review is complete. I'll move it into the post next and then ping for a second review via the preview.

**Comment by ryanwelcher** [comment]
I moved the post into a preview -https://developer.wordpress.org/news/?p=3420&preview=1&_ppp=7b6492b0c6

There seems to be some issues with the code block that I'll tackle on Monday

**Comment by bph** [comment]
@ryanwelcher yes, sorry about that. Nick is on it, though.  https://github.com/WordPress/wporg-developer-blog/pull/61

**Comment by justintadlock** [comment]
Running through the second review now.

**Comment by justintadlock** [comment]
Good work, @ryanwelcher! The second review is in, which is mostly grammar and punctuation changes.

**Comment by ryanwelcher** [comment]
I've updated the post, adding an excerpt and featured image. 

Preview: https://developer.wordpress.org/news/?p=3420&preview=1&_ppp=dadf4f97be

Social Media Post:

The create-block package is a fantastic time-saving tool that allows you to quickly and consistently create custom blocks for your projects with a single command. With External Project Templates you can take full control of create-block to customize how you build your blocks.

**Comment by ryanwelcher** [comment]
cc @bph @justintadlock

**Comment by bph** [comment]
Howdy @ryanwelcher Awesome article. 
If that's ok with you, we schedule the article for next week on Tuesday (4/16) for publishing 

Just for convenience, here again the checklists: 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by bph** [comment]
What's missing is the Social post (unless that's what you call 'post excerpt'?

**Comment by ryanwelcher** [comment]
> What's missing is the Social post (unless that's what you call 'post excerpt'?

Yes, that's what I called it.

**Comment by ryanwelcher** [comment]
I've changed the title of the post to `Creating an external project template for create-block` - FYI

`Props @greenshady, @bph and @dansoschin for providing feedback and reviewing this post.`

**Comment by ryanwelcher** [comment]
> If that's ok with you, we schedule the article for next week on Tuesday (4/16) for publishing

Totally fine with me! Should I schedule it WP or just hit publish then?

**Comment by ryanwelcher** [comment]
I've scheduled it in WP

**Comment by ryanwelcher** [comment]
Post is live - https://developer.wordpress.org/news/2024/04/16/creating-an-external-project-template-for-create-block/

**Comment by juanmaguitar** [comment]
Social scheduled for May 7th

**Comment by flexseth** [comment]
Just wanted to raise awareness about some semantics around using the `webpackConfig` file

- https://github.com/WordPress/gutenberg/discussions/44010

Not sure if it's mentioned in the post, but might be a good idea to test the code in the post to make sure it is working. **Disclaimer:** I have not tested, but it's been reported twice via the post above
