### ISSUE TITLE
An overview of the "Block hooks" 

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#168]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** September  1, 2023</sup>
The feature for "[Auto-inserting blocks](https://github.com/WordPress/gutenberg/issues/53987)" is coming in WordPress 6.4. The name might still [be TBD](https://github.com/WordPress/gutenberg/issues/53987#issuecomment-1695915874), but the approach for this article will be an overview of the feature with 2-3 examples of how it can be used. 

This feature has major implications for extenders and the article, coupled with technical documentation, will help educate the community. Ideally, this should be published right after Beta 1 (9/26)

Edit: This feature is now called [Block hooks](https://github.com/WordPress/gutenberg/pull/54147).</div>

**Comment by ndiego** [comment]
This post is going to be put on hold until the 6.5 release cycle. The current implementation of Block Hooks has a number of limitations that will be addressed following the release of 6.4. Therefore, it makes the most sense to wait until the feature receives additional development to spotlight on the Developer Blog.

**Comment by ndiego** [comment]
The drafted article is available here: https://docs.google.com/document/d/1U-sUW0YM1tq1YblHf5zAGWcR5k35ujO3t81y_wWzZo8/edit 

@ockham has already provided a technical review. 🙏

**Comment by justintadlock** [comment]
Great work with this, Nick! First review is complete.

**Comment by ndiego** [comment]
Given the length and breadth of this article, I changed the title to "Exploring the Block Hooks API in WordPress 6.5". Let me know what you all think. It is the same title as the [Developer Hours session](https://www.meetup.com/learn-wordpress-online-workshops/events/299677581/), but the session will be covering the examples in the article, so I kinda like the symmetry.

**Comment by bph** [comment]
I am looking at it in the Public Post Preview. 
- I would remove the Example: 1 & Example 2 etc. from the subheaders or put them into parenthesis at the end of the subheader. It's not the most important part of what you are describing. (and better for SEO) 
- Examples 3 second sentence - "the Block Hooks API only worked with [dynamic blocks](https://developer.wordpress.org/block-editor/getting-started/fundamentals/static-dynamic-rendering/), not statically rendered ones." wouldn't it be the other way around? Save = null is for dynamic blocks.. And that wasn't possible. - It also feels that the distinction doesn't matter in the example? 

I also share for your convenience the two check lists. 


### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ndiego** [comment]
> I would remove the Example: 1 & Example 2 etc. from the subheaders or put them into parenthesis at the end of the subheader. It's not the most important part of what you are describing. (and better for SEO)

All fixed! 

> Examples 3 second sentence - "the Block Hooks API only worked with [dynamic blocks](https://developer.wordpress.org/block-editor/getting-started/fundamentals/static-dynamic-rendering/), not statically rendered ones." wouldn't it be the other way around? Save = null is for dynamic blocks.. And that wasn't possible. - It also feels that the distinction doesn't matter in the example?

Ahh good catch. "not hook blocks" was supposed to say "only hook blocks". All fixed. 

The distinction here is really for folks who tried out the API in 6.4 and ran into the dynamic block limitation. You couldn't hook a Paragraph block with content until 6.5. 

Thanks for reviewing 🙏

**Comment by ndiego** [comment]
The article has been published! 🎉

**Social copy**

> The Block Hooks API is an extensibility mechanism that allows you to dynamically insert blocks into block themes. Learn how to use the API in your own projects in this comprehensive overview on the Developer Blog.
>
> https://developer.wordpress.org/news/2024/03/25/exploring-the-block-hooks-api-in-wordpress-6-5/
