### ISSUE TITLE
What's new for developers (October 2023)

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#170]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Google Doc: https://docs.google.com/document/d/1_lhva1_BB3eHM8DVpuazCHTUQUzLHL3UjGtdkw-S4Ts/edit#heading=h.8c87ntigzvhh

Resources to track:

[Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
[A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
[Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
[Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
[Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by dingo-d** [comment]
Hi!

I'd like to report the release of the 3.0.1 version of WordPress Coding Standards: https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/3.0.1

**Comment by bph** [comment]
Congrats for the fast release! @dingo-d - Thank you so much for sharing we'll add it to the post.

**Comment by justintadlock** [comment]
Just a heads up that the linked Google Doc is not currently public. :)

**Comment by bph** [comment]
It is now open to be commented on to anyone with a link :-) Thanks @justintadlock for the ping!

**Comment by justintadlock** [comment]
**Breaking change with fonts**

- https://github.com/WordPress/gutenberg/issues/54605
- https://github.com/WordPress/twentytwentyfour/pull/422

This came up in a convo today, so it'll definitely be worth looking into if it's not addressed in GB/Core.

**Comment by justintadlock** [comment]
This ticket was passed along by Dave Smith: https://github.com/WordPress/gutenberg/pull/54590

It looks like it's in the Gutenberg 16.8 release, so y'all will probably catch that one anyway.

**Comment by bph** [comment]
@justintadlock Thanks. Seem it's slated to be cherry-picked for 16.7 and 6.4 -

**Comment by bph** [comment]
Needs to be highlighted, too 
https://github.com/WordPress/gutenberg/pull/54494

**Comment by juanmaguitar** [comment]
[Plugin Checker](https://wordpress.org/plugins/plugin-check) - To be highlighted 
https://make.wordpress.org/plugins/2023/09/19/update-turning-the-tide/

**Comment by annezazu** [comment]
Noting this as something to include: https://github.com/WordPress/gutenberg/pull/44214

**Comment by bph** [comment]
> Needs to be highlighted, too
https://github.com/WordPress/gutenberg/pull/54494

will be moved to the November edition. the PR is part of the 16.8 which will come out after the publishing date of the October edition. (10/10)

**Comment by bph** [comment]
> @annezazu Noting this as something to include: https://github.com/WordPress/gutenberg/pull/44214 

This will be in the Plugin release 16.8 and will be covered in the November edition of **What's new for developers**

**Comment by bph** [comment]
[Public preview is now available. ](https://developer.wordpress.org/news/?p=2139&preview=1&_ppp=60867c2dce) for first review

### Pre-publishing checklist: 

- [x] Post Title in Sentence case
- [x] Use "Center Column" template
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by justintadlock** [comment]
I did a quick review and found some minor issues. I didn't make any changes directly since this is already a draft post:

- Dates shouldn't use the ordinal number (e.g., 1st, 2nd, etc.). For example, "November 7th, 2023" becomes "November 7, 2023."
- In the intro section, "nexxt major" should be "next major."
- Use the Notice block instead of a Paragraph block for the alert box. It will have the correct padding.
- Can you add a screenshot for the Background for Group blocks section? It's not 100% necessary, but if it's worth highlighting, I like to showcase it visually.
- Make sure to change backticks to inline code in the editor. There are a few spots (probably where I added them in the initial doc).
- "light box" should be "lightbox."
- The lightbox code example could be tightened up by removing the extra spacing between lines.
- The list in the "More design tools for Core blocks" has inconsistent period usage at the end of the list items. I'd prefer to add a period after each here.
- Need a link for the "Font Library and Management" section. Actually, do we need this section at all? It's already mentioned in the intro.

**Comment by bph** [comment]
@justintadlock Thank you for the thorough review. All issues fixed. 

It's scheduled now for October 10 at 3pm UTC 
Again the [publish preview link here](https://developer.wordpress.org/news/?p=2139&preview=1&_ppp=60867c2dce)

**Comment by bph** [comment]
## Social Copy: 
Gutenberg as a framework, Background image in Group block, Lightbox for images and so much more: October roundup of What's new for Developers
https://developer.wordpress.org/news/2023/10/whats-new-for-developers-october-2023/ #WordPressDevBlog

## Published 
[What’s new for developers? (October 2023)](https://developer.wordpress.org/news/2023/10/whats-new-for-developers-october-2023/)

**Comment by bph** [comment]
schedule for 2/26 on social networks.
