### ISSUE TITLE
A walk-through tutorial on using the Create Block Theme plugin

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#173]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/171

<div type='discussions-op-text'>

<sup>Originally posted by **tinjure20** September 27, 2023</sup>
I am a huge fan of the [Create Block Theme](https://wordpress.org/plugins/create-block-theme/) (CBT) plugin, which is a must-have in my workflows, serving as a swish knife like tool for creating block themes. I had made a draft document about how to use the plugin a while ago, but it may need to be updated with the latest WP & CBT plugin releases.

IMO, this would be a useful walk-through tutorial topic, and adding it to the list for discussion with a link to the Google Doc.

https://docs.google.com/document/d/1uh4Pn-jtVXJ1pmbcCGs7bYAhPFs12L-qVqdxIhu1qww/edit?usp=sharing</div>

**Comment by bph** [comment]
Please continue conversation on the issue

- #173

This discussion space is locked in favor of the issue.

**Comment by tinjure20** [comment]
Thank you @bph. I will take up this issue and update the draft with the latest WP & CBT plugin releases.

**Comment by bph** [comment]
Howdy @tinjure20 I started going over the [Google Doc. ](https://docs.google.com/document/d/1uh4Pn-jtVXJ1pmbcCGs7bYAhPFs12L-qVqdxIhu1qww/edit?usp=sharing) and you'll see a few comments and edits. I am ot sure if you are ready for a review yet, but I wanted to get a head start on this article. 
I am not yet completely done and hope to continue later today.

**Comment by tinjure20** [comment]
@bph Thank you very much for taking the time to review the [Google Doc](https://docs.google.com/document/d/1uh4Pn-jtVXJ1pmbcCGs7bYAhPFs12L-qVqdxIhu1qww/edit?usp=sharing). I have taken care of your initial comments. After your second look, I would request one of the themereview team members have a second review.

**Comment by bph** [comment]
@tinjure20  It's a great walk-through all the options. it might need a some formatting once it is drafted on the blog. 

You might need to do some work on your screenshot, though. most of them have poor color contrast, and you might need to change the font for the comments in your editor, as it's barely readable. 

I am done with the review and comments.

**Comment by tinjure20** [comment]
@bph Thank you very much. I will take care of your comments, recreate some screenshots that are eligible to read, and address any formatting issues once the content has been ported to the blog draft.

**Comment by bph** [comment]
@tinjure20 just a question for my planning, would you be able to push the article forward in the next two week? I'll head into Christmas/End of year vacation on Dec 15, 2023, and it would be great if we can publish your article before that.

**Comment by tinjure20** [comment]
@bph, sure, I could do it as soon as its second review is complete. IMO, the [Navigation Block](https://github.com/WordPress/developer-blog-content/issues/149) article is almost ready, I am **waiting** for its copy-editing to be completed. I could do both within the next two weeks.

**Comment by abhansnuk** [comment]
Hello @tinjure20 thanks for all your work on this post. I have edited the article in the google doc. Comments added in there.

To add:
- I have added a couple of notes about alt attributes about images, but they apply to all images being added please. We are also asking all writers to consider the names they add for images when they are uploading them to the media library too, and not supplying the images as links. Hope that added info helps as you move the article.
- The editors and reviewers names are to add in a props line at the end of the post.
- Excerpt

Thanks.

@bph there is a real mix of how the 'Site Editor' is being capitalized in general. The 6.4 documentation post which covers the features has 'Site editor', the [main documentation page](https://wordpress.org/documentation/article/site-editor/) has a mix. I've seen recent edits taking it to 'Site editor', but that may have changed again (I can't recall the last update on this). Do you? We can then make this particular post consistent with this and the other documentation still in progress.

**Comment by tinjure20** [comment]
@abhansnuk, I greatly appreciate your review and comments on the article. I have addressed your feedback and will begin transferring the Google Doc content (images as suggested) to the CMS.

**Comment by tinjure20** [comment]
@bph The article is now in [public preview](https://developer.wordpress.org/news/?p=2275&preview=1&_ppp=3bd6e7717e). I have reviewed the following pre-publication list, but if I have missed anything, please let me know. 

- Post Title in Sentence case - yes
- Are Category or Categories selected? - yes
- Are Tags identifies? - yes
- Is there an explicit Excerpt? - yes
- All images files uploaded to media library - Yes
- Image alt caption - yes

**Comment by bph** [comment]
Here is the full list: 

### Pre-publishing checklist: 

- [x] Post Title in Sentence case
- [x] Use "Center Column" template
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x]  add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by tinjure20** [comment]
Draft updated with "center column" template and a "featured image" assigned. Pops have been added already. The last one (from the pre-publish check list), below, is a draft that you may wish to revise.

"This walk-through tutorial guides users how to use the Create Block Theme plugin to create a customized theme by overwriting, cloning, adding style variations, and exporting any block theme."

I am not sure if I have permission to complete all the post-publish list, except the "add Props for reviews to #props channel in WP Slack"

**Comment by bph** [comment]
Thank you. Let's get it over the finish line!

**Comment by bph** [comment]
It's scheduled to be published: December 5, 2023 10:00 am UTC+0

**Comment by tinjure20** [comment]
Thank you @bph , @abhansnuk, and @justintadlock. The article is [published](https://developer.wordpress.org/news/2023/12/a-walk-through-tutorial-on-using-create-block-theme-plugin/).
