### ISSUE TITLE
What's new for developers? (November 2023)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#174]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1v8kmYmRY3_3FH7WawKxXoHyQ1g4_-mfYyO6xL5oAp4g/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by justintadlock** [comment]
Noting this for later: https://twitter.com/aurooba/status/1714323750781665402

**Comment by bph** [comment]
suggested being included in our round-up however  punted to Nov edition because of release schedule cc @justintadlock 

- https://github.com/WordPress/gutenberg/pull/44214
- https://github.com/WordPress/gutenberg/pull/54494

**Comment by justintadlock** [comment]
The draft for this is now ready for review: https://docs.google.com/document/d/1v8kmYmRY3_3FH7WawKxXoHyQ1g4_-mfYyO6xL5oAp4g/edit?usp=sharing

**Comment by thetinyl** [comment]
@justintadlock Nice! Took a look and made some suggestions in the doc for your consideration.

**Comment by justintadlock** [comment]
@thetinyl - Thanks for the review!

This is now drafted on the Dev Blog and ready to be published tomorrow: https://developer.wordpress.org/news/?p=2190&preview=1&_ppp=12515b033f

**Comment by justintadlock** [comment]
Published! 🎉 

**Social Copy:**

> With WordPress 6.4 now shipped around the world, make sure you catch up with all the developer-focused changes in the latest release and get a look ahead at some upcoming features:
>
> https://developer.wordpress.org/news/2023/11/whats-new-for-developers-november-2023/

**Comment by bph** [comment]
scheduled on social for 2/27
