### ISSUE TITLE
What's new for developers? (December 2023)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#177]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1P2rOTSi-4_1fGavaVpXexXfEIQyDkEK_ItBNJzwZDJs/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by justintadlock** [comment]
@bph Since the week in core posts haven't come out regularly lately, I reviewed the [last 60 days on Trac](https://core.trac.wordpress.org/timeline?from=11%2F30%2F2023&daysback=60&authors=&ticket=on&changeset=on&repo-=on&repo-design=on&repo-tests=on&sfp_email=&sfph_mail=&update=Update). We can use that link in the future (just have to update the times in the form). Mostly, what we need to find are just the changesets, which are generally what I need when putting the final post together.

**Comment by justintadlock** [comment]
This doc is now ready for review: https://docs.google.com/document/d/1P2rOTSi-4_1fGavaVpXexXfEIQyDkEK_ItBNJzwZDJs/edit?usp=sharing

**Comment by bph** [comment]
It's now available as [public preview on the site. ](https://developer.wordpress.org/news/?p=2374&preview=1&_ppp=47ceee558d) and ready for 2nd Review. It will be published on December 10th, 2023

**Comment by bph** [comment]
working through the checklists

### Pre-publishing checklist: 

- [x] Post Title in Sentence case
- [x] Use "Center Column" template
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by justintadlock** [comment]
**Social copy:**

> Check out the latest developer-focused features and changes in WordPress and Gutenberg in this final monthly roundup of 2023:
>
> https://developer.wordpress.org/news/2023/12/10/whats-new-for-developers-december-2023/

**Comment by bph** [comment]
scheduled on social for 2/28
