### ISSUE TITLE
What's new for developers? (January 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#179]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/18c3u7ltzLvngsZ5qJnoJ_FyQkLKqqxMp2c_aS0cOcTY/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by bph** [comment]
Once published, share the link and a note on the issue for [This month in WordPress](https://github.com/WordPress/Marketing-Team/issues/343) post of the marketing team before Feb 2nd 2024.

**Comment by justintadlock** [comment]
The draft is finished and now ready for review: https://docs.google.com/document/d/18c3u7ltzLvngsZ5qJnoJ_FyQkLKqqxMp2c_aS0cOcTY/edit?usp=sharing

**Comment by justintadlock** [comment]
Props to @ndiego and @bph for reviewing. I'm working through these now.

**Comment by justintadlock** [comment]
Post is in the system and ready to publish tomorrow.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/news/2024/01/10/whats-new-for-developers-january-2024/

Leaving this ticket open until I write the social copy.

**Comment by juanmaguitar** [comment]
> Leaving this ticket open until I write the social copy.

@justintadlock do you have a timeframe for this social copy?
I'm scheduling posts today and it would be great if we could get this post scheduled to be published next week.

**Comment by justintadlock** [comment]
> The developer documentation gets a facelift, Gutenberg has a new template management screen, and more developer goodies, all covered in this latest monthly roundup for WordPress extenders:
>
> https://developer.wordpress.org/news/2024/01/10/whats-new-for-developers-january-2024/
