### ISSUE TITLE
Dev Blog: 2023 Year in Review

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#187]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/176

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** November  8, 2023</sup>
@bph and I have discussed publishing a "year in review" type of post for the Developer Blog. The timeline would be to publish this early January 2024.

I haven't had a chance to outline what this might look like yet, but the primary goal would be to share everything that was published on the blog in the past year. It might be a good idea to mention a few of the bigger WordPress highlights too.

For reference, here are a few examples that I wrote while working for WP Tavern. The end result, of course, would be a bit different for the Dev Blog, but I'm hoping this might give us a few ideas:

- https://wptavern.com/reflecting-on-2019-the-year-in-review
- https://wptavern.com/2020-step-away-from-the-fire
- https://wptavern.com/wp-taverns-2021-year-in-review

Ideas welcome.</div>

**Comment by ndiego** [comment]
We could also mention the redesign 😉

**Comment by justintadlock** [comment]
Post will be written here: https://docs.google.com/document/d/143JglDIta9hplAYSReKnoQLZ027UVwuFqtRkdclsU1w/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this is now ready for review: https://docs.google.com/document/d/143JglDIta9hplAYSReKnoQLZ027UVwuFqtRkdclsU1w/edit?usp=sharing

Note: I still need to do some stat checks.

**Comment by justintadlock** [comment]
**Social Copy:**

> From 54 published posts to an overhauled design, catch up with everything that happened on the WordPress Developer Blog in 2023:
>
> https://developer.wordpress.org/news/2024/01/05/2023-year-in-review/
