### ISSUE TITLE
Pitfalls working with @wordpress/data, useSelect and useDispatch and how to avoid those.

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#190]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **bph** December 14, 2023</sup>
This post would be an updated rewrite of Jarda Snajdr [post on his personal blog two years ago.](https://jardasn.blog/2021/01/22/some-best-practices-for-using-useselect-from-wordpress-data/)0
adding a few more practices and patterns that address problems that Jarda witnessed causing performance issues recently.

The useSelect hook implementation itself has also evolved significantly in the last year or so, having been rewritten to use React 18’s useSyncExternalStore, and adding optimizations like granular subscriptions to individual stores or conditional “lazy” subscriptions.

It would be for a reader who is already familiar with @wordpress/data and useSelect and useDispatch, uses them successfully to write a custom block or plugin, but wants to improve their game and to learn more details.

_Note: Discussion title is a work in progress... it will be fixed in review process._

</div>

**Comment by jsnajdr** [comment]
Looking forward to start working on the article! 🚀

**Comment by bph** [comment]
wonderful. Just assigned the topic to you, Jarda!

**Comment by jsnajdr** [comment]
Here's a draft of the article available for comments: https://docs.google.com/document/d/1gTuFwR0O2P4s8KZQ0VNy9tkVwhT1YBptL2WlLr0S-bM/edit

**Comment by ryanwelcher** [comment]
This is a great article @jsnajdr! I've left some comments/thoughts and am happy to discuss!

**Comment by jsnajdr** [comment]
This is now a draft post in WordPress: https://developer.wordpress.org/news/?p=3015&preview=1&_ppp=bad243e253

**Comment by bph** [comment]
Hi @jsnajdr here is the 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by jsnajdr** [comment]
Social copy:

> Learn how to use the useSelect React hook more effectively. This article offers many tips and tricks and insights about this part of the @wordpress/data package.

**Comment by justintadlock** [comment]
I know this has already been reviewed, and we're close to publishing. But I just did a quick run-through the article, and something stood out to me as missing. 

When or why should I (as the reader) use the `useSelect()` hook? It might not hurt to throw this into the introduction section. That way, it just gives the reader more of a sense of whether this is something they want to dive into.

**Comment by jsnajdr** [comment]
> When or why should I (as the reader) use the `useSelect()` hook?

I added a sentence to the opening paragraph that describes where and why the hook is used -- in the UI components of the block editor and of custom blocks. That should make the article start less abruptly, and should give you some picture whether this is an area of WordPress development that you are interested in.

**Comment by bph** [comment]
Published 🙌 [How to work effectively with the useSelect hook](https://developer.wordpress.org/news/2024/03/28/how-to-work-effectively-with-the-useselect-hook/)

**Comment by bph** [comment]
scheduled for April 22
