### ISSUE TITLE
Tutorial: Adding Starter Page and Template Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#194]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/180

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** December 12, 2023</sup>
Currently, there is little documentation for adding Starter Page Patterns and Starter Template Patterns. There are plans to add docs for these in the Theme Handbook: https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 But it will likely be a bit before those are written and published.

In the meantime, it'd be great to introduce them here on the Dev Blog. The Twenty Twenty-Four theme also includes some starter patterns, so it might mean a good chance to show off what the theme is capable of too.

**Starter Page Patterns** are patterns that appear when creating a new page (can also be used for any post type), allowing the user to choose a pattern to start from.

**Starter Template Patterns** are patterns that are available when a user creates a new template of that type in the Site Editor.

It's possible that we could even split this into two separate tutorials.</div>

**Comment by justintadlock** [comment]
Working on this one here: https://docs.google.com/document/d/1RnXXIh6F_P9HDUbgM1eHn6iEOzyC45ou6uPxBZHD0_A/edit?usp=sharing

**Comment by justintadlock** [comment]
This one is drafted and ready for reviews: https://docs.google.com/document/d/1RnXXIh6F_P9HDUbgM1eHn6iEOzyC45ou6uPxBZHD0_A/edit?usp=sharing

**Comment by marybaum** [comment]
On it!

**Comment by bph** [comment]
I am through with my review and my questions. Great post!

**Comment by marybaum** [comment]
Done!

**Comment by justintadlock** [comment]
Thanks, @bph and @marybaum!!!

**Comment by justintadlock** [comment]
Social copy: 

> Want to know how Twenty Twenty-Four shows a "Choose a pattern" modal when adding a new page? It's actually a built-in WordPress feature that you can use in your themes. Find out how in this tutorial from the Developer Blog:
>
> https://developer.wordpress.org/news/2024/01/31/adding-starter-patterns-to-your-wordpress-themes/

**Comment by bph** [comment]
scheduled on social for 2/29
