### ISSUE TITLE
Introduction/Overview of WordPress Playground

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#198]
**Update:** This topic has been updated to be more of an introduction or general overview of Playground.

---

### Discussed in https://github.com/WordPress/developer-blog-content/discussions/196

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** January  3, 2024</sup>
One of the most painful experiences (at least in my opinion) is managing live demos to showcase your new Wordpress theme to the world. You usually need to set up and maintain a multisite instance for multiple themes. And, it becomes more complex if you want to give potential users access to the admin to actually explore it. It's a headache and management nightmare.

What if you didn't need to do all of that?

That's where WordPress Playground comes in, especially its Blueprints API: https://wordpress.github.io/wordpress-playground/blueprints-api/index

You can easily provide a demo (even multiple demos with their own configurations) by simply providing a blueprint to Playground.

My proposal is to write a guide on using Playground to showcase your theme.

We have some working examples in the current Block Theme Examples repo (click the links in the README to see how this works): https://github.com/WordPress/block-theme-examples</div>

**Comment by ironnysh** [comment]
Excited to start working on this :-)

**Comment by justintadlock** [comment]
@ironnysh - Thanks for taking this on. I'm excited to see what you come up with. Feel free to ask me for any help or anyone from the `#core-dev-blog` Slack channel about getting started.

Here's a list with important links for contributing:

- https://developer.wordpress.org/news/how-to-contribute/
- https://developer.wordpress.org/news/tips-and-guidelines-for-writers/

The biggest thing is to put your draft (when you start it) in a Google Doc that has open comments/suggestions and leave the link to it here. The review process will happen within the doc.

**Comment by ironnysh** [comment]
Awesome, thank you  @justintadlock!
I already have a question 🙂 Is there a recommended/average word count for this type of post, which would probably include code snippets?

**Comment by justintadlock** [comment]
There's no required/recommended word count.

For reference, the average word count of all posts on the Dev Blog from 2023 was ~1,800 words. But, again, this is not something we really look at, so don't think of that as some sort of goal. I only share because I know it helps some folks outline or visualize their plans for a post.

**Comment by ironnysh** [comment]
> it helps some folks outline

Yup, that's why I asked 😄

**Comment by justintadlock** [comment]
Just a quick note that if you run into any issues when using `add_editor_style()` in the example code, we ran into an issue that requires enabling networking for Playground for those styles to load correctly.

Here's how to turn it on: https://github.com/WordPress/block-theme-examples/issues/9#issuecomment-1887453451

**Comment by ironnysh** [comment]
Thanks for the heads-up, @justintadlock.

I had [a little adventure](https://github.com/WordPress/wordpress-playground/issues/927) with the networking feature a few days ago :-)

**Comment by adamziel** [comment]
I’d just make sure the article mentions the [Blueprints v2 proposal](https://github.com/WordPress/blueprints/issues/6). It would be a really nice progression to have – here’s the existing API, here’s what it can do, go and play with it, and if you’ll struggle to do anything we are designing the next version right now and would _really_ want to hear from you and shape it together.

**Comment by adamziel** [comment]
Also, I wanted to surface [this Blueprint examples wiki page](https://github.com/WordPress/wordpress-playground/wiki/Blueprint-examples#load-php-code-on-every-request-mu-plugin) created by @bgrgicak

**Comment by bgrgicak** [comment]
> Also, I wanted to surface [this Blueprint examples wiki page](https://github.com/WordPress/wordpress-playground/wiki/Blueprint-examples#load-php-code-on-every-request-mu-plugin) created by @bgrgicak

I'm not happy with the format, but it's simple to add blueprints. Longterm we should invest some time in making it look better.

**Comment by ironnysh** [comment]
Thanks for the links, @adamziel!

@bgrgicak, is this wiki page meant to be used to showcase "community recipes"? I'm asking because I found a few more similar pages across the project, and it might be easier to consolidate them instead of maintaining another source.
 
- There's the [examples](https://wordpress.github.io/wordpress-playground/blueprints-api/examples) page on the official docs
- A [standalone demos page](https://playground.wordpress.net/demos/)
- And a few more [apps/demos here](https://wordpress.github.io/wordpress-playground/links-and-resources/#apps-built-with-wordpress-playground).

**Comment by adamziel** [comment]
@ironnysh these examples are all over the place right now. I'd love to consolidate them. The wiki page is there because we've noticed the friction involved in adding new doc pages using Pull Requests prevents us from opportunistic actions like "this Blueprint I've built is cool, let's quickly share it somewhere". Ideally, publishing those would be easy and  encourage contributions. The upcoming [Blueprints community space](https://github.com/WordPress/blueprints/issues/54) could be an opportunity to tie it all together.

**Comment by ironnysh** [comment]
Right, got it. The community space sounds like a perfect fit, but I guess it'll take a while to build and launch. I was hoping to have a single source I can link to from the post 😀

Oh, and off-topic: I found [this demo a few days ago](https://wpcodebox.com/playground)

**Comment by ironnysh** [comment]
BTW, if it helps, I'd be happy to open a quick PR:
- Adding the recipes from the WIki to [examples](https://wordpress.github.io/wordpress-playground/blueprints-api/examples).
- Copying the [demos from the standalone page](https://playground.wordpress.net/demos/) to the [apps/demos page](https://wordpress.github.io/wordpress-playground/links-and-resources/#apps-built-with-wordpress-playground).

**Comment by adamziel** [comment]
> The community space sounds like a perfect fit, but I guess it'll take a while to build and launch

Actually, v1 might be just a GitHub repository to launch it without months of design of development. I'm exploring one [here](https://github.com/adamziel/blueprints) and developer materials are the largest blocker there.

> Oh, and off-topic: I found [this demo a few days ago](https://wpcodebox.com/playground)

This is lovely, thank you so much for sharing!

> BTW, if it helps, I'd be happy to open a quick PR:

Yes please! Thank you!

**Comment by ironnysh** [comment]
PR ready [here](https://github.com/WordPress/wordpress-playground/pull/1107) :-)

**Comment by ironnysh** [comment]
Draft ready for review: https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit

**Comment by justintadlock** [comment]
@ironnysh First, I just want to say thank you for taking on this topic. What you have is written well, but I expected that after having read some of your other work. :)

My biggest concern right now is that the tutorial tries to cover too much ground, which means that it never really dives deeply enough and focuses on a specific thing. The goal of this topic was supposed to walk theme authors through creating a theme demo with Playground. And I feel like we've missed that mark. Right now, this is a more general overview of what you can do with Playground.

That does leave me questioning whether we should either:

1. Pursue this as a different topic altogether that's more general usage of Playground or 
2. Try to rework the current draft to cover the proposed topic of walking through creating a theme demo

Before moving forward with reviews, I'd want us to get some clarity around this to make sure we're all on the same page. I'd also like to hear your thoughts about which path you'd prefer.

I believe either option is OK, but if we go with option 1, we should split these topics so that the original isn't closed. It'd still be great to have a step-by-step walkthrough of creating a theme demo.

**Comment by zzap** [comment]
I reviewed the article and wanted to leave the same comment as @justintadlock above (luckily, I read all the comments as well).

My thought is: keep this article as is (just change the title) - it's very informative and easy to follow. I think it's important to have this in our blog. Follow up with shorter article (that needs no explaining what the Playground is because we already have that) with specific usecase - building theme demo (link to previous article for more context).

This way, we could have many followups concentrating on only specific usecases while broader explanations are already covered.

**Comment by ndiego** [comment]
I've been exploring some other interesting applications for blueprints that would be a good (shorter) follow-up to a more general article about Playground.

**Comment by annezazu** [comment]
👋🏼 Chiming in here to support a more general article about playground, along with different use cases in hopes that it might be something the broader dev community can start giving feedback on and using, along with meetup organizers as this could really be game changing. I was about to propose an article on the developer blog around using playground with the following in mind but it seems like this would cover it nicely. 

>“Imagine creating effortless presentations, workshops, demos, and more that will create an interactive learning environment”

**Comment by adamziel** [comment]
This is fantastic and well researched. This article will have a lasting impact – **thank you so, so much** @ironnysh! It's written so well ❤️  Would it be okay to reuse parts of it in developer resources? It would be super helpful especially for onboarding people to Blueprints and the [Blueprints community space](https://github.com/adamziel/blueprints/issues/2#issuecomment-2009673186).

Also, I left some comments inline in places that stood out to me.

**Comment by bph** [comment]
I agree with @zzap, and others. It's a great article. As suggested, we publish this article under "Introduction to Playground - running WordPress without servers" or something like this (wordsmiths step up here!). 

This would be a great post to link to from deeper dive into Playground topics. 

And we open another issue to [cover the topic](https://github.com/WordPress/developer-blog-content/discussions/196) @justintadlock proposed. 

@ironnysh Would that work for you? 

I could open an adhock discussion in the core-dev-blog channel to get wider approval.

**Comment by flexseth** [comment]
Really liking the intro on this one @ironnysh! It reads like a TechCrunch article!

> Have you heard about WordPress Alchemy? It’s a serverless version that runs inside the browser and goes by [WordPress Playground](https://wordpress.org/playground/).
>
> Developed [by Adam Zieliński in 2022](https://wordpress.tv/2023/05/23/developer-hours-wordpress-playground-americas/), this groundbreaking project isn’t alchemy, [it’s WebAssembly (WASM)](https://developer.wordpress.org/news/2023/08/30/exploring-the-future-of-web-development-with-webassembly-and-php/). 
>
> The same technology used to drive browser-based IDEs [is at the core](https://wordpress.github.io/wordpress-playground/architecture/index) of Playground, supporting [Zieliński‘s vision](https://github.com/WordPress/wordpress-playground/issues/472) to empower developers, users, learners, extenders, and contributors.

**Comment by ironnysh** [comment]
Thank you for the kind words and productive comments and suggestions. Can't tell you how much I enjoyed reading through this discussion, and I'm excited to read more use cases!

So yeah, let's split it :-) I rewrote the _JavaScript API_ section and expanded the demo into a [tutorial (Part 2)](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.ozzfilfe7zsb). It's in the same doc, just below the _Extras_.

> open another issue

@bph --That'll be great. I'll create a new doc with the tutorial and link it there.

> Would it be okay to reuse parts of it in developer resources?

@adamziel --(super) Fine by me. @bph & @justintadlock, is it okay?

**Comment by ironnysh** [comment]
@adamziel, I left you two follow-up questions in the doc.

BTW, @flexseth found a bug :-) [see here](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit?disco=AAABHfulkrQ).

**Comment by flexseth** [comment]
> Would it be okay to reuse parts of it in developer resources?

@ironnysh - There is a master tracking issue for the documentation overhaul. 
- https://github.com/WordPress/wordpress-playground/issues/772

Put in some work yesterday and today... consolidating all of the bullet points in this article into (most likely) pages with TOC's. 

The notes basically fall into a couple of categories for docs: 
- end-user docs (HelpHub)
- developer docs (Devhub)
- demo & testing docs
- teaching (for Meetup Organizers, WP Coaches & Trainers)

I will make it a point to get that together today, so everyone can see what correlates, is already written, and so we can discuss a plan for who can pick up work on what. If that works!

pinging @adamziel for visibility to let him know I'm working on the docs consolidation yesterday and today. 

Should have a good working draft up this evening that shows links 
- Bullet point > draft content (already WIP)
- Bullet point > existing content
- Bullet point > draft content (new WIP)

That way there shouldn't be much overlap in what folks are working on!

Screenshot below is how I'm marking the content up internally, stay tuned!

<img width="503" alt="image" src="https://github.com/WordPress/developer-blog-content/assets/3792502/78278ee0-34d4-40d9-86f6-1c46b6573bce">

**Comment by flexseth** [comment]
Somewhat related to this post: I was wondering if there has been any benchmark testing done for the playground? It seems like there's a decent bit that goes on behind the scenes when it loads up, and I'm just thinking if hundreds of people were to go to a single domain at once (ie from the dev blog post to the demo)..

When the post is published it goes out to the Slack, Developer Blog, Subscribers... anyone syndicating automatically from the dev blog... it might be helpful to set up Varnish or some type of load balancing measures before publishing? 

Just a thought. Worked with a popular music site a while back and their site would go down when they hit the front page of the music subreddit, wanting to make sure that experience didn't happen when trying to promote the Playground.  :)

**Comment by justintadlock** [comment]
I've split the two topics based on everyone's feedback. Let's keep this one as the overview/intro to Playground to not lose the discussion. For the theme demo topic, I've split it to #244.

**Comment by ironnysh** [comment]
Thanks, @justintadlock!
> I rewrote the JavaScript API section and expanded the demo into a tutorial ([see Part 2](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.ozzfilfe7zsb)). It's in the same doc, just below the Extras.

Shall I add this to #244?

**Comment by ironnysh** [comment]
@bph, @justintadlock --All comments resolved. The text is ready for the second review.

**Comment by adamziel** [comment]
I left a few more comments but it looks great otherwise – thank you SO MUCH for writing this @ironnysh!

**Comment by ironnysh** [comment]
Great, thanks, @adamziel! One fixed, only one left to resolve :-)

Thank _you_ for creating Playground ;-)

**Comment by bph** [comment]
@ironnysh I did another look at apart from one link, and one correction. With all the comment I wasn't clear if you started a new document or if the one I already review was still the one you were working on. 
 [I went to this document](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.bptlfgge3o) and read to [the bookmark](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#bookmark=id.l1pg37gbmjhr) which seemed to be the natural end of an Overview post. 
Please ping me, if you need me to go some place else for the second review. 

Also I added you as an author to the Dev Blog '
`Invitation email sent to user. A confirmation link must be clicked for them to be added to your site." 

Once you are ready to post to the blog, please let me know and I'll share our checklist with you.

**Comment by ironnysh** [comment]
Hi @bph, great, thank you!

Yes, this is the same doc you reviewed before—I rewrote the closing paragraph and moved the whole demo to Part 2.
- [Part 1: The Overview](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.goe272ejjxxu) ends where you added [the bookmark](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#bookmark=id.l1pg37gbmjhr).
- [Part 2: The tutorial](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.ozzfilfe7zsb). Still needs a second review, I guess.

Two questions:
1. Would it be possible to display [the `<iframe>` here](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#bookmark=id.3y5owbfpu5h) as a Playground Block?
2. What's the best way to include [the extras](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit#heading=h.ortt4xb7x81x)? Is there an `<aside>` block I can use?

**Comment by bph** [comment]
As mentioned [in the comment](https://docs.google.com/document/d/135Y73OQE8qo60pBE6gAc4QIxNvpJ5MNynDg1-HgdHtI/edit?disco=AAABKEQ-WaI) The iframe won't work on the Dev Blog. I tested it last month. Nothing has changed since then. There are security implications, that strip out the iframe. But that's ok, if you want to show off the plugin you can create a blueprint and create a link button in the blog post. 

Extras: If you take the Extra line out, and  move both the paragraph about the plugin and the site building into your post before the "Playground in the field" paragraph above the "Stay tuned". They are both in the realm of the JavaScript API and still in testing...

**Comment by bph** [comment]
Hi @ironnysh  I see that you are already posting your article to the Dev Blog. Please "Enable Public Preview" and share the link in a comment here. so the review for the second review can do it on the blog post. 

![Image](https://github.com/WordPress/developer-blog-content/assets/39980/de0f6824-c3c1-4ed7-83e7-2d2ffe2bff06)

**Comment by bph** [comment]
For your reference.... 

### Pre-publishing checklist: (updated 1/29/2024)

- [ ] Post Title and subheaders in sentence case
- [ ] Are Category or Categories selected?
- [ ] Are Tags identifies?
- [ ] Is there an explicit Excerpt?
- [ ] Are all images files uploaded to the media library
- [ ] Do all images have an alt-text?
- [ ] For TOC us the Pattern under _Developer Blog > Table of contents_
- [ ] Assign or upload a featured image
- [ ] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [ ] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post.

**Comment by ironnysh** [comment]
@bph, all done. Here's the link to the preview: https://developer.wordpress.org/news/?p=3309&preview=1&_ppp=6161ec285a.

**Comment by flexseth** [comment]
> @bph, all done. Here's the link to the preview: https://developer.wordpress.org/news/?p=3309&preview=1&_ppp=6161ec285a.

Sorry for just getting to this @ironnysh, but I made a comment in the Google Doc draft about using the `kitchen-sink` and how it's important for editing media... dunno if it's too late to get in. Limitation I just stumbled upon

**Comment by ironnysh** [comment]
Thanks, @flexseth, I added it to the post

**Comment by ironnysh** [comment]
**Social copy:** 

>No setup, no download—WordPress Playground lets you spin a website in a few seconds. Here's everything you need to know to get started

**Comment by justintadlock** [comment]
Working on the second review right now...

**Comment by justintadlock** [comment]
@ironnysh - I left a few minor comments in the Google Doc, but everything looks good to me. Really great writing!

**Comment by ironnysh** [comment]
Thanks, @justintadlock! :-)
Fixed 'em all (in the doc and the post).

**Comment by ironnysh** [comment]
@bph, are there guidelines for the featured image? I uploaded a file, but wanted to double-check (dimensions, file size, format, etc.).

**Comment by bph** [comment]
@ironnysh Handling of the featured image has been quite fluid in the last couple of months. 

I create mine via Google Slides and you can [see my examples there.](https://docs.google.com/presentation/d/1vFbR8utQi0x3HDSX1L5QD1N05gM2tTF_7sOEmjd0c2g/edit#slide=id.p). If it helps, feel free to make a copy. 


The purpose of the featured image is for visual support on sharing on the Social webs. 
Examples:  [on X](https://twitter.com/WordPress/status/1767990520200978494) or [also on X](https://twitter.com/WordPress/status/1765395164502085824) 

- dimensions: 1050 x 600
- background: Black
- Text: Title of the post in white (optional)
- Screenshot or code view as visual anchor. 
- Filesize: the smaller the better, use your image compression settings generously... 

These are just my personal choices.  We haven't settled on a standard format yet.

**Comment by ironnysh** [comment]
Perfect :-)

**Comment by bph** [comment]
@ironnysh Seems we are really close to publishing your article! 🙌🏻 

As this is your first article on the developer blog, I'll share the checklist with you: 
### Pre-publishing checklist: (updated 1/29/2024)

- [ ] Post Title and subheaders in sentence case
- [ ] Are Category or Categories selected?
- [ ] Are Tags identifies?
- [ ] Is there an explicit Excerpt?
- [ ] Are all images files uploaded to the media library
- [ ] Do all images have an alt-text?
- [ ] For TOC us the Pattern under _Developer Blog > Table of contents_
- [ ] Assign or upload a featured image
- [ ] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [ ] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post. 

Please notify me when you are through the pre-publish list or if you have questions. I'll double-check and will publish the article..

**Comment by ironnysh** [comment]
@bph, all done 🥳

The post is here: https://developer.wordpress.org/news/?p=3309&preview=1&_ppp=6161ec285a

> ### Pre-publishing checklist: (updated 1/29/2024)
> * [x] Post Title and subheaders in sentence case
> * [x] Are Category or Categories selected?
> * [x] Are Tags identifies?
> * [x] Is there an explicit Excerpt?
> * [x] Are all images files uploaded to the media library
> * [x] Do all images have an alt-text?
> * [x] For TOC us the Pattern under _Developer Blog > Table of contents_
> * [x] Assign or upload a featured image
> * [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
> * [x] Add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))

**Social copy:**

> No setup, no download—WordPress Playground lets you spin a website in a few seconds. Here's everything you need to know to get started

**Comment by adamziel** [comment]
@ironnysh one last note, I recently made the kitchen sink bundle the default to reduce general confusion around the PHP extensions:

https://github.com/WordPress/wordpress-playground/pull/1191

It's not a blocker for anything here, but I just wanted to note it.

**Comment by bph** [comment]
Good morning @ironnysh I made a few more modifications: 

 "A new post: https://playground.wordpress.net/?theme=blue-note&url=/?page_id=2"
 -> Opens the Sample Page though.
 This is the URL to open a new post `https://playground.wordpress.net/?theme=blue-note&url=/wp-admin/post-new.php` 
✅ fixed it. 

There is still an external link, that needs to be removed: 
(If you prefer a more modular solution, [try Antonio Sejas’ elegant plugin](https://github.com/sejas/playground-plugin-admin-notice)). 
❌ removed it. 

What's your reasoning for those examples URL not made as links? 
✅ Added links. 

Changed the background color for your code details to a less alarming light blue 
![Screenshot 2024-04-05 at 12 06 23](https://github.com/WordPress/developer-blog-content/assets/39980/887664f3-e065-4a8c-86ef-475ab3fd6e92)
✅ changed. 

The post feels a bit devoid of visuals. Screenshots would help visualize the UI: 

## Examples

I love the "trippy, M. C. Escher-like way of running WordPress inside WordPress. " image :-) This would be the screenshot for it. 
![Screenshot 2024-04-05 at 11 44 11](https://github.com/WordPress/developer-blog-content/assets/39980/2f9a4bc6-ee00-4311-9674-598f5de2562e)
✅ Added the screenshot. 

I am unsure about the other two examples. It might make your article feel like it needs to cover the other options/ settings as well. Just wanted to discuss this a bit. Maybe it just reveals a gap in the documentation we need to close. 

**This is the **Additional Actions** Menu**
![Screenshot 2024-04-05 at 11 12 33](https://github.com/WordPress/developer-blog-content/assets/39980/addd78e1-75d4-415b-9601-5dc1d942a0da)

**The Settings screen**
![Screenshot 2024-04-05 at 11 12 26](https://github.com/WordPress/developer-blog-content/assets/39980/b50858d5-f41e-45cd-a2b7-15fe1af120c2)

**Comment by ironnysh** [comment]
That's great news, @adamziel -- Thanks for letting me know :-) I updated the post.

@bph, you're the best, THANK you! :-)

- **Visuals:** I actually took [a few screenshots](https://drive.google.com/drive/folders/1ryeJfUAFIAWc27HNQ8kW1qpxQJN0HxXC) while writing, but with all the code snippets and notice boxes, I felt that adding images might make the post even "busier" and interrupt the reading flow.

- **The Settings UI:** the logical place for that would be under [Build a site...](https://developer.wordpress.org/news/2024/04/05/introduction-to-playground-running-wordpress-in-the-browser/#build-a-site-and-share-it), but since everything changes so fast (my screenshots are already outdated 🤣), I thought I'd leave it for people to explore on their own.

What do you think? I can quickly add an explanation and the 2-photos gallery if you think it's important.

**Comment by bph** [comment]
@ironnysh The **Build a site** part is really the mind-blowing 🤯  and seeing the **Additional actions** menu might make it more 'tangible' if you know what I mean. Go ahead if you want to add it. 

And if you would like to add other screenshots, just remember to add alt-text, too.

**Comment by ironnysh** [comment]
@bph, I ended up rewriting [this whole section](https://developer.wordpress.org/news/2024/04/05/introduction-to-playground-running-wordpress-in-the-browser/#build-a-site-and-share-it) :-) What say you?

> remember to add alt-text

Always!

**Comment by ironnysh** [comment]
@bph, I can't close this issue or the accompanying discussion (#196) 

### Post-publishing checklist
> * [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles)
> * [ ]  close the issue with a comment to link to the published post
> * [ ]  close the accompanying discussion with the link to the published post.

The post was published here: [Introduction to Playground: running WordPress in the browser](https://developer.wordpress.org/news/2024/04/05/introduction-to-playground-running-wordpress-in-the-browser/)

**Comment by bph** [comment]
Thanks @ironnysh - Ah right. It's the same issue why you can check the checkboxes in my comments. Not enough privileges. Need to look into it.

**Comment by bph** [comment]
Social post schedule for April 24.
