### ISSUE TITLE
Developer content on Learn WordPress

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/developer-blog-content#2]
A wrap-up of all the developer-focused content either published on Learn WordPress or hosted as Learn WordPress Online Workshops, for the month of August.

**Comment by bph** [comment]
Good point. Thanks, @jonathanbossenger - Given that the Learn.WordPress site has its online place, an updated list of new WordPress.tv videos for developer is probably the best content for the developer blog. 

My experience with Gutenberg Times taught me is that the list of upcoming events is not conducive to publication. The scheduling is sporadic and short-term.  A post would be outdated the week it was published. A link to the schedule is most likely all that could be done for the ongoing workshops on meetup.com

**Comment by bph** [comment]
At our last meeting, we discussed the idea of monthly hand-curated round-up post: 

- Learn.WordPress - new course, new workshops
- Developer relevant PRs merged into Core > Backend
- Developer relevant PRs merged into Core > Frontend (Gutenberg plugin)
- Updates for Feature Plugins. 
- Recent uploads of developer oriented talks on WordPress TV (by learn, or by Wordcamps, or Meetups)

**Comment by bph** [comment]
I am closing this issues as we cover Learn.WordPress resources in the monthly round-up posts.
The first one was published on Feb 10th:  [What’s new for developers? (February 2023)](https://developer.wordpress.org/news/2023/02/whats-new-for-developers-february-2023/)
