### ISSUE TITLE
What's new for developers? (February 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#207]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1dHUKWDTZstOG7KR3uxWJejN5eUmWm0LdVvL-m4Gvi6s/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by adamziel** [comment]
Some editing may be required but here's the first draft of what's new in WordPress Playground:

---

## Live previews

* Theme reviewers now [have a “Live preview” link](https://href.li/?https://meta.trac.wordpress.org/ticket/7382#comment:10) for new theme submissions. 🎉
* Plugin reviewers now [have a “Live preview” link](https://href.li/?https://meta.trac.wordpress.org/ticket/7380) for new plugin submissions thanks to amazing work by [@tellyworth](https://playgroundp2.wordpress.com/mentions/tellyworth/).
* All WordPress core PRs now [get a “Live preview” link](https://href.li/?https://core.trac.wordpress.org/ticket/59416) to ease the testing (like [this one here](https://href.li/?https://github.com/WordPress/wordpress-develop/pull/5776)).

## Playground now supports multisites

Go to https://playground.wordpress.net?multisite=yes to enjoy the magic:

![CleanShot 2024-01-29 at 12 34 04@2x](https://github.com/WordPress/developer-blog-content/assets/205419/006f8b7c-da23-4179-80ac-7df6fbd187b7)

If you the [Blueprint API](https://wordpress.github.io/wordpress-playground/blueprints-api/index), you can lean on the `enableMultisite` Blueprint step:

```json
{ "steps": [ { "step": "enableMultisite" } ] }
```

## wp-cli is now supported in the CLI and in the browser

`wp-cli` now works with the WASM PHP provided by the `@php-wasm/cli` npm package.

You can try it out with the following command:

```
npx @php-wasm/cli wp-cli.phar user list
```

![CleanShot 2024-01-18 at 14 55 13@2x (2)](https://github.com/WordPress/developer-blog-content/assets/205419/46f3f0da-9a57-4d36-b313-12e7a02f2fcf)

Furthermore, you can also use wp-cli directly in the browser – see the [live demo](https://playground.wordpress.net/demos/wp-cli.html).

https://github.com/WordPress/developer-blog-content/assets/205419/0ed60752-d481-41a6-a2bd-e38216641e16

The popular commands seem to work, although many limitations are yet to be discovered. Please report any issues at https://github.com/WordPress/wordpress-playground/issues

## Playground Block.

The new [Playground Block](https://wordpress.org/plugins/interactive-code-block/) brings Playground into the WordPress editor. 
It supports:

- Embedding Playground with a custom Blueprint
- Setting WP_DEBUG and WP_SCRIPT_DEBUG constants
- Navigating to a specific URL
- Code editor – the files become an auto-installed plugin
- Exposing PHP errors via an error_log file

https://github.com/WordPress/playground-tools/assets/205419/5f0b794b-866a-4587-acfe-939e690de625

Work is underway to use that block for interactive tutorials on learn.wordpress.org.

## Other highlights

WordPress Playground now supports [PHP 8.3](https://href.li/?https://github.com/WordPress/wordpress-playground/pull/829) and [mbregex](https://href.li/?https://github.com/WordPress/wordpress-playground/pull/884) and [OpenSSL](https://href.li/?https://github.com/WordPress/wordpress-playground/pull/883/files#top) PHP extensions.

**Comment by adamziel** [comment]
@bph @justintadlock can we also ping @bgrgicak in these posts?

**Comment by bph** [comment]
Certainly! Added @bgrgicak to the notifier. Notification starts for the March edition. 
<Waving at @bgrgicak/>

**Comment by justintadlock** [comment]
This one is ready for review now: https://docs.google.com/document/d/1dHUKWDTZstOG7KR3uxWJejN5eUmWm0LdVvL-m4Gvi6s/edit?usp=sharing

Just a heads up that this is expected to be published on Saturday, Feb. 10.

**Comment by justintadlock** [comment]
Props to @ndiego for the first review.

**Comment by rmartinezduque** [comment]
Looks great to me, Justin! I just left some minor comments and suggestions for consideration. Feel free to accept or reject as you see fit.

**Comment by justintadlock** [comment]
Props to @rmartinezduque for the second review.

I'll get this moved over to the Dev Blog tomorrow and ready to publish early on Saturday.

**Comment by justintadlock** [comment]
**Social copy:**

> WordPress 6.5 is shaping up to be an exciting release for developers. Check out all the feature updates and changes from the past month on the Developer Blog:
> 
> https://developer.wordpress.org/news/2024/02/10/whats-new-for-developers-february-2024/

**Comment by bph** [comment]
Shared with Marketing team for [This month in WordPress February](https://github.com/WordPress/Marketing-Team/issues/364) edition
