### ISSUE TITLE
When to use Transients API and how

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#213]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **bph** December  4, 2022</sup>
Thank you @Milana for suggesting this topic. 
When you have a minute, maybe you can elaborate a bit on what this blog could cover. </div>

**Comment by ryanwelcher** [comment]
I have started my [draft here](https://docs.google.com/document/d/1Qju0NTZGVc5ESqrZi_h39PPu4dCLvIiwy3vGuRTVNyg/edit#heading=h.ndkcswff4cr). It's not ready for review yet but I wanted to get it added here for reference

**Comment by ryanwelcher** [comment]
Draft is ready for first review - https://docs.google.com/document/d/1Qju0NTZGVc5ESqrZi_h39PPu4dCLvIiwy3vGuRTVNyg/edit#heading=h.7mmnqqs4uize

@zzap I'd love your input on this. Especially any good use-cases that can be added.

**Comment by justintadlock** [comment]
I'm working on the first review.

**Comment by justintadlock** [comment]
Great job, @ryanwelcher! I'm finished with the first review.

**Comment by zzap** [comment]
@ryanwelcher thank you so much for working on this article. Great job and very informative. 

>@zzap I'd love your input on this. Especially any good use-cases that can be added.

I think you have great examples. Another good one could be saving third-party API response. 

Another thing I would add, because I hear many developers mixing these two, is the main difference between caching and transients: storage (object, page, browser vs database and memory if caching is enabled), persistence etc

**Comment by ryanwelcher** [comment]
> Another good one could be saving third-party API response.

Fantastic example, I'll get that added.

> Another thing I would add, because I hear many developers mixing these two, is the main difference between caching and transients: storage (object, page, browser vs database and memory if caching is enabled), persistence etc

Great callout. I need to update the intro and this might be a good fit there.

**Comment by ryanwelcher** [comment]
Second draft is complete and ready for second review  - https://docs.google.com/document/d/1Qju0NTZGVc5ESqrZi_h39PPu4dCLvIiwy3vGuRTVNyg/edit

**Comment by justintadlock** [comment]
@ryanwelcher - Here are the checklists before and after publishing:

### Pre-publishing checklist:

* [x] Post Title and subheaders in sentence case
* [x] Are Category or Categories selected?
* [x] Are Tags added?
* [x] Is there an explicit Excerpt?
* [x] Are all images files uploaded to the media library
* [x] Do all images have an alt-text?
* [x] If using a Table of Contents, use the Pattern under _Developer Blog > Table of contents_
* [x] Assign or upload a featured image
* [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
 * [x] Add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))

### Post-publishing checklist

- [x] Add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles)
- [x] Close the issue with a comment to link to the published post
- [x] Close the accompanying discussion with the link to the published post.

**Comment by ryanwelcher** [comment]
Public preview is available [here](https://developer.wordpress.org/news/?p=3732&preview=1&_ppp=f6f2157c98). Planning on publishing tomorrow morning.

**Comment by ryanwelcher** [comment]
Social Copy:

> The Transient API is a powerful tool for WordPress developers looking to speed up their sites. Explore how to use them here:

https://developer.wordpress.org/news/2024/06/11/an-introduction-to-the-transients-api/

**Comment by ryanwelcher** [comment]
The article has been published - https://developer.wordpress.org/news/2024/06/11/an-introduction-to-the-transients-api/

**Comment by StevenDufresne** [comment]
Love the article!

Very minor; there are a couple of indentation issues in the code samples.

## Screenshots

<img width="690" alt="Screenshot 2024-06-12 at 8 55 46 AM" src="https://github.com/WordPress/developer-blog-content/assets/1657336/23d5a867-231c-421c-bfd1-0e36e5ca0e72">
<img width="722" alt="Screenshot 2024-06-12 at 8 53 05 AM" src="https://github.com/WordPress/developer-blog-content/assets/1657336/a0f8fca0-0502-4b9d-ab96-4d95f62ad69a">

**Comment by ryanwelcher** [comment]
Thank @StevenDufresne! 

I've fixed that, the formatting was a little odd from as I had it in a Google doc. Moving foward, I'll paste it into an IDE then to the article
