### ISSUE TITLE
Overview of "block theme" stuff you can do with classic/hybrid themes

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#218]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/202

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** January 10, 2024</sup>
Currently, there is a not a good resource that outlines exactly what "block" features you can use within classic themes. For example, you can use `theme.json`, various `add_theme_support()` opt-ins, block-based template parts, and more.

The proposal is to give an overview of the essential pieces of creating a hybrid theme (i.e., a classic theme that opts into various block features).

This is a middle ground between classic and block that we haven't really embraced much, but it is still a common use case for agencies and developers who still need to use classic things for their projects.</div>

**Comment by bph** [comment]
Hi @troychaplin Thank you for stepping up to the place and take the lead on this topic. 👏

**Comment by troychaplin** [comment]
Apologies for the delay, I'm finally ready to dive into this one. I am putting together notes relating to the article to make sure I capture all the talking points, @justintadlock would you be open to reviewing those notes and providing some feedback before I get started on writing the full article?

**Comment by troychaplin** [comment]
My notes for this article are here: https://docs.google.com/document/d/1zkae6wtTH6lsRQ8EQu11RTHmRMx4cL4npfXlQAij8yY/edit?tab=t.0#heading=h.vbpi1qm90sw7

**Comment by bph** [comment]
Hi @troychaplin Would you mind open up the Google Doc for anyone with a link to comment. It'll be easier to provide feedback.

**Comment by troychaplin** [comment]
> Hi [@troychaplin](https://github.com/troychaplin) Would you mind open up the Google Doc for anyone with a link to comment. It'll be easier to provide feedback.

Oh so sorry, I did do that and forgot to reply back.

**Comment by troychaplin** [comment]
First draft of this article is ready for review -- https://docs.google.com/document/d/1-E2xj8_2YBn202UBkrDZzUpng4JVYqO9p0tZ-h99rac/edit?tab=t.0

Just before the conclusion I have some notes for a couple of sections I originally thought I would write but they don't seem to fit anymore and I'm looking for some feedback on whether or not I should pursue them as section, wrap them into one "Other Features" type of section, or just drop them all together.

I reached out to @ndiego about doing a review and providing some feedback based on his knowledge and experience with themes and block related functionality.

**Comment by ndiego** [comment]
I have started the first review, but have some structural questions about the Hybrid themes section, [this note in particular](https://docs.google.com/document/d/1-E2xj8_2YBn202UBkrDZzUpng4JVYqO9p0tZ-h99rac/edit?disco=AAABY923mYw).

Right now, this section does highlight "block theme" stuff you can do with classic/hybrid themes, but it's not exhaustive, and I don't want you to have to rewrite theme documentation on the functionality that is the same across all theme types. 

Perhaps all the functionality that is the same in both block and classic themes could be simplified, and greater emphasis should be placed on the differences. This is also an opportunity to explain why someone might choose a hybrid theme approach instead of sticking to a purely classic or purely block theme.

This is just one opinion, though. I would love to hear your thoughts, @justintadlock, especially since you opened the original discussion issue.

**Comment by troychaplin** [comment]
Thanks for the review @ndiego, I have made most of the changes. Have left a a couple bigger items that require a bit more time. And to also wait for some input from @justintadlock as well.

As far as the approach, I'm happy to rework to focus on just the differences. When I read the original discussion I understood the concept as being block theme features that can be used in a classic theme.

At the end of the day, I'm happy to take whichever approach you all prefer, I'm just thankful to have gotten to write this in the way I did, as I didn't know a lot about most of this stuff before and I am taking a lot of new knowledge that I'm excited to expand upon further. I wish I knew a lot of it a year ago when I created a hybrid theme for an enterprise system as I would have made several different decisions. Now I have a decent list of updates to make there, and I am grateful

**Comment by bph** [comment]
@troychaplin I just made a few suggestions regarding guidelines etc. I am deferring to @justintadlock for more feedback and technical review. I agree, that having the list of things that are possible with classic themes, would make this article a one-stop-shop and covering in principle of styles variations, block variations, would be helpful for theme developers trying to transition.

**Comment by troychaplin** [comment]
Thank you @bph, as always your feedback is much appreciated!

**Comment by troychaplin** [comment]
Just a quick followup, had to step away for other stuff for a few days, aiming to jump back to this one in the next few days. @justintadlock  / @bph is this one ok to move into the Done w/1st Review column?

**Comment by justintadlock** [comment]
@troychaplin - I updated the review status. Yes, one of us should've changed that earlier.

I'll have some time later today and tomorrow if you need any help. I'll also be available Monday and Tuesday of next week. Beyond that, I'll be out for a couple of weeks.

**Comment by troychaplin** [comment]
Thanks @justintadlock, if that's the case I'll try and get to it a bit earlier and hopefully you'll have time to complete a second review

**Comment by troychaplin** [comment]
@justintadlock I have finished all my revisions and have move this issue to "Needs 2nd Review"

**Comment by justintadlock** [comment]
This looks solid. Great work, @troychaplin! I added a few minor suggestions in the doc.

The only other suggestion I'd have is to throw in a few screenshots when possible. It just breaks up some of the text a bit more.

---

I think you already know the drill for publishing, but here's the pre and post checklists:

### Pre-publishing checklist:

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC use the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] Add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
- [x] Publish!

### Post-publishing checklist

- [x] Add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] Close the issue with a comment to link to the published post
- [x] Close the accompanying discussion with the link to the published post.

**Comment by troychaplin** [comment]
Thanks for all the feedback and encouragement @justintadlock, much appreciated. I've just made all the changes you have suggested and will get some screenshots ready for the final article while I go through and setup the accompanying repo!

**Comment by troychaplin** [comment]
For social post

Explore how to bridge the gap between classic WordPress themes and modern block features and start using block-based functionality while maintaining the flexibility of traditional PHP theme development:

https://developer.wordpress.org/news/?p=4748&preview=1&_ppp=6aa53dd2ee --> **to be updated once published**

**Comment by troychaplin** [comment]
@justintadlock, @ndiego, @bph the final draft is ready for review before publishing -- https://developer.wordpress.org/news/?p=4748&preview=1&_ppp=6aa53dd2ee

**Comment by troychaplin** [comment]
Article has been published https://developer.wordpress.org/news/2024/12/03/bridging-the-gap-hybrid-themes/

**Comment by bph** [comment]
Social posts scheduled for 12/13
