### ISSUE TITLE
What's new for developers? (March 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#220]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1c5rZfU66rg7VwwIv_ugWKjEVf145--7Z_iE3GbNgdhA/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Primary writer:**

@ndiego is taking on the writing responsibilities for this edition. 🎉  We'll be with him along the way to help gather notes and offer feedback.

**Comment by justintadlock** [comment]
Just a note that Gutenberg 17.7 RC1 will be the first Gutenberg release to follow (it wasn't included in February): https://github.com/WordPress/gutenberg/releases/tag/v17.7.0-rc.1

**Comment by bph** [comment]
Notes for additional formatting of the final version: 

- [ ] Make it a sticky post so it appears in the top spot of the Developer Blog
- [ ] Add a Table of Contents group padding 2, background: Blueberry 4

I leave that here for now. We probably need a separate Documentation page for the What's new for Developers round-up post.

**Comment by ndiego** [comment]
> Add a Table of Contents group padding 2, background: Blueberry 4

@bph just wanted to note that there is now a dedicated pattern for the TOC in the theme.

**Comment by ndiego** [comment]
I'm still working on the imagery, but the first draft is ready for review: https://docs.google.com/document/d/1c5rZfU66rg7VwwIv_ugWKjEVf145--7Z_iE3GbNgdhA/edit

**Comment by adamziel** [comment]
@bgrgicak would you be able to provide a Playground update here based on closed issues and prs in three playground repos?

**Comment by ndiego** [comment]
Yeah if @bgrgicak can provide some highlights, I will get those added. I have added a placeholder for Playground now.

**Comment by ndiego** [comment]
> I'm still working on the imagery, but the first draft is ready for review: https://docs.google.com/document/d/1c5rZfU66rg7VwwIv_ugWKjEVf145--7Z_iE3GbNgdhA/edit

The videos have all been recorded and are linked in the doc.

**Comment by eidolonnight** [comment]
Doc reviewed and suggestions made. 👍🏻

**Comment by justintadlock** [comment]
@ndiego - You're good to go. Just might want to throw the table of contents in there when you move it to the Dev Blog. Good job!

**Comment by ndiego** [comment]
**Social copy**

> Explore the recent updates for developers in Gutenberg and upcoming features in WordPress 6.5.
> 
> https://developer.wordpress.org/news/2024/03/10/whats-new-for-developers-march-2024/

**Comment by ndiego** [comment]
Post is published: https://developer.wordpress.org/news/2024/03/10/whats-new-for-developers-march-2024/
