### ISSUE TITLE
Share change in process for agencies building sites with the site editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/developer-blog-content#229]
This has come up repeatedly over the years with the Site Editor: switching to the Site Editor is both a technical and process change. While we have lots of resources on the technical side, can we do a post featuring the process side too? I think having a few examples of "How we do it" style posts would go a long way to help folks consider switching by showing them _how_ folks have done so.

**Comment by bbertucc** [comment]
Hey @annezazu - I'm happy to get a post up from Decubing. We can schedule the work for next week (Monday). We'll probably focus on one project. Let me know whatever else you need for us to get this up.

**Comment by annezazu** [comment]
That sounds great! @bph any chance you can help guide this? You all are much closer to what format and work is needed to get live on the dev blog.

**Comment by justintadlock** [comment]
I've opened this ticket as a Discussion here: https://github.com/WordPress/developer-blog-content/discussions/230

This is just so that things go through the normal approval process. No need to change this ticket. If/When approved, we'll add the Topic Approved label to this ticket.

**Comment by bph** [comment]
Conversation closed. See https://github.com/WordPress/developer-blog-content/discussions/230#discussioncomment-11392655
