### ISSUE TITLE
Patterns -  tips and tricks for developers

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#235]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **bph** February 20, 2024</sup>
Now that patterns are a massive component of block theme development, and theme developers might want to reuse certain patterns over multiple sites/theme, it would be good to know what tips designers can give who have published a series of block themes. What to think about when you want to create site-agnostic patterns? 

What makes patterns most manageable ( wrap it in  a top-level group block )
How best to use styles? What about colors and typography? 

How to handle content and media assets? 

</div>

**Comment by justintadlock** [comment]
This topic was approved in the March Editorial Group meeting.

@beafialho - If you comment on this ticket, someone from the team can assign it to you.

**Comment by beafialho** [comment]
Thank you, I'm currently working on this

**Comment by beafialho** [comment]
👋 Here's a [draft](https://docs.google.com/document/d/13cTZJWKMquF6MWmsZORzO4PjAp_EEkMOPJLdWLVdPyk/edit) for the post.

**Comment by justintadlock** [comment]
This looks like a pretty good set of practices. I've finished the second review and left my suggestions in the doc.

I did have one other nit-pick about the overall tone of the draft:

The biggest issue for me when reading was that it felt impersonal. It is a very opinionated piece on recommended practices but was detached from the person. The _authority_ here feels like the Dev Blog. But the authority should be you and your experience. I'd love to see you integrate more of yourself and your experience in the intro section. It doesn't have to be over the top. Something simple like this would work:

> Here are the lessons that I've learned working with patterns while building...

Think of the post more as "**My** Best Practices for Patterns" rather than "**The** Best Practices for Patterns." I think you can really capture that with a short paragraph in the intro that lets the reader know where you're coming from.

Hope that helps. Anyway, good work!

**Comment by ironnysh** [comment]
That's a great article, @beafialho. I really like that you're bringing a designer's perspective to the Developer blog

**Comment by bph** [comment]
@beafialho I added your as an author to the WordPress Developer Blog and you should have received an invitation.

**Comment by bph** [comment]
When you are worked through the feedback, you are ready to publish: 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post.

**Comment by beafialho** [comment]
Thanks everyone for your feedback!

> The biggest issue for me when reading was that it felt impersonal. It is a very opinionated piece on recommended practices but was detached from the person. The authority here feels like the Dev Blog. But the authority should be you and your experience. I'd love to see you integrate more of yourself and your experience in the intro section. It doesn't have to be over the top.

@justintadlock great point! I have suggested a different intro paragraph in the Google Doc. If you want to take a look, I am ready of bring it to the editor.

**Comment by justintadlock** [comment]
@beafialho - Looks great!

**Comment by beafialho** [comment]
Thank you! I've created the post (preview [here](https://developer.wordpress.org/news/?p=3057&preview=true&_thumbnail_id=3068)), and have verified all in the pre-publishing checklist.

Here is the copy for social post:

> What makes a well designed pattern? And what ensures that a pattern integrates flawlessly into any WordPress site? A designer shares some of the lessons they've learned while building themes and websites.

**Comment by bph** [comment]
Published it! [Pattern design tips and tricks for developers](https://developer.wordpress.org/news/2024/03/19/pattern-design-tips-and-tricks-for-developers/)

**Comment by abhansnuk** [comment]
Well done @beafialho and hope you will write more pieces like this for the blog.

**Comment by bph** [comment]
@beafialho Can you please double-check on the slide show you used if it's display all the information you wanted it to display. 
 
The editor view has some explanatory text that goes with each slide. 
![Screenshot 2024-03-19 at 17 37 01](https://github.com/WordPress/developer-blog-content/assets/39980/0063c2d2-58c3-4680-945d-55ba2ee04de8)

The text does not display on the frontend. 
![Screenshot 2024-03-19 at 17 36 19](https://github.com/WordPress/developer-blog-content/assets/39980/f1e0296c-1119-4519-a4b4-6dfbee05b4f7)

Do we need to see for a different way to relay the information? Or check in with @ryelle or @renintw if there is a bug in the theme?

**Comment by beafialho** [comment]
> Can you please double-check on the slide show you used if it's display all the information you wanted it to display.

I confirm, it's visible on the editor but not on the front end.

**Comment by bph** [comment]
[Pattern design tips and tricks for developers](https://developer.wordpress.org/news/2024/03/19/pattern-design-tips-and-tricks-for-developers/)
