### ISSUE TITLE
Box Shadow - a sneak peek

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#236]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **bph** February 19, 2024</sup>
Box shadow were available to theme developers since 6.2 

WordPress 6.5 will bring a considerable update including updated UI for content creators. 

This article will explain the new features and how to use them. It also covers what will be next for box shadow support beyond. 

A draft is available in [this Google Doc. ](https://docs.google.com/document/d/1kmpktk4EkSRSxBCK70C1lYWOqjAcvd1N4qvOhKvMthM/edit)

The article will also serve as an update to the previous post on Box Shadow support: [Using the box shadow feature for themes](https://developer.wordpress.org/news/2023/01/12/using-the-box-shadow-feature-for-themes/)
</div>

**Comment by bph** [comment]
- Also https://github.com/WordPress/gutenberg/pull/59358
- https://github.com/WordPress/gutenberg/pull/59616
- https://github.com/WordPress/gutenberg/issues/57103

**Comment by bph** [comment]
I tested the box shadow UI implementation with WordPress 6.5 RC 2, and made some minor adjustments from the earlier version. [It would be ready for review.](https://docs.google.com/document/d/1kmpktk4EkSRSxBCK70C1lYWOqjAcvd1N4qvOhKvMthM/edit) 

It's a short article, less than 600 words. If there are further ideas on what else to cover about the box support, please let me know.

**Comment by bph** [comment]
Earlier today [box shadow for featured image block was merged](https://github.com/WordPress/gutenberg/pull/59616#). I will add a section for that.

**Comment by justintadlock** [comment]
Good job, Birgit! First review is in.

**Comment by ironnysh** [comment]
Cool tutorial, @bph.

**Comment by bph** [comment]
Thanks for taking the time to review 🙏

**Comment by bph** [comment]
### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by bph** [comment]
Public Working on the prepublishing check list
[Public Post Preview](https://developer.wordpress.org/news/?p=3024&preview=1&_ppp=85ccdcc81b)

**Comment by bph** [comment]
Social Copy: 

>  Drop Shadows add another dimention to your images or buttons. With WordPress 6.5 the feature is now available in the block editor. Learn how to set, control and use shadow presets in your theme, blocks and posts.

**Comment by bph** [comment]
Published: [Drop Shadow updates in WordPress 6.5](https://developer.wordpress.org/news/2024/03/21/drop-shadow-updates-in-wordpress-6-5/)
