### ISSUE TITLE
Tutorial on how to create a custom font collection

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#237]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** February 15, 2024</sup>
The Font Library feature in WP 6.5 will include the ability to let plugins/themes register a custom font collection. This would make for a good lightweight tutorial that both showcases the Font Library and shows developers how to extend it. The post just needs to be a walkthrough on "how to do this thing" with code examples and screenshots.

For more information, see: https://github.com/WordPress/gutenberg/issues/57980

If approved, I'm happy to add this to my list of topics, but this might also be a "good first topic" for a new contributor or for anyone who's excited about the Font Library. I'm also good with helping out with code.

CC'ing @matiasbenedetto who worked on this feature and could provide feedback.</div>

**Comment by justintadlock** [comment]
Just noting that I'm happy to pick up this tutorial but didn't want to assign myself yet and leave it open for anyone who wants to take it on. It'd be a nice shorter tutorial for anyone who wants something lightweight.

**Comment by justintadlock** [comment]
I'll go ahead an pick this one up since we didn't have any takers. :) 

Draft will be here: https://docs.google.com/document/d/1Gy5jUGQjvqOCsR_eLCqYfKc6cC_ccl77cAUT4picO-M/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this one is ready to review at any time.

**Comment by bph** [comment]
@justintadlock I reviewed it and only had some minor opinionated correction 😄 
I also tested the code examples and ran into an oddity... See my comment on the Google Doc. 

Other than that, all good

**Comment by ndiego** [comment]
This looks great @justintadlock. I added a few comments to the doc.

**Comment by justintadlock** [comment]
**Social copy:**

> WordPress 6.5 has a new Font Library to let users manage their sites fonts, but you can also create curated font collections via themes and plugins. Learn more on the Developer Blog:
>
> https://developer.wordpress.org/news/2024/04/01/how-to-register-custom-font-collections-for-the-font-library/

**Comment by flexseth** [comment]
> https://docs.google.com/document/d/1Gy5jUGQjvqOCsR_eLCqYfKc6cC_ccl77cAUT4picO-M/edit?usp=sharing

Greetings @justintadlock - under the heading 
## Limitations for themes

Question: Do you think it would be a good idea to include licensing information here? 

For instance
- Using Font Awesome as a Font Library
- Using Adobe Web Fonts
- Using fonts purchased from XXXX font foundry 

All of these could have licensing restrictions that end-users and themers need to know about...

**Comment by justintadlock** [comment]
> Question: Do you think it would be a good idea to include licensing information here?

No, my post is just focused on using the API. It would be up to developers (or their legal representation) to decipher/understand the licensing terms of any particular third-party project they want to use.

**Comment by flexseth** [comment]
> It would be up to developers (or their legal representation) to decipher/understand the licensing terms of any particular third-party project they want to use.

I see, that's the general approach WordPress takes I suppose - "This is not legal advice."  😆

**Comment by marybaum** [comment]
That's actually something that's going to come up in my type post 5 — where to get good type. The new Monotype subscription has some tiers that let us download, and the reality is that while we do prefer people use open-source typefaces, and people can use their own, I have saved a frolicking fortune with that $200/year Monotype subscription. It includes a lot of small foundries along with the very biggest, so it's even curtailed the number of times I have to deal with Adobe's hosted solution (where you still have to write the CSS for Every. Single. Selector. if you want your type to work in Safari and on mobile).

**Comment by bph** [comment]
Social post schedule for April 19
