### ISSUE TITLE
How to use WordPress Playground for handovers

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#247]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **ironnysh** April  3, 2024</sup>
After writing [an overview of what's possible with Playground](https://github.com/WordPress/developer-blog-content/issues/198) for different audiences, I'd like to share a practical example focused on a use case relevant for developers.

The tutorial demonstrates how to work with the JavaScript API to create a [live WordPress website](https://github.com/ironnysh/playground-demo-handover) developers can share with clients. The project includes:
- A modified theme
- A custom plugin, and
- A snippet that generates a new post (complete with the block markup).

The text is already written :-) [See the draft here](https://docs.google.com/document/d/1c31vE7U9eSLfHc9bE1-6E3BTK6bB2s6OhTfLbO_l7zQ/edit?usp=sharing).</div>

**Comment by ironnysh** [comment]
✍🏻

**Comment by ironnysh** [comment]
Welp, the [draft is ready](https://docs.google.com/document/d/1c31vE7U9eSLfHc9bE1-6E3BTK6bB2s6OhTfLbO_l7zQ/edit?usp=sharing) for review 😄

**Comment by bph** [comment]
Good morning, @ironnysh  I did a review of the draft and left some comments. We need to slightly change the approach, though as the linking to the ephemeral Vercel space won't work for the official WordPress blog. I'd be happy to get on a call to see how to approach it slightly differently. I don't think it's huge blocker...

**Comment by bph** [comment]
Now I could envision this:  If you turn it around, following a path of enhanced complexity.
Start with blueprint json steps. That goes through the meat of the matter there, with demo how it works using the ?blueprint-url=blueprint.json.

Then I could see that you discuss advantage to to embed the playground into an index.html, as 

-  do your own styling, 
-  add additional links and 
-  add a Call to actions to the space. 

Then you share the code for that and create a screenshot and of your demo and leave it at that. 
Those who are reading that far would know how to place an index.html and a CSS file into the web and don't need any instructions for that. "It's beyond the scope of this article". (edited)
What do you think?

**Comment by ironnysh** [comment]
Hey @bph, great idea. Thanks for the review and helpful suggestions :-)

I’ll share the revised version here once it’s ready.

**Comment by ironnysh** [comment]
Hi @bph, v2 is ready for review ([same file](https://docs.google.com/document/d/1c31vE7U9eSLfHc9bE1-6E3BTK6bB2s6OhTfLbO_l7zQ/edit))

**Comment by bph** [comment]
Thanks for the ping @ironnysh I'll take a look at it tomorrow.

**Comment by ironnysh** [comment]
Hi @bph, the post is ready for its final-final close up :-)

Public preview is here: https://developer.wordpress.org/news/?p=3531&preview=1&_ppp=3c012555ca

### Pre-publishing checklist: (updated 1/29/2024)
> * [x] Post Title and subheaders in sentence case
> * [x] Are Category or Categories selected?
> * [x] Are Tags identifies?
> * [x] Is there an explicit Excerpt?
> * [x] Are all images files uploaded to the media library
> * [x] Do all images have an alt-text?
> * [x] For TOC us the Pattern under _Developer Blog > Table of contents_
> * [x] Assign or upload a featured image
> * [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
> * [x] Add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))

**Social copy:**

Spin a live site with a custom plugin, a theme adapted to feature it, and a user manual—no server needed

**Comment by bph** [comment]
Published: [How to use WordPress Playground for interactive demos](https://developer.wordpress.org/news/2024/04/25/how-to-use-wordpress-playground-for-interactive-demos/)

**Comment by bph** [comment]
@ironnysh congrats for your second article!

Would you do the honors and post the props on Slack and I will take care of the rest of the Post-publishing checklist
 
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles)
- [x]  close the issue with a comment to link to the published post
- [x]  close the accompanying discussion with the link to the published post.

**Comment by ironnysh** [comment]
Thanks! :-)

- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles)

**Comment by juanmaguitar** [comment]
Social schedule for May 9th
