### ISSUE TITLE
What's new for developers? (May 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#250]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/19GwlMyTxd7ycduo_u3QENGkJU4y5NpNd6u1poq9GVD8/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Comment by adamziel** [comment]
The community Blueprint gallery is close to an official launch. Let's mention it even if we don't get to a more official announcement: https://github.com/WordPress/blueprints

**Comment by ndiego** [comment]
I completed the first review and added a few comments. Looks good!

**Comment by juanmaguitar** [comment]
I've done another review and also added some comments. 
Great job!

**Comment by justintadlock** [comment]
This has now been moved to the Dev Blog as a draft and is ready to go for tomorrow.

**Comment by justintadlock** [comment]
**Social copy:**

> Take an early look at some upcoming WordPress 6.6 features and more in the latest monthly roundup for developers:
>
> https://developer.wordpress.org/news/2024/05/10/whats-new-for-developers-may-2024/
