### ISSUE TITLE
What's new for developers? (June 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#264]
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1I3msotKyqE1ChKJz5Ha45u2Gl9eytL8U671h4uJxArI/edit?usp=sharing

**Resources to track:**

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries
- [Dev Notes](https://make.wordpress.org/core/wp-admin/edit.php?tag=dev-notes-6-2)

**Writer:** @ryanwelcher will be the primary author on this post.

**Comment by justintadlock** [comment]
Some tickets to watch that may include breaking CSS changes for themes (particularly around CSS resets):

- https://github.com/WordPress/gutenberg/issues/57537
- https://github.com/WordPress/gutenberg/pull/57908

**Comment by juanmaguitar** [comment]
@justintadlock @bph Has it been discussed previously sharing the [resources used to curate this content](https://github.com/WordPress/developer-blog-content/issues/264#issue-2293745089) ("Resources to track") in the post itself? I think it could be interesting for developers as a way to help discover how to keep track of changes happening in WordPress.

**Comment by justintadlock** [comment]
I don't see anything necessarily wrong with some sort of resources section, but I would say that I use that list as more as a rough guideline. The only resources that I use 100% of the time are:

- Gutenberg changelog from the repo
- Trac changesets (you have to manually configure this each month)
- Replies to the monthly ticket

I also note things from other sources like Twitter, Facebook, and third-party blogs (none of which we can link to).

**Comment by annezazu** [comment]
Want to flag this PR https://github.com/WordPress/gutenberg/pull/61577 I'm not sure if it'll be ready for June but I think it's the perfect thing to include whenever it lands as it'll need feedback and testing from plugin authors.

**Comment by ryanwelcher** [comment]
> Want to flag this PR [WordPress/gutenberg#61577](https://github.com/WordPress/gutenberg/pull/61577) I'm not sure if it'll be ready for June but I think it's the perfect thing to include whenever it lands as it'll need feedback and testing from plugin authors.

The PR is still in draft but it it gets merge before Monday, we can probably get it added.

**Comment by ryanwelcher** [comment]
This is ready for review

**Comment by justintadlock** [comment]
Moved this to 2nd review since the first was completed.

**Comment by justintadlock** [comment]
Nice work, @ryanwelcher! Second review is done and ready. Once finished, you're ready to publish on the 10th!

**Comment by ryanwelcher** [comment]
Social copy:

> Get caught up on the latest changes for WordPress 6.6 and more in the June edition of the monthly developer roundup:

https://developer.wordpress.org/news/2024/06/10/whats-new-for-developers-june-2024/

**Comment by justintadlock** [comment]
👏  Good work on your first What's new for devs? post, Ryan!

**Comment by colorful-tones** [comment]
Just wanted to note that this phrase feels out of context and out of place.

> Studio by WordPress.com is now available for Windows.

[A conversation](https://poststatus.slack.com/archives/CHNM7Q7T8/p1718157174372119) took place in Post Status Slack. 

I would vote to remove it. I do not think there was ill intent in including it but it is dissparaging for some outside folks.

**Comment by ryanwelcher** [comment]
> I would vote to remove it. I do not think there was ill intent in including it but it is dissparaging for some outside folks.

As per the conversation in Post Status slack, the line has been updated to include (external tool):
> Studio by WordPress.com is now available for Windows (external tool)

**Comment by bph** [comment]
social schedule for 7/23
