### ISSUE TITLE
Using Data Views in your plugin/preparing for the future

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#273]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/232

<div type='discussions-op-text'>

<sup>Originally posted by **annezazu** March  4, 2024</sup>
[With Data Views](https://github.com/WordPress/gutenberg/issues/55083) making its first entry into the WordPress sphere in 6.5 in a fairly contained way, it feels like a good time to start talking about what's to come and ensuring plugin authors can start reusing what's being done in Core to level up their own designs/flows. I think this would make for a good developer blog post perhaps going through what's available in core, how to follow along, and what components are available to use.</div>

**Comment by bph** [comment]
@juanmaguitar with the creation of the issue, only the description came over from the discussion. Please refer to the discussion for additional comment on the topic 

- #232

**Comment by juanmaguitar** [comment]
I'm currently working on this blog post. 
[This project](https://github.com/wordpress-juanmaguitar/devblog-dataview-plugin) is the foundation of the one I plan to explain in the blog post.

**Comment by juanmaguitar** [comment]
I'm working on the draft here:
https://docs.google.com/document/d/1BwsiVbo1T46KYpb0N-dCV0y3REC0_YFKNH3D0yPo8Cs/edit

(still not ready for review)

**Comment by juanmaguitar** [comment]
The draft is ready for a first review:
https://docs.google.com/document/d/1BwsiVbo1T46KYpb0N-dCV0y3REC0_YFKNH3D0yPo8Cs/edit

**Comment by marybaum** [comment]
I'll do a drive-by in a few hours!

**Comment by justintadlock** [comment]
I added quite a few comments but ran out of steam (it's a long one!). There's feedback from @marybaum and @eidolonnight in the doc too, but I'll wait for one of them to wrap up editing before moving to the next step.

Overall, I'm really excited about getting this published on the Dev Blog!

**Comment by justintadlock** [comment]
I did want to point out one thing that was inconsistent throughout the article: When referring to "Data Views," I believe there are two ways you'll want to spell it, depending on the context.

When talking about the feature, I'd refer to it as "Data Views."

When specifically talking about the component (the code), I'd refer to it as `DataViews`.

Data Views, DataViews, Dataviews, and Dataview were all used at different points and in different contexts. It would help to bring consistency to it.

**Comment by marybaum** [comment]
Done! With copious explanations—read or not, as you like.

**Comment by juanmaguitar** [comment]
Thanks, @eidolonnight @marybaum and @justintadlock, for the review and the feedback.
I have done a revision of the article taking all the feedback received into account.
The article is ready for another review:
https://docs.google.com/document/d/1BwsiVbo1T46KYpb0N-dCV0y3REC0_YFKNH3D0yPo8Cs/edit#heading=h.vof9d4754tud

**Comment by juanmaguitar** [comment]
> When talking about the feature, I'd refer to it as "Data Views."
> When specifically talking about the component (the code), I'd refer to it as DataViews.

I have reviewed the code to address this. I think I've changed all references to DataViews (or Data Views) to be consistent but I'll do another check before the article is published.

**Comment by marybaum** [comment]
Looks good! I did just catch one extra comma between a subject and verb, and added a missing full stop at the end of a sentence.

**Comment by bph** [comment]
@juanmaguitar seems you are getting ready to publish your first post on the Developer Blog. I am so excited!

Here are your checklist for this last step :-) 
### Pre-publishing checklist: 

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by juanmaguitar** [comment]
Social copy:

> Learn how to create a React app in the admin UI using a plugin that displays and interacts with data through the DataViews WordPress component.

**Comment by juanmaguitar** [comment]
Post published!
https://developer.wordpress.org/news/2024/08/27/using-data-views-to-display-and-interact-with-data-in-plugins/

**Comment by justintadlock** [comment]
Scheduled for social on September 3.
