### ISSUE TITLE
Curating the Editor Experience: Tips & Tricks

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#276]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/262

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** May  6, 2024</sup>
The title is still TBD, but the idea of this article will be to showcase the many lesser known ways you can curate the Editing experience in WordPress. We already have a few articles on this topic that cover bigger topics like [client-side](https://developer.wordpress.org/news/2023/05/24/curating-the-editor-experience-with-client-side-filters/) and [server-side](https://developer.wordpress.org/news/2023/07/05/how-to-modify-theme-json-data-using-server-side-filters/) filtering, but I think it would be fun to showcase ~10 real-world examples and then directs the reader back to the official documentation and/or other related articles. 

This topic idea corresponds with [ongoing work](https://github.com/WordPress/gutenberg/issues/56170) to improve the [Curating the Editor Experience](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/) section of the Block Editor Handbook. </div>

**Comment by ndiego** [comment]
The first draft is ready for review here: https://docs.google.com/document/d/1TrvgGtfthBMv-3nQgqHjizd370ROTcEVmG4Y9KQWyAE/edit

**Comment by justintadlock** [comment]
Good job, @ndiego. First review finished.

If you want to try a shorter code example for the duotone filter, here's a quick and untested idea. Your code looks OK, though.

```php
function example_enable_duotone_to_media_text_blocks( $args, $block_type ) {
	
	// Only apply the filter to Media & Text blocks.
	if ( 'core/media-text' !== $block_type ) {
		return $args;
	}

	$args['supports'] ??= [];
	$args['supports']['filter'] ??= [];
	$args['supports']['filter']['duotone'] = true;

	$args['selectors'] ??= [];
	$args['selectors']['filter'] ??= [];
	$args['selectors']['filter']['duotone'] = '.wp-block-media-text .wp-block-media-text__media';

	return $args;
}

add_filter( 'register_block_type_args', 'example_enable_duotone_to_media_text_blocks', 10, 2 );
```

**Comment by ndiego** [comment]
> If you want to try a shorter code example for the duotone filter, here's a quick and untested idea. Your code looks OK, though.

Code works great, thanks! Much simpler.

**Comment by bph** [comment]
I am done with the second review and would say it's ready to be published. Fabulous article again @ndiego 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ndiego** [comment]
Post has been published: https://developer.wordpress.org/news/2024/07/04/15-ways-to-curate-the-wordpress-editing-experience/ 

**Social copy:** 

> Customizing the WordPress Editor can enhance your user's editing experience by streamlining content creation and ensuring consistency. Discover 15 curation methods you can use to optimize your site.

**Comment by bph** [comment]
social scheduled for July 26
