### ISSUE TITLE
Color and typography variations/options in WP 6.6

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#282]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** June 11, 2024</sup>
WordPress 6.6 will ship with a new global color and typography variations system. Similar to global style variations, which are placed under a theme's `/styles` folder, these new variations will work on top of the same underlying system. 

However, color and typography variations let themers define specific color schemes and typography sets that users can choose from:

![image](https://github.com/WordPress/developer-blog-content/assets/1816309/daefc48a-c186-49ea-a152-748f4985dcaf)

This recreates a feature that is popular in classic themes that utilize the customizer to give the user pre-built color schemes and typography sets to choose from. Essentially, it lets the user quickly pick their colors and typography at the click of a button without affecting other parts of the overall theme design.

These new "preset" variations can also be used alongside normal global style variations, mixing and matching different designs.

Feature addition:

- https://github.com/WordPress/gutenberg/issues/61215</div>

**Comment by justintadlock** [comment]
I'm working on this here: https://docs.google.com/document/d/15h3thuKpQ6j3yKf2cudoIZ2Iw3a6jNwm_-8e1MGRu9c/edit?usp=sharing

**Comment by justintadlock** [comment]
This one is ready for review! 🎉

**Comment by bph** [comment]
Code tested and almost no comment from me. Done 1st review

**Comment by ironnysh** [comment]
@justintadlock Fantastic work, as usual! 👏
- I left a couple of minor copy suggestions.
- I run into a CSS specificity bug (the funnest!). I added [a comment](https://docs.google.com/document/d/15h3thuKpQ6j3yKf2cudoIZ2Iw3a6jNwm_-8e1MGRu9c/edit?disco=AAABR1BlC24) with a screenshot in the doc.

Other than that, the second review is done.

**Comment by justintadlock** [comment]
Thanks, @bph and @ironnysh!!!

> I run into a CSS specificity bug (the funnest!). I added [a comment](https://docs.google.com/document/d/15h3thuKpQ6j3yKf2cudoIZ2Iw3a6jNwm_-8e1MGRu9c/edit?disco=AAABR1BlC24) with a screenshot in the doc.

That's a block-level style, which should always overrule global styles. It's working as it should.

**Comment by ironnysh** [comment]
Oh! Didn't think about it... so it's a feature ;-)

**Comment by justintadlock** [comment]
**Social copy:**

> Did you know that you can build custom color and typography presets for your theme users in WordPress 6.6? Find out how on the Developer Blog:
>
> https://developer.wordpress.org/news/2024/07/22/mixing-and-matching-styles-colors-and-typography-in-wordpress-6-6/

**Comment by juanmaguitar** [comment]
Social Schedule on Thu, Aug 8, 2024
