### ISSUE TITLE
Actions from Data Views: Adding images to the Media Library

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/developer-blog-content#299]
Part 2 of the post https://github.com/WordPress/developer-blog-content/issues/273 which first part was published at [Using Data Views to display and interact with data in plugins](https://developer.wordpress.org/news/2024/08/27/using-data-views-to-display-and-interact-with-data-in-plugins/)

**Comment by juanmaguitar** [comment]
I'm working on the draft of this article [here](https://docs.google.com/document/d/1EBAC4wLeh-Bhxm4c3n3BRep_4knJRrasR-r2RWquzww/edit) (not ready to review)

**Comment by juanmaguitar** [comment]
[The article](https://docs.google.com/document/d/1EBAC4wLeh-Bhxm4c3n3BRep_4knJRrasR-r2RWquzww/edit) is ready for review. 
I think a better title for the article would be: [Actions from Data Views: Adding images to the Media Library](https://docs.google.com/document/d/1EBAC4wLeh-Bhxm4c3n3BRep_4knJRrasR-r2RWquzww/edit#heading=h.f9g2up7ytnad)

**Comment by zzap** [comment]
I did the first review and left comments and suggestions in the document, but I did not run the code.

Thank you so much, @juanmaguitar, for working on it. I love your info boxes with additional info :heart: 

Another suggestion would be to break all the text and code blocks with a screenshot of the current state. I see one place you planned for but maybe have a couple more (where there's an user-facing change). This is just a suggestion, feel free to ignore it.

@bph first review is completed.

**Comment by juanmaguitar** [comment]
> Another suggestion would be to break all the text and code blocks with a screenshot of the current state. I see one place you planned for but maybe have a couple more (where there's an user-facing change). This is just a suggestion, feel free to ignore it.

I have added a few screenshots to the draft and there will also be a video at the beginning of the post showing how the project will look like with the actions added in the article.

**Comment by justintadlock** [comment]
Good work with this, @juanmaguitar. 🚢 when you're ready.

**Comment by juanmaguitar** [comment]
The post has been published at: https://developer.wordpress.org/news/2024/09/23/actions-from-data-views-adding-images-to-the-media-library/

---

Social copy:

> Explore Data Views actions and what you can do with them, such as interacting with WordPress through the REST API or displaying modal windows.
>
> https://developer.wordpress.org/news/2024/09/23/actions-from-data-views-adding-images-to-the-media-library/

If we wanted to publish a second social post pointing back to Part 1:

> Miss out on Part 1? Check out how to get started with Data Views.
>
> https://developer.wordpress.org/news/2024/08/27/using-data-views-to-display-and-interact-with-data-in-plugins/

**Comment by juanmaguitar** [comment]
### Pre-publishing checklist: 

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by juanmaguitar** [comment]
https://developer.wordpress.org/news/2024/09/23/actions-from-data-views-adding-images-to-the-media-library/
