### ISSUE TITLE
What's new for developers? (October 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#309]
This is a rolling discussion for a monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

**Google Doc:** https://docs.google.com/document/d/1dhpv0ZmyHUrs2FuiWGanU77Q6P50j-lNiS8h8pgOB40/edit?usp=sharing

@ndiego will be the primary author for this post.

**Comment by adamziel** [comment]
These three fantastic guides are worth highlighting:

* [Providing content for your demo with WordPress Playground](https://href.li/?https://wordpress.github.io/wordpress-playground/guides/providing-content-for-your-demo)
* [WordPress Playground for Theme Developers](https://href.li/?https://wordpress.github.io/wordpress-playground/guides/for-theme-developers)
* [WordPress Playground for Plugin Developers](https://href.li/?https://wordpress.github.io/wordpress-playground/guides/for-plugin-developers)

We're also working on a UX overhaul: https://github.com/WordPress/wordpress-playground/pull/1731

It may or may not land in time for the next post. If it does, it's absolutely worth highlighting. CC @annezazu

**Comment by justintadlock** [comment]
Great job, @ndiego!

**Comment by bph** [comment]
## 2nd Review done
Looked at it on public preview and made the following changes: 

- [x] Zoom out and Playground Highlight headlines need to be h3
- [x] Select and Edit to Write and Design. references to UI spaces are to be in bold. 
- [x] Also check the next sentences 
- [x] Same with "Preview dropdown" 
- [x] change giving you the flexibility to allowing you the flexibility 
- [x] In "Template registration API changes" you write "once Gutenberg 19.5 is released" added the date 10/23 to it.

**Comment by bph** [comment]
@ndiego it is ready to ship

### Pre-publishing checklist: 

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ndiego** [comment]
The post has been published here: https://developer.wordpress.org/news/2024/10/10/whats-new-for-developers-october-2024/

Social copy:

> With WordPress 6.7 just around the corner, stay up-to-date on the latest developer news from the past month, including major updates to WordPress Playground.
> 
> https://developer.wordpress.org/news/2024/10/10/whats-new-for-developers-october-2024/

**Comment by ndiego** [comment]
Social post scheduled for 10/14
