### ISSUE TITLE
Broken link in dev blog nav

### ISSUE THREAD

**Issue by troychaplin** [WordPress/developer-blog-content#312]
In the dev blog navigation the Block Development submenu item for Plugins links to a category that doesn't seem to exist -- https://developer.wordpress.org/news/category/block-development/

**Comment by troychaplin** [comment]
Suggestion: give Themes, Plugins and Blocks the same visibility in the main dev blog navigation.

- Plugins would link here: https://developer.wordpress.org/news/category/plugins/
- Blocks would move to the top level and link to here: https://developer.wordpress.org/news/category/blocks/

**Comment by bph** [comment]
Thanks, Troy. We did have a hick-up in our navigation. It should be fixed now... What do you think?

**Comment by troychaplin** [comment]
> Thanks, Troy. We did have a hick-up in our navigation. It should be fixed now... What do you think?

Nicely done! I love the extra categories, gives dev quicker access to some great resources!

**Comment by bph** [comment]
Huge thank you to @ndiego who fixed the navigation for us.
