### ISSUE TITLE
Using the Block Bindings editor API (JS) in WP 6.7

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#317]
WordPress 6.7 exposes a partial set of JS-based editor functions for working with Block Bindings: https://github.com/WordPress/gutenberg/pull/65713

- `registerBlockBindingsSource`: to register a source in the client.
- `unregisterBlockBindingsSource`: to unregister an existing source.
- `getBlockBindingsSource`: to get a specific registered source and its properties.
- `getBlockBindingsSources`: to get all the registered sources in the client.

These are now stable, public functions for theme and plugin authors to extend how Block Bindings work in their projects, especially custom Block Binding sources. I'm proposing a tutorial that walks developers through using these APIs to manipulate bindings in the editor.

There is an additional `getFieldsList` property that will also be public in the Gutenberg plugin only, which could also be a showcase of what's to come in the future.

**Comment by justintadlock** [comment]
The "create ticket from discussion" feature on GitHub seems to broken (at least for me) right now, so I just copied this over from: https://github.com/WordPress/developer-blog-content/discussions/316

**Comment by justintadlock** [comment]
I'm working on this one here: https://docs.google.com/document/d/17o20lmRBxbak8hegX-RmtpKjS2hKlyyc18mbaYR4IWs/edit?usp=sharing

Code examples are up with a rough idea of an outline. Now it's time to fill in all the blank space with words!

**Comment by justintadlock** [comment]
This one's ready for its first review now: https://docs.google.com/document/d/17o20lmRBxbak8hegX-RmtpKjS2hKlyyc18mbaYR4IWs/edit?usp=sharing

**Comment by justintadlock** [comment]
This has received a first review by @cbravobernal, @artemiomorales, and @gziolo. This was primarily a technical review, so the next round should be heavy on copyediting.

**Comment by justintadlock** [comment]
Second review by @ndiego.

**Comment by ndiego** [comment]
> Second review by @ndiego.

Yup! Sorry, I forgot to comment here. Great article, as always.

**Comment by SantosGuillamot** [comment]
I just left some comments there. I think the article is great 👏

**Comment by bph** [comment]
Published: [Getting and setting Block Binding values in the Editor](https://developer.wordpress.org/news/2024/10/29/getting-and-setting-block-binding-values-in-the-editor/)
