### ISSUE TITLE
What’s new for developers? (November 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#321]
This is a rolling discussion for a monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Google Doc: https://docs.google.com/document/d/1SAooDfUIix2Zk6-rt1vkG0pW481Stkdf7OkefI4fiGs/edit?usp=sharing

Current authorship plans: @ndiego will be the primary author with @justintadlock focused on theme stuff.

**Comment by justintadlock** [comment]
Note that I'm trying something new with the Google Doc this time around. Google Docs has recently introduced a new "Tabs" feature, so I split the doc into the main article and the notes sections.

**Comment by ndiego** [comment]
The first draft is available for review: https://docs.google.com/document/d/1SAooDfUIix2Zk6-rt1vkG0pW481Stkdf7OkefI4fiGs/edit?tab=t.0

**Comment by justintadlock** [comment]
Looks good, @ndiego!

**Comment by ryanwelcher** [comment]
@ndiego I just did a pass for the second review. Looks great!

**Comment by ndiego** [comment]
Post published: https://developer.wordpress.org/news/2024/11/10/whats-new-for-developers-november-2024/

**Comment by ndiego** [comment]
**Social copy**

> WordPress 6.7 is here. Catch up on last-minute additions that were included in this release and see what’s coming next for Core, Gutenberg, and WordPress Playground.

**Comment by ryanwelcher** [comment]
Social schedule for Nov 28
