### ISSUE TITLE
How to build light/dark mode with theme.json

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#336]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/331

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** November  5, 2024</sup>
Using `color-scheme` and `light-dark()`, which both have pretty widespread browser support, theme authors can start building color palettes that support the user's OS preferences.

* https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme (Baseline: Widely Available)
* https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark (Baseline: 2024)

This proposal is for a topic that would walk readers through creating color palettes that work with system preferences without ever leaving `theme.json` (well, at least for the front end).

There is one minor thing: the color picker in the editor requires a few lines of code to work.

Here's an example repo of a TT4 child theme of this in action: https://github.com/justintadlock/tt4-dark-mode

**Stretch goal for the tutorial:** There may be a possibility of explaining how to create a light/dark toggle with Block Bindings and the Interactivity API (haven't worked this out yet). This could be a fun addition to the tutorial but is not a hard requirement.

</div>

**Comment by bph** [comment]
[An interesting list](https://wordpress.slack.com/archives/C015GUFFC00/p1733163033313409) of methods in the outreach channel

**Comment by justintadlock** [comment]
Working on this here and expect to have the first draft finished tomorrow: https://docs.google.com/document/d/1GUIICX4H8GDWZ5B2SMqsRwSwaXYFz5ndN1Y0erPS-g8/edit?usp=sharing

**Comment by justintadlock** [comment]
Ready for reviews! 🎉

**Comment by ndiego** [comment]
The first review is complete. Left a few minor suggestions. Great article, learned a lot about the CSS spec for light dark 👌

**Comment by justintadlock** [comment]
> learned a lot about the CSS spec for light dark 

Yep, it's really neat what you can do with just basic, modern CSS for this now. No more complex methods!

**Comment by ryanwelcher** [comment]
Second review is done. No suggestions from me.

**Comment by justintadlock** [comment]
All right. Post is moved to the Dev Blog in draft mode. I plan to publish on Thursday.

**Comment by justintadlock** [comment]
**Social Copy:**

> Learn how to create light and dark mode color schemes for your block themes using theme.json:
>
> https://developer.wordpress.org/news/2024/12/mastering-light-and-dark-mode-styling-in-block-themes/

**Comment by jonathanbossenger** [comment]
Scheduled for social on 18/02
