### ISSUE TITLE
How to disable specific heading levels in the Editor

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#338]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/323

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** October 22, 2024</sup>
This would be a snippet that provides an example of the heading-level curation options available in WordPress 6.7. 

The snippet will show you how to disable H1, H5, and H6 in the Heading block for all users who are not administrators using PHP. 

```php
function example_modify_heading_levels_globally( $args, $block_type ) {

    $is_administrator = current_user_can( 'edit_theme_options' );

    if ( 'core/heading' !== $block_type || $is_administrator ) {
        return $args;
    }

    // Remove H1, H5, and H6.
    $args['attributes']['levelOptions']['default'] = [ 2, 3, 4 ];

    return $args;
}
add_filter( 'register_block_type_args', 'example_modify_heading_levels_globally', 10, 2 );
```</div>

**Comment by ndiego** [comment]
The snippet is ready for a first review here: https://docs.google.com/document/d/1BOuO8eqqMfVae-wBzfItBOr5MMuuO0heY7_kJG07_OM/edit

**Comment by troychaplin** [comment]
@ndiego I reviewed this, had one minor comment. Great article, I upgraded to 6.7 today and remove an older block check in lieu of this function and it's working great!

**Comment by ndiego** [comment]
This snippet is ready for a second review. The public preview is available here: https://developer.wordpress.org/news/?p=4727&post_type=snippets&preview=1&_ppp=a9ca7ab3d2

**Comment by bph** [comment]
Just reviewed and it's great. You can certainly publish it. 

I added the checklistz here so we can evaluate if we need all the steps for snippets, too. 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [ ] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ndiego** [comment]
The post has been published here: https://developer.wordpress.org/news/snippets/how-to-disable-heading-levels-in-the-editor/

**Social copy**

> WordPress 6.7 allows developers to restrict the heading levels that are available to users in Core blocks. Learn how in this code snippet on the WordPress Developer Blog.

**Comment by ryanwelcher** [comment]
Social schedule for Nov 26
