### ISSUE TITLE
Snippet: How to lock blocks and prevent your users from unlocking them

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#344]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/342

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** November 18, 2024</sup>
This snippet would provide a very brief overview of the [Block Locking API](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/block-locking/) and then show developers how to prevent unlocking in specific contexts: 

**Post types:**
```php
add_filter( 'block_editor_settings_all', function( $settings, $context ) {
    if ( $context->post && 'page' === $context->post->post_type ) {
        $settings['canLockBlocks'] = false;
    }

    return $settings;
}, 10, 2 );
```

**User permissions:**
```php
add_filter( 'block_editor_settings_all', function( $settings ) {
    $settings['canLockBlocks'] = current_user_can( 'edit_theme_options' );

    return $settings;
} );
```

The snippet will also show how to disable access to the Code Editor, so users cannot manipulate the attributes directly.</div>

**Comment by ndiego** [comment]
This snippet is ready for its first review. Here's the draft: https://docs.google.com/document/d/1ok6K0cvpCSMwkOgs_lFWC0xCTjyCgMPZaMuocF9C87o/edit?tab=t.0

**Comment by bph** [comment]
A nice, conscise 360° on Block locking and how to control it. Made an editing suggestion and also suggested another link to shorted the UI paragraph, to keep it even more conscise :-)

**Comment by ndiego** [comment]
> A nice, conscise 360° on Block locking and how to control it. Made an editing suggestion and also suggested another link to shorted the UI paragraph, to keep it even more conscise :-)

Perfect, thanks. This allowed me to trim the majority of that paragraph.

**Comment by ryanwelcher** [comment]
Second review done. Ready to go!

**Comment by bph** [comment]
### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [ ] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [x] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [ ] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ndiego** [comment]
The snippet has been published: https://developer.wordpress.org/news/snippets/how-to-lock-wordpress-blocks-and-prevent-unlocking/ 

Social Copy: 

> In this article on the Developer Blog, Learn how to lock blocks in WordPress and prevent your users from unlocking them. The code snippets provided are great for maintaining design consistency.

**Comment by ndiego** [comment]
Social post scheduled for 12/27
