### ISSUE TITLE
What's new for developers? (December 2024)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#347]
This is a rolling discussion for a monthly series that is intended to keep track of the items, PRs, Trac tickets, and Make blog posts that are interesting/important for developers. The goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Google Doc: https://docs.google.com/document/d/1PNTcp8uxjZm8vyPmwl1y2t17gYzGccMj98pXg-U-S_Y/edit?usp=sharing

Author: @ryanwelcher

**Comment by ryanwelcher** [comment]
Ready for first review.

**Comment by ryanwelcher** [comment]
First review was done by @bph

**Comment by ndiego** [comment]
I have completed the second review. Just flagged a few minor things.

**Comment by bph** [comment]
Just in case... 

### Pre-publishing checklist: (updated 1/29/2024)

- [x] Post Title and subheaders in sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Are all images files uploaded to the media library
- [x] Do all images have an alt-text?
- [x] For TOC us the Pattern under _Developer Blog > Table of contents_
- [x] Assign or upload a featured image
- [x] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [x] Add the label "post to social" to the issue
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by ryanwelcher** [comment]
Social copy:

> Catch up on what’s coming next for Core, Gutenberg, and WordPress Playground in the last edition of What's New for Developers for 2024

Published [What’s New for Developers? (December 2024)](https://developer.wordpress.org/news/2024/12/10/whats-new-for-developers-december-2024/)

**Comment by ndiego** [comment]
Scheduled for 12/20
