### ISSUE TITLE
Snippet: How to register a block variation but hide it from the inserter

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#351]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/348

<div type='discussions-op-text'>

<sup>Originally posted by **ryanwelcher** November 26, 2024</sup>
In the [#outreach channel](https://wordpress.slack.com/archives/C015GUFFC00/p1732289265960489), I had a discussion with someone that wanted to create a block variation but only have it be inserted via a pattern.

This is possible by using the `scope` property and settings it to `block'</div>

**Comment by ryanwelcher** [comment]
Snippet is ready for first review - https://docs.google.com/document/d/1-wem7ORmODPoUDImJRn7BYiCOA29hZJWHvWv1ch90pk/edit?usp=sharing

**Comment by ndiego** [comment]
Completed the first review!

**Comment by justintadlock** [comment]
Looks good to go.

**Comment by ryanwelcher** [comment]
Social Copy:

> In this snippet from the Developer Blog, Learn how to hide a block variation from the inserter using the scope property.

**Comment by ryanwelcher** [comment]
Published -https://developer.wordpress.org/news/snippets/snippet-how-to-register-a-block-variation-but-hide-it-from-the-inserter/

**Comment by ndiego** [comment]
Social post scheduled for 1/2
