### ISSUE TITLE
Article idea: change the hamburger icon

### ISSUE THREAD

**Issue by mburridge** [WordPress/developer-blog-content#4]
Some people don't like the default two bar hamburger menu icon in the Navigation block, and might prefer a three bar icon or other icon.

This was asked [here](https://wordpress.org/support/topic/hello-and-change-mobile-hamburger-icon-twentytwentytwo/?view=all), and a solution provided [here](https://wordpress.org/support/topic/customize-navigation-block-hamgurger-icon/).

I propose this how-to as a possible article in the developer blog.

**Comment by justintadlock** [comment]
WordPress 6.1 will have an icon selector (added in Gutenberg 14.1).  It only includes four options at the moment: https://github.com/WordPress/gutenberg/pull/43674

It doesn't currently allow custom icons, which would be a future iteration.

**Comment by mburridge** [comment]
Ah, okay. I'll close this then as I guess it won't be needed.
