### ISSUE TITLE
2022: the block developer’s year in review

### ISSUE THREAD

**Issue by mburridge** [WordPress/developer-blog-content#40]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** December 12, 2022</sup>
A post wrapping up 2022 and summarising all the new developments and resources that became available during 2022.

e.g.
- workshops/courses/tutorials on learn.wordpress.org
- wordpress.tv videos
- dev notes
- updates to create-block

Can you think of any other ideas not covered in the above list?

To be published before the end of 2022.</div>

**Comment by mburridge** [comment]
The start of a draft for this post is in [this Google Doc](https://docs.google.com/document/d/1h0vxZQ1KzbXN8PpAWOpVC38HSk2DSWFsg9DqaIgNAlw/edit#heading=h.t1n8yyiul901).

At the moment I'm just looking for resources to add to each section. Please suggest away with any resources that you're aware of that you think should be included.

Please also say if you think I'm missing something that should be in the post.

Do you think the scope of the post is too wide? Should I be limiting the scope to just learning and documentation resources, rather than trying to give a broader overview of the year?

**Comment by juanmaguitar** [comment]
> Do you think the scope of the post is too wide? Should I be limiting the scope to just learning and documentation resources, rather than trying to give a broader overview of the year?

Yes, I think that focusing on just the learning and documentation resources related to Block Development published in 2022 would make an effective and valuable post that could be shipped in the following week.

**Comment by abhansnuk** [comment]
Hi @mburridge. I agree that a narrower scope would be better and focusing on block development learning and documentation resources. It would be useful and perhaps we can give a call to action in it to encourage block developers to read it to find out if they know all these things came out in 2022.

**Comment by mburridge** [comment]
[The post](https://docs.google.com/document/d/1h0vxZQ1KzbXN8PpAWOpVC38HSk2DSWFsg9DqaIgNAlw/edit#heading=h.ycugz2sp7o9m) is now ready for review. It would be great to get it published before the start of the Christmas holidays.

**Comment by justintadlock** [comment]
First review complete.  Great work, @mburridge!  This will be a useful resource.

**Comment by mburridge** [comment]
[The preview](https://developer.wordpress.org/news/?p=572&preview=true) is now available for review. If everyone is happy with it I think it would be great to schedule publication for 31st Dec.

**Comment by bph** [comment]
The above "preview" link would only be accessible for logged-in users. 

A "**public post** preview"  link can be created using the additional setting in the Documentation settings "enable public preview' and share that link when requesting a review. 

![Screen Shot 2022-12-22 at 13 29 08](https://user-images.githubusercontent.com/39980/209202703-b8a403db-7358-4aa8-94b9-9f266b789f31.png)

We might have reviewers that don't have (yet) access to the site.

**Comment by bph** [comment]
@mburridge This article looks great online!
 I only have minor suggestions

- Please update the link to Roadmap to point to the top WordPress site and not to the localized gb site. https://wordpress.org/about/roadmap/

- You could add links to the graphics where possible, so when someone clicks on them are taken to the right site and don't have them hunt down the link from the text. :-) 

**To keep props uniform**
- add @ the user (no need to use full names and links, the blog should pull the links from the @ mention.) 
- italic and right aligned. 

With the above changes, this should be good to publish 🙌 . 

There is no need to wait for Dev 31 to publish it. You could schedule it for  Tuesday  (27) or Wednesday (28), and it will have wider attention.

**Comment by mburridge** [comment]
@bph I've made all the changes you suggested, though Wes and Courtney don't come up with @ mentions 🤷‍♂️.

Publication has been scheduled for 11:00 on Wed 28th Dec.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/20643925/209208723-7562e828-9079-447d-9d3e-17a8a4b53a57.png">

**Comment by bph** [comment]
Thanks @mburridge for letting me know about the mention not being picked up by the site.  

I created [an issue on the Theme repo](https://github.com/WordPress/wporg-developer-blog/issues/33), so I don't forget about it before I return to work

**Comment by bph** [comment]
The post was published on Dec 28th, 2022 
[2022: the block developer’s year in review](https://developer.wordpress.org/news/2022/12/28/2022-the-block-developers-year-in-review/)
