### ISSUE TITLE
A Walk-Through of Layout Classes in WordPress 6.1

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#49]
A [copy of this post on the Gutenberg Times](https://gutenbergtimes.com/a-walk-through-of-layout-classes-in-wordpress-6-1/), that was published before the Dev Blog was available, with the understanding that it will be moved to the Dev Blog, once it's open to the public. 

Approved by the Editorial group in Jan 5th meeting. 

[Public Post Preview is available](https://developer.wordpress.org/news/?p=639&preview=1&_ppp=d59ef80411)

Once the post is published on the Dev Blog, the canoncial URL will point from the GT post to the Dev Blog.

**Comment by justintadlock** [comment]
Do we want to go ahead and publish this or wait for it to get another review round?  I can go through and do a check and cleanup of anything.  Is there anything else I need to do on my end?

**Comment by bph** [comment]
Absolutely. Yes, if you want to double-check it against the guidelines etc. 
During the meeting Abha noted "Suggest we put a shorter summary at the top when it is copied across to help with search too."

**Comment by justintadlock** [comment]
I've went through and did some cleanup based on our style guide, switched this to use the ToC block, fixed a couple of stylistic issues, added cats/tags, and added props from the original review.

**Comment by bph** [comment]
Thank you for getting it ready. I'll publish it tomorrow and point the canonical URL from GT to the DevBlog.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/news/2023/01/11/a-walk-through-of-layout-classes-in-wordpress-6-1/
