### ISSUE TITLE
A journey of a PHP developer building blocks

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#5]
A tale on how to approach the first block, what do know, what helps, what is a challenge and how to over come them. by @mburridge

**Comment by mburridge** [comment]
An initial draft of the post (still unfinished as yet) can be found [here](https://docs.google.com/document/d/1zyHZaka2gPh4G8qQbLwG8TpnFLVmjKg9svv4NlV4zWU/edit#).

**Comment by mburridge** [comment]
Title changed to "A PHP developer's guide to getting started with block development" and angle on the article changed from first person perspective to a more general guidance type of approach.

**Comment by mburridge** [comment]
The draft post '[A PHP developer's guide to getting started with block development](https://docs.google.com/document/d/1zyHZaka2gPh4G8qQbLwG8TpnFLVmjKg9svv4NlV4zWU/edit#heading=h.353dk4r0snt7)' is now ready for review.

**Comment by bph** [comment]
The post was reviewed and published: [A PHP developer’s guide to getting started with block development](https://developer.wordpress.org/news/2022/11/29/a-php-developers-guide-to-getting-started-with-block-development/)
