### ISSUE TITLE
Block Theme Resource Round-Up

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/developer-blog-content#50]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **DaisyOlsen** December 22, 2022</sup>
Similar to the topic idea in #37 - I'd like to write up a round-up style post with resources for Theme Developers, particularly for Block Themes and the gradual adoption of block theme technology. Ideally, focused on content that was new in the last several months. Since the post will not be published until 2023, I suggest avoiding calling it a 2022 wrap-up in favor of a more general Round-up.

- workshops/courses/tutorials on learn.wordpress.org
- wordpress.tv videos
- dev notes
- Useful how-to/tutorials from DevHub

To be published before the end of January 2023.

Discussion, feedback welcome!</div>

---

## Pre-Publish Checklist

- [x] Post Title in Sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identified?
- [x] Is there an Excerpt?
- [x] Props added? 
- [x] Publish!

**Comment by DaisyOlsen** [comment]
It's taken me a bit longer to get this fleshed out than I hoped but I've managed to curate most of the links I'd like to include in the post. At the excellent suggestion of @bph I plan to organize the links based on function/feature with an eye toward workflow rather than chronologically as I originally thought to do.

The links are being gathered and organized into a [Raindrop.io Collection](https://raindrop.io/daisy-olsen/word-press-theme-development-resources-31161910/)

**Comment by DaisyOlsen** [comment]
I have one more place to pull links from, and I can get a draft together pretty quickly for review.

**Comment by DaisyOlsen** [comment]
I've created a doc with [my (very) rough draft](https://docs.google.com/document/d/1hqzY4H6nC7HZe6YbgzQ3FMzYxVi0OHTPe3hQigwueJw/edit?usp=sharing). I've organized links into what I believe to be good groupings based on general topics. I hope not to overwhelm the post with a lot of text, as I think the real value is in the content at the other end of the links and how they are organized. There are a few that I may need to change the link text for to make them more clear.

I will put a bit more work into this and plan to have it in a reviewable state before I begin my weekend. If you have any feedback on the organization of the links, please feel free to comment on the document. I'll report back when the prose section is ready for feedback.

**Comment by DaisyOlsen** [comment]
I got closer but didn't get this post review ready for this sprint. Moving to Q1.3

**Comment by DaisyOlsen** [comment]
This is ready for review! I would love to see this published sometime next week if possible 🥺 All feedback and suggestions are welcome. Text is intentionally on the light side because the links are the focus.

https://docs.google.com/document/d/1hqzY4H6nC7HZe6YbgzQ3FMzYxVi0OHTPe3hQigwueJw/edit?usp=sharing

I have not added a draft post yet. If that's the preferred next step, I'm happy to do so.

**Comment by bph** [comment]
Hi @DaisyOlsen, I gave it a first look and added a few comments. It's a fantastic list of links in one place. It could also be immediately overwhelming if it isn't broken up into a few narrated paragraphs. I offered a few suggestions, you don't have to follow, but they might give you a few more ideas, how to guide your reader beyond the catalog.

**Comment by DaisyOlsen** [comment]
Thanks for the feedback @bph I'll be working on implementing some or all of it in the next day or so :-)

**Comment by DaisyOlsen** [comment]
I've implemented some of the feedback provided in the Google docs draft. I've moved it all over to a draft on the site: https://developer.wordpress.org/news/?p=832&preview=1&_ppp=bcbf2310e0

I've left the short text, and link lists as-is. This was the format I was going for to group the links without too much text around them. I'm happy to be wrong for future posts, but this seems to be the right approach to me this time around. 

Would love to move this forward in the next couple of days, if possible if I get another review or two.

**Comment by abhansnuk** [comment]
Hi @DaisyOlsen 
Thanks for this. Two suggestions:
- breaking up this sentence as it is quite long and maybe harder to follow for those translating it as they read. 
“Whether you are just starting to use the WordPress site and styles editors or you want to read detailed explanations of newly implemented technical aspects of the theme engine, there is content from around the WordPress family of sites that will cover all of that and more.”
- the list of links: be helpful to know which are videos etc. Aldo suggest breaking up the longer lists with some list headings / groups to make it easier to navigate back and forth from to follow each link.

**Comment by abhansnuk** [comment]
Can you please add an excerpt before it goes live, and any contributor names that are needed at the bottom. Thanks @bph and @DaisyOlsen . Back to you.

**Comment by DaisyOlsen** [comment]
Thanks for the fast turnaround Abha. I'll get this wrapped up to publish tomorrow. 🎉

**Comment by mburridge** [comment]
That's a fantastic list of resources and you've done a great job in compiling the list and categorising the items within it @DaisyOlsen. The one thing I think I would like to see, and I realise it would be quite a bit more work and so potentially would delay publication so feel free to disregard, is a more detailed introduction to each section explaining the basic concepts and why you need them. 

So, taking Block locking as an example - what is block locking, what purpose does it serve or what problem does it solve, and why should I follow up by clicking the links in that section and what benefits will it bring me.

This could provide the reader with "motivation" for digging into what is an excellent list of resources.

**Comment by DaisyOlsen** [comment]
Great suggestions @mburridge - I will continue with the short descriptions, however. I think revisiting this post or creating something like it periodically would be a good idea. The next time, the descriptions could be fleshed out more, and the links updated to reflect the most relevant information.

**Comment by DaisyOlsen** [comment]
The post has been published. Thanks to everyone for the reviews and suggestions. 

https://developer.wordpress.org/news/2023/02/block-theme-resources-roundup/
