### ISSUE TITLE
Demystify Home & Posts Page Templates

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#6]
By @DaisyOlsen 

The WordPress template hierarchy is relatively straightforward but there is often confusion about how Reading settings and index, custom, home, and front-page templates work and where each should be used to control the home and posts pages on a site.

**Comment by DaisyOlsen** [comment]
A [draft of this post](https://developer.wordpress.org/news/?p=141&preview=1&_ppp=8538c59b16) has been added to the site and is ready for review.

**Comment by abhansnuk** [comment]
**Second review done @bph:**
Thanks for writing this Daisy. 
@bph, this could get both a 'Beginner' and 'Intermediate' label to display.
It sets out the differences, actions, and where to learn more well so will be useful to both audiences. It may also be worth taking part of this and reusing it on LearnWP too for end users as opposed to devs, if it is not there already.

- **To do:** Alt text needed for images on this post
- Capitals, punctuation and bullet points standardized throughout post and in line with Estela's comment in docs last week. **Query** for @bph on specific capitalization in the main headline for this post for 'Home and Posts templates'. 
- - **Follow-up for tips doc:** Also presume in text 'classic theme' and 'block theme' as general terms would be lower case first letters. This can be added to the tips for writers document as an example.
- **Query:** Are we hyphenating 'front-page'? If so, this needs to be added to the tips for writers document under hyphenation
- **To action:** Excerpt needed, category and tags/ keywords, and credits before publication.
- **Query;** are there any links to docs/ DevHub @DaisyOlsen which could be added to this post?

**Wider questions as with other posts for launch:**
- for very long articles are we going to put a section content list at the top, and any back to top links @bph ?
code title field and accessibility (as per query raised for posts in general)
- keywords for posts to be discussed at next dev blog meeting
- format we will be using for credits at the end of posts (to be agreed and will need to be used for all the posts going live next week too)

**Comment by bcworkz-wp** [comment]
Suggest appending to "Template names are referenced below without file extensions.":
"Required file extensions would be either '.php' or '.html'  as appropriate for the theme type being developed."
or something along those lines. An article targeted at beginners cannot assume the reader knows much of anything.

**Comment by DaisyOlsen** [comment]
Thanks for the great feedback, everyone. I want to be sure I understand my next steps here. Would you all like me to incorporate the feedback above? I don't want to falsely assume what should be done next.

**Comment by bph** [comment]
Well, @DaisyOlsen What is it you would want to do next?

**Comment by bph** [comment]
:-) If I had to spell it out, I would say you have three paths on your journey. 

- incorporate the feedback you agree with, 
- ask for clarification if you don't understand, and 
- explain, why you don't agree with feedback…

**Comment by abhansnuk** [comment]
@bph if you can let me know about the questions above that relate to all posts, I can incorporate this into the tips for writers document. Thanks so much.

**Comment by bph** [comment]
@abhansnuk I have a favor to ask: Would you mind consolidating items that need overall/wider clarification, with your recommendation in the draft of your Writing Guidelines, and highlight them in the comments of the Google Doc? 

> Query: Are we hyphenating 'front-page'? If so, this needs to be added to the tips for writers document under hyphenation

[I looked up front-page](https://www.merriam-webster.com/dictionary/front-page), seems we don't need to be added to the writer's guidelines, unless there is a reason not to follow Merriam-Webster's dictionary.

**Comment by justintadlock** [comment]
In the context of WordPress or websites in general:

> That is the front-page template. <-- when used as an adjective
>
> The site displays posts on its front page. <-- when used as a noun (but, we'd likely say "homepage" here)

**Comment by DaisyOlsen** [comment]
This post has been published. I added alt-text and reviewed bullet lists and titles for consistency. I also expanded the note about file extensions to mention HTML and PHP.

Any further edits to punctuation or capitalization can still be adjusted if needed.

**Comment by bph** [comment]
Published as [Demystifying Home and Posts Templates in WordPress theme development](https://developer.wordpress.org/news/2022/11/17/demystifying-home-and-posts-templates-in-wordpress-theme-development/)
Thank you all
