### ISSUE TITLE
Tutorial: Deep dive into block styles

### ISSUE THREAD

**Issue by justintadlock** [WordPress/developer-blog-content#64]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** December 14, 2022</sup>
Block styles, at least from what I've seen, have been one of the least used features for theme authors.  And, when they are used, they are underutilized, not showing off their full potential.

I'd like to do a deep dive into how to build them, the multiple methods of loading styles for them only when needed, and showcasing some advanced examples.

On top of this introduction post, I could also see this working as an ongoing series where we have contributing theme designers showcase new block style ideas.  And, because we have a good overview as a first post, posts in the series could link back to the first post to show the foundational pieces without having to re-teach it each time.</div>

**Comment by justintadlock** [comment]
Ran into a pretty major bug with the block styles feature: https://github.com/WordPress/gutenberg/issues/27244

**Comment by justintadlock** [comment]
Uploading backup copy of [block styles draft](https://github.com/WordPress/developer-blog-content/files/10523387/index.md).  This is still really rough right now (been a bit sick this week, so not at the top of my game).  I expect to have a finished first draft on Monday.

**Comment by justintadlock** [comment]
The first draft is now ready: https://docs.google.com/document/d/1oridnyOL-27M1f5_bPPowzf0HhhmNez2nUlhvdCv7cA/edit?usp=sharing

I'm going to do another pass over it tomorrow, but it is now open for feedback and review.

**Comment by mburridge** [comment]
LGTM. Great tutorial @justintadlock. I've just added a couple of suggestions and one question that I'm not sure what the answer is.

**Comment by justintadlock** [comment]
Published: https://developer.wordpress.org/news/2023/02/creating-custom-block-styles-in-wordpress-themes/
