### ISSUE TITLE
Extending WordPress with SlotFill 

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#7]
A blog post following [his WCUS talk](https://us.wordcamp.org/2022/session/extending-wordpress-using-slotfill/) by @ryanwelcher 
_quoted from the session description._ 
Being able to extend and customize the editorial experience for users has been a part of any WordPress developer’s toolbox since hooks were introduced in WordPress 1.2. We have come a long way since then and now with the Gutenberg Project, we have a new tool available to us – SlotFill.

The SlotFIll system can be used to extend blocks and the UI for the Block Editor and Site Editor screens making it a critically important tool for any WordPress developer. This talk will take a deep dive into how this system works, show how and where you can currently extend WordPress, and finally how to create your own custom SlotFills!

**Comment by bph** [comment]
[Posted to Dev Blog now in public review](https://developer.wordpress.org/news/?p=63&preview=1&_ppp=da7b7f5ba0) (for subscribers)

Updated/Review

- title and subheaders to **sentence case** (from TitleCase) 
- changed resource links from YouTube to **WordPressTV** URLs where available
- marked the GitHub link to Ryan's personal repo as **(External)**

_Could use a second review._

**Comment by abhansnuk** [comment]
Second review completed as requested in your message today @bph .
Another really interesting post that will be useful for devs and highlights a lot of the information in documentation.

**Remaining queries/ actions:**
- second par, there are spaces around the text in semi-circular brackets, is this a convention we are using @bph? We may need to look at the impact for accessibility with this.
- in the 'Fill' section, third par, assuming the reference to "Fill accepts a single prop:" relates to 'property', If so, shall we change it to 'property' at first ref @bph ?
- PluginArea section, 1st bullet point: should 'implementions' be 'implementations'?
https://developer.wordpress.org/block-editor/reference-guides/components/slot-fill/
- 'A Visual Representation' section: both images need alt texts.
- Links should not use 'here' and ideally give information on the link. (Note to check this has been included in the tips for writers). This has been updated in the post. 
- revised descriptors of links and used brand form for WPTV references
- bullet points standardized within post
- references to 'we' changed as per style agreed

- references to Block Editor etc now following response from Estela in docs meeting last week on capitalization. (Note: tips for writers will need to use the same, and can give the example Estela gave).

- categories, keywords, excerpt, credits for any references used and reviewers to be added. 

**Wider questions:**
- for very long articles are we going to put a section content list at the top, and any back to top links @bph ? 
- code title field and accessibility (as per query raised for posts in general)
- keywords for posts to be discussed at next dev blog meeting
- format we will be using for credits at the end of posts (to be agreed and will need to be used for all the posts going live next week too)

**Comment by bcworkz-wp** [comment]
I believe the small white text on orange background graphics (Visual Representation section) do not meet WCAG accessibility guidelines for minimum contrast. Could be difficult for the visually impaired to comfortably make out. The orange background should be darker. Ideally the smallest text should be larger if it's not too difficult to do without having to redo the entire layout.

**Comment by bph** [comment]
@ryanwelcher your next steps: 

- Incorporate the feedback you agree with,
- ask for clarification if you don't understand, and
- explain, why you don't agree with feedback
- add props to reviewers and others on the bottom 
- when ready for publishing move item to respective column on the project board

**Comment by ryanwelcher** [comment]
Thank you all for the feedback. See below:

> 
> * second par, there are spaces around the text in semi-circular brackets, is this a convention we are using @bph? We may need to look at the impact for accessibility with this.

I've updated this to use commas instead of brackets.

> * in the 'Fill' section, third par, assuming the reference to "Fill accepts a single prop:" relates to 'property', If so, shall we change it to 'property' at first ref @bph ?

**Term props is a React.js convention, it should stay the same.**

> * PluginArea section, 1st bullet point: should 'implementions' be 'implementations'?
>   https://developer.wordpress.org/block-editor/reference-guides/components/slot-fill/

Updated

> * 'A Visual Representation' section: both images need alt texts.

I've added the alt text

> * revised descriptors of links and used brand form for WPTV references

Updated - @bph you did this, correct?

> * bullet points standardized within post

Can you clarify this for me? I am using ordered lists for things that have numbered steps and unordered for lists. Is this incorrect?

> * references to 'we' changed as per style agreed

Updated

> * references to Block Editor etc now following response from Estela in docs meeting last week on capitalization. (Note: tips for writers will need to use the same, and can give the example Estela gave).

Updated


> * categories, keywords, excerpt, credits for any references used and reviewers to be added.
be using for credits at the end of posts (to be agreed and will need to be used for all the posts going live next week too)

I have added some, feel free to change/add more if needed.

**Comment by bph** [comment]
@ryanwelcher yes I updated the links to  WPTV for the videos. 

I am unsure what to do with the repos for examples etc like this in the long run. 

That's definitely a question for after GoLive .... but if you have ideas for it. Let me know.

**Comment by bph** [comment]
Post is now published: [How to extend WordPress via the SlotFill system](https://developer.wordpress.org/news/2022/11/18/how-to-extend-wordpress-via-the-slotfill-system/)
Thanks y'all

**Comment by juanmaguitar** [comment]
@ryanwelcher can you add a Social copy for this post so it can be scheduled to be promoted in the official WordPress social media channels?

**Comment by ryanwelcher** [comment]
@juanmaguitar this is my first post on SlotFill, I think you're looking for one on [custom slot fill?](https://github.com/WordPress/developer-blog-content/issues/146)

**Comment by juanmaguitar** [comment]
> I think you're looking for one on https://github.com/WordPress/developer-blog-content/issues/146

Yes, you're right 🤦‍♂️ Thanks for pointing me in the right direction
