### ISSUE TITLE
Tutorial on block deprecation

### ISSUE THREAD

**Issue by mburridge** [WordPress/developer-blog-content#71]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** January 26, 2023</sup>
If you make a change to the way that a block is rendered you will see the "invalid content" error message after the change.

![this-block-contains-unexpected-or-invalid-content](https://user-images.githubusercontent.com/20643925/214892339-0cf4d378-c1db-4ca9-bbe4-c5eb7ff6ea01.jpg)

This commonly occurs during development, and developers working with blocks are very aware of this and are used to dealing with it.

However, if you've already published a block and want to make changes to it in an update you won't want users to see the "invalid content" error message, which they will in each instance of the block across their site until recovery is done on each of them.

To circumvent this problem developers can "deprecate" the old version of the block.

A tutorial on how to deprecate a block, and when and why you should do it, would be a nice addition to the Developer Blog.

Reference:
[Deprecation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/)
 

</div>

**Comment by mburridge** [comment]
### Resources

#### Documentation
- [Deprecation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) - Block Editor Handbook

#### Videos
- [Deprecation strategies for your custom Gutenberg blocks](https://www.youtube.com/watch?v=BWXcQEbVSx8) (Ryan Welcher)

#### Blog articles
- [How to Deprecate Gutenberg Blocks](https://awhitepixel.com/blog/how-to-deprecate-gutenberg-blocks/)
- [How to deprecate code in Gutenberg editor blocks](https://atomicblocks.com/how-to-deprecate-gutenberg-editor-blocks/)
- [What Happens When Block Markup Changes?](https://wptavern.com/ask-the-bartender-what-happens-when-block-markup-changes) (Justin Tadlock)
- [Gutenberg – Block Deprecation](https://dev.to/crs1138/gutenberg-block-deprecation-418e)

#### Forums

- [How do I properly deprecate Gutenberg block](https://stackoverflow.com/questions/67773080/how-do-i-properly-deprecate-gutenberg-block)
- [How can I deprecate an old version of my custom Gutenberg block, but keep the new version?](https://wordpress.stackexchange.com/questions/411736/how-can-i-deprecate-an-old-version-of-my-custom-gutenberg-block-but-keep-the-ne)

**Comment by mburridge** [comment]
### Things to mention

- Why deprecate? - to provide graceful fallback for earlier versions of the block
- Primarily for static blocks - not needed for dynamic blocks as they don't have a `save()` function
- Benefit is for the content editor - avoids the 'invalid content' error message in the editor
    - front-end displays what's in `wp-content` for the post regardless
    - front-end only changes when the content is updated when the post is saved with new version of `save()`
- Each deprecated version of the block is an object, in the `deprecated` array, and has the following properties:
    - `attributes`
    - `supports`
    - `save`
    - `migrate`
    - `isEligible `
- Create a `deprecated.js` file and import it into `index.js` and use it in the `registerBlockType` function call
- Define each deprecated version as a `const` and reference in the exported array, e.g. `[v3, v2, v1]`

### Simple demonstration
Scaffold a block with `@wordpress/create-block`
Create 3 posts - add the new block to each (plus some text "Test 1 / 2 /3 ")
Change text in `save()` and create first deprecation
Test in second post
Change text in `save()` and create second deprecation (also maybe change `<p>` to `<div>` - and view markup)
Test in third post
Test in first and second posts

**Comment by ndiego** [comment]
@mburridge I have a lot of deprecation horror stories, so looking forward to this piece. Will definitely be a very valuable addition to the blog! 💪

**Comment by mburridge** [comment]
> I have a lot of deprecation horror stories

@ndiego please do share. It might be nice to have a section on pitfalls and gotchas to watch out for.

**Comment by ndiego** [comment]
Will do. I'll put together some examples next week 💪

**Comment by carstingaxion** [comment]
I would like to read about some nice ways to *deprecate* third–party blocks in favor of matured core blocks.

**Comment by mburridge** [comment]
A [draft of the post](https://docs.google.com/document/d/1mJ348wGeosThRzP9ynARmVOePBEc7cSS2wq13cDZVKA/edit#) is ready for review. Please test the code examples and that the iterations of the code and the deprecations of previous versions all work. Also any suggestions or corrections that might improve the post will be very welcome. Thanks.

**Comment by ndiego** [comment]
@mburridge I will read through today and add any comments I might have, but one thing that has tripped me up frequently is multiple deprecation issues. If there is more than one, sometimes the error message in the console can lead you in the wrong direction since it will only display the first error it encounters. So maybe a warning that the error message is helpful but only displays one error at a time and will not always be able to diagnose every issue.

**Comment by justintadlock** [comment]
This is well-written, as usual, @mburridge. I learned a ton and think this is exactly the kind of content that we need on the Developer Blog. I left a handful of in-doc comments.

I think my biggest note would be to try to break up the text a bit more with sections. I think this is pushing 2,000 words, so having a few headings sprinkled in there will make it easier to digest for readers.

I still need to do a run-through of the code, but the copy is pretty solid at this point.

**Comment by mburridge** [comment]
Thanks @justintadlock. I've broken up the wall-of-text with some headings, as per your suggestion. Let me know what you think.

**Comment by justintadlock** [comment]
@mburridge - The headings look good to me.

I've finished walking through the code and left my suggestions in the document. Overall, it felt pretty straightforward, and I successfully worked through each item. It was a really nice exercise for me since I haven't tried deprecation before. I'll definitely be more at ease with doing it for future blocks.

In addition to my mention of being precise about `src/index.js` vs. `index.js`, you could just mention earlier in the post that the reader will be working in the `src` folder. Just do it once instead of updating each file reference. I think that'd work better in this case.

**Comment by mburridge** [comment]
Glad you found it useful @justintadlock - I guess I must be doing something right! 😅

>  you could just mention earlier in the post that the reader will be working in the src folder

Great suggestion, thanks - I've done that.

**Comment by mburridge** [comment]
[Public preview](https://developer.wordpress.org/news/?p=967&preview=1&_ppp=e7cda12387) is now available for review.

**Comment by bph** [comment]
@mburridge Here is a publish checklist for you :-) 

- [x]  Post Title in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identifies?
- [x]  Is there an Excerpt?
- [x]  Props added?

**Comment by mburridge** [comment]
The only thing outstanding is that I can't find Fabian Kägy's profile page for the props.

**Comment by bph** [comment]
You would need to do at it manually. The site only pulls from the list of users on this site, not on all of wordpress. [It's a known issue](https://github.com/WordPress/wporg-developer-blog/issues/33), that hasn't been fixed yet.

**Comment by mburridge** [comment]
Okay, I found it in the end - he spells his surname differently in his username than in is actual surname 🤷‍♂️

**Comment by mburridge** [comment]
As far as I'm concerned this is ready to go @bph @abhansnuk @marybaum.

**Comment by mburridge** [comment]
"Block deprecation – a tutorial" now [published](https://developer.wordpress.org/news/2023/03/block-deprecation-a-tutorial/).

**Comment by Bruse-Lee** [comment]
Why not implement a plug-in that traverses all articles containing the Attempt Block Recovery button and simulates users clicking to go to batch Recovery？
