### ISSUE TITLE
What's new for Developer (March 2023)

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#84]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **bph** February 13, 2023</sup>
This is a rolling discussion for a new monthly series that is intended to keep track of the items, PRs, Trac ticket and make blog posts that are interesting/important for developers. The current goal is to publish a post on the 10th of each month with the previous month's updates.

Everyone is welcome to contribute to this monthly document. If you find something interesting, just create a new reply to this discussion below.

Resources to track:

- [Keeping up with Gutenberg: Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/)
- [A Week in Core](https://make.wordpress.org/core/tag/week-in-core/)
- [Gutenberg plugin release posts](https://make.wordpress.org/core/tag/gutenberg-new/)
- [Core editor chat](https://make.wordpress.org/core/tag/core-editor-summary/), [dev chat](https://make.wordpress.org/core/tag/dev-chat+summary/), [performance team](https://make.wordpress.org/core/tag/performance-chat+summary/) meeting summaries

@justintadlock created a new Google Doc for March: https://docs.google.com/document/d/1l2CGDiXFRN6QhEzdiykGx779ozMehUM1ZnXD66ZbKd8/edit#</div>

**Comment by justintadlock** [comment]
I still have one sub-sub-section left to write out on this (like one or two paragraphs), but we can start the review process at this point: https://docs.google.com/document/d/1l2CGDiXFRN6QhEzdiykGx779ozMehUM1ZnXD66ZbKd8/edit#heading=h.cunu8im14w

**Comment by marybaum** [comment]
I have had my way with this now! Make of it what you will, and do your damnedest! And Oh. Maaannnnn! I am I excited about word-counted excerpts!

**Comment by justintadlock** [comment]
@marybaum Thank you for running through this. Great feedback!

**Comment by marybaum** [comment]
You are most welcome!

**Comment by justintadlock** [comment]
Thanks to @abhansnuk for a second review. Still working through the final edits and will be ready to publish.

**Comment by justintadlock** [comment]
Post is now live on the blog: https://developer.wordpress.org/news/2023/03/whats-new-for-developers-march-2023/
