### ISSUE TITLE
Examples of using the new filter blockEditor.useSetting.before

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#85]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **annezazu** December  8, 2022</sup>
Pulled from this PR: https://github.com/WordPress/gutenberg/pull/45089 This would be a great filter to highlight, especially when thinking about additional curation options with the block editor. 

>This allows the injection of block settings into the block editor before everything is rendered, so we are able to customize the settings available for a block however we want.

This unlocks a ton of neat options but definitely needs to be explained in detail and documented in general. </div>

**Comment by ndiego** [comment]
Thanks @bph I'll pick this up.

**Comment by cbirdsong** [comment]
Here are some examples of stuff that I haven't been able to figure out that _seem_ like they should be possible with this?
- Defaulting the "Inner blocks use content width" toggle switch to off when a new group block is added
- Defaulting the "table has header row" toggle switch to on when a new table block is added
- Removing the custom content width/wide width fields within the layout panel
- Removing the layout panel entirely

(If these aren't possible then I guess that's another thing to clarify?)

**Comment by ndiego** [comment]
Thanks @cbirdsong, I am going to start diving into this next week.

**Comment by bph** [comment]
Notes from the Editorial meeting March 2.
>[Share examples of using the new filter blockEditor.useSetting.before (#38)](https://github.com/WordPress/developer-blog-content/discussions/38) (title of the discussion, not working title yet) -> **agreement in principle for idea, further discussion to follow**

- [@bph](https://profiles.wordpress.org/bph/): there will be a [Dev Note](https://make.wordpress.org/core/2023/02/28/custom-settings-wordpress-6-2/) about this new filter hook and this would be a follow-up post to give people more examples and use cases
- alternative titles to be added to the ticket. [@marybaum](https://profiles.wordpress.org/marybaum/) to work with [@ndiego](https://profiles.wordpress.org/ndiego/) and [@greenshady](https://profiles.wordpress.org/greenshady/) on options

**Comment by ndiego** [comment]
The first draft of the article is ready for review: https://docs.google.com/document/d/1ktyuo4BHOeN3YzIpgoR83tmFGFTZIviKpC-NG2oabpA/edit#

**Comment by marybaum** [comment]
On it!

**Comment by marybaum** [comment]
Done!

**Comment by ndiego** [comment]
Thanks for all your help @marybaum 🙏

**Comment by ndiego** [comment]
The [draft has been updated](https://docs.google.com/document/d/1ktyuo4BHOeN3YzIpgoR83tmFGFTZIviKpC-NG2oabpA/edit#) based on @marybaum's edits. @ingeniumed @alecgeatches @ryanwelcher @mburridge if you have time, I would greatly appreciate a technical review. This will be the first real article on the new `blockEditor.useSetting.before` filter so I want to make sure I am showcasing it well. 🙏

The code is all available via a [companion plugin](https://github.com/ndiego/block-curation-examples). I would like to keep the functionality of the examples the same if possible so I don't have to update the graphics, but any suggestions for improvement would be most welcome. Thanks!

**Comment by mburridge** [comment]
Excellent article. I just added a couple of minor comments.

**Comment by bph** [comment]
After the 2nd review is done on the blog draft, here is the Pre-publish checklist @ndiego 
- [x] Post Title in Sentence case
- [x]  Are Category or Categories selected?
- [x]  Are Tags identifies?
- [x]  Is there an explicit Excerpt?
- [x]  Props added?
🙌 Publish! 📗
- [x] add Props for reviews to #props channel in WP Slack

**Comment by alecgeatches** [comment]
@ndiego @marybaum @mburridge Fantastic article! I left a couple of very minor suggestions. I also left a comment chain about possible performance issues with expensive operations in `blockEditor.useSetting.before`, but after some testing I was incorrect about the cost of the example code and it's fine.

Thank you for writing up this awesome guide.

**Comment by ndiego** [comment]
Thanks for the review @alecgeatches 🙏

**Comment by ingeniumed** [comment]
@ndiego @marybaum @mburridge Great article! I love the practical examples that have been provided along with screenshots of them in action. No suggestions from my end, as it looks great. 🚢

**Comment by ndiego** [comment]
This article has been published: https://developer.wordpress.org/news/2023/05/curating-the-editor-experience-with-client-side-filters/ 🎉
