### ISSUE TITLE
Tutorial on how to use theme.json filters

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#86]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **ndiego** February 23, 2023</sup>
[theme.json filters](https://make.wordpress.org/core/2022/10/10/filters-for-theme-json-data/) were introduced in WordPress 6.1, and allow developers to modify theme.json settings and styles in unprecedented ways. Unfortunately, there is little documentation and few real-world examples. Educating the community, especially agency developers, on these new editor curation techniques would hopefully increase block adoption among an important demographic.

This post should cover the following:

- Illustrate the need for more editor curation tools for advanced builders.
- Provide an overview theme.json filters and how they help address this need
- Provide 3-4 real-world examples</div>

**Comment by ndiego** [comment]
Thanks @bph I'll pick this up.

**Comment by mwhiteley16** [comment]
Allowing conditionals on these filters would be nice as well. For example, if a user wants to disable specific settings only within "posts" since they typically require far less stylistic control.

**Comment by ndiego** [comment]
This article is ready for first review: https://docs.google.com/document/d/1f64YAP90gjRtP0KgtjAx6wiBKuhRLT1dFUJTPAKLGDw/edit

**Comment by marybaum** [comment]
Heading in! NIck, I do copy edits in suggestion mode — Keep what works for you and broom what doesn't!

**Comment by ndiego** [comment]
Thank you sooo much @marybaum 🙌

**Comment by marybaum** [comment]
Done! See what you think, and do your damnedest!

You'll notice maybe that my edits are mostly about changing passive verbs to active ones: from 

**_The function is used to return this_**

to

_**The function does this...**_

And I add copious references to You, which is any reader's favorite person (themself ... ) to keep readers engaged and remind them they have skin is this game. I like to say we talk TO readers, not ABOUT them.

The third thing I do, generally, is use the shortest, most colloquial words possible. Because I want to connect with a reader viscerally, not cerebrally— I mean, in the gut, not the head—since the gut is where things stick.

**Comment by ndiego** [comment]
Thanks @marybaum, I greatly appreciate it. 🙏

**Comment by mburridge** [comment]
Excellent article, I had nothing to add a comment on. Great job!

**Comment by ndiego** [comment]
Thanks for the review @mburridge 

The [public preview](https://developer.wordpress.org/news/?p=1602&preview=1&_ppp=ecbdc47510) of the final draft is available.

**Comment by bph** [comment]
@ndiego This is a great tutorial. I am tempted to write a few customization myself 😄 

I found the compare image block a little hard to decipher. I tried to add additional instructions above, but found that it doesn'tmake it easier to see the two different variations, but it's makes it even more awkward.... 

<img width="959" alt="Screenshot 2023-07-05 at 08 48 53" src="https://github.com/WordPress/developer-blog-content/assets/39980/89604314-0247-4f01-9aec-7f5067af17eb">

I would use both image in the canvas as they are and add some caption to each. We have the space, and it's much clearer for the reader to see the difference right away. 

Here again for you the two checklists before you hit the publish button. 

### Pre-publishing checklist: 

- [x] Post Title and subheaders in Sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt? (not optional)
- [x] Do all images have an alt-text?
- [x] Props added? 
🙌 Publish! 📗 🎉 

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack 
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with link to the publish post.

**Comment by ndiego** [comment]
@bph thanks for reviewing and good callout. I was trying to get too fancy with it 😅 I'll update the images as a two images gallery. I already updated the images at the beginning of the article and I think it works well.

**Comment by ndiego** [comment]
The post has been published here: [How to modify theme.json data using server-side filters](https://developer.wordpress.org/news/2023/07/how-to-modify-theme-json-data-using-server-side-filters/)

Thanks to everyone who helped out!
