### ISSUE TITLE
useEntityRecords tutorial

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#87]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** January 17, 2023</sup>
A tutorial explaining the use of the [`useEntityRecords` hook](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/#useentityrecords) to retrieve data from the database, and demonstrating its usage via a demo project. It will also show:

- how to use the state properties, e.g. `isResolving`, `hasResolved`, to carry out actions depending on the state of the request
- the use of attributes to alter the request query

The tutorial could also cover the [`useEntityRecord` hook](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/#useentityrecord). 

There are currently no tutorials that I can find and the documentation on this is scant.</div>

**Comment by mburridge** [comment]
A [draft of this post](https://docs.google.com/document/d/1mpSdIbtFiocRZKkFKOQdXgl1k8s251TWMMBo42o6cSM/edit#)  is now ready for review.

**Comment by bph** [comment]
Just a reminder on the **Pre-publish Checklist**
 
- [x] Post Title in Sentence case
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x]  Is there an explicit Excerpt?
- [x]  Props added?
 🙌 Publish! 📗
- [ ]  add Props for reviews to #props channel in WP Slack

**Comment by marybaum** [comment]
On it!

**Comment by mburridge** [comment]
[Public preview](https://developer.wordpress.org/news/?p=1321&preview=1&_ppp=4936c017ce) is now ready for review.

**Comment by bph** [comment]
Published: [useEntityRecords: an easier way to fetch WordPress data](https://developer.wordpress.org/news/2023/05/useentityrecords-an-easier-way-to-fetch-wordpress-data/)
