### ISSUE TITLE
What the heck is wp-env?

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#89]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **mburridge** December  9, 2022</sup>
I propose an article on local WordPress environments for developers with an emphasis on `wp-env`, explaining what it is, what the benefits of using it are, and how to use it. The post should include plenty of screenshots of `wp-env` in action.

## Outline

**Local WordPress environments**
Local WP environment - what and why
A brief survey of:
- MAMP/WAMP/XAMPP
- Local (Flywheel)
- Valet (Laravel)
- DevKinsta (Kinsta)

**What is `wp-env`?**
Allows you to spin up a transitory WordPress environment from the command line. 
Primarily for development.
Requires Docker.
Requires Node/NPM.

**Why use `wp-env`?**
Quick and easy way to spin up a temporary WordPress environment for testing and development.
Doesn't require a monolithic installation.
Zero config.
Provides a testing environment on port 8889

**Installation**
Via NPM, either globally with -g switch, or in an existing project with a `package.json` file as a dev dependency 
Test with `wp-env --version`

**Usage**
`wp-env start` from project folder, or `npm rum wp-env start` if installed as a dev dependency
If Docker is not running you'll get an error
Can run in browser with `localhost:8888` - login credentials, etc...
Stop the environment with `wp-env stop`
Can run WP-CLI commands with `wp-env run cli [command]`
Can customise environment with a `.wp-env.json` file

**Troubleshooting**
Detail various troubleshooting steps

**References**

- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/
- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#wp-env-json</div>

**Comment by juanmaguitar** [comment]
Another reference:
- https://developer.wordpress.org/block-editor/contributors/code/getting-started-with-code-contribution/#using-docker-and-wp-env

**Comment by mburridge** [comment]
A first draft of the article is [ready for review](https://docs.google.com/document/d/1RfQTiRFd3jzqm5VBKXkwT4vaUYmX0N8cLLfKYeZUv30/edit#).

**Comment by justintadlock** [comment]
It reads pretty well from a technical standpoint. Everything seems easy to follow, and this should help folks easily spin up a dev install without much work. Review notes left in the doc.

**Comment by mburridge** [comment]
The [public preview](https://developer.wordpress.org/news/?p=1120&preview=1&_ppp=2542d64e16) of the wp-env post is now available for review

**Comment by mburridge** [comment]
Pre-publish checklist:

 - [x] Post Title in Sentence case
 - [x] Are Category or Categories selected?
 - [ ] All images with alt-text?
 - [x] Are Tags identifies?
 - [x]  Is there an Excerpt?
  - [x] Props added?

**Comment by juanmaguitar** [comment]
Why does [this preview](https://developer.wordpress.org/news/?p=1120&preview=1&_ppp=2542d64e16) have a different layout than the published articles?

<img width="1428" alt="Screenshot 2023-03-23 at 12 37 15" src="https://user-images.githubusercontent.com/422576/227192367-e7b48fe0-2da9-470d-9da6-322deb31732f.png">

<img width="1033" alt="Screenshot 2023-03-23 at 12 38 38" src="https://user-images.githubusercontent.com/422576/227192732-e3673fe9-ed76-45d6-a033-ecc35d7d8dcb.png">

**Comment by bph** [comment]
Ah right. We changed the template from "default"to "center column' 
At the moment it needs to be manually assigned in the post settings..

**Comment by mburridge** [comment]
Fixed it.

**Comment by juanmaguitar** [comment]
@bph @justintadlock what's the purpose of the "Updates" category?
I'm not sure this type of content belongs there
I also think the "Concepts" category is for more theoretical content.

**Comment by mburridge** [comment]
Not sure how 'Updates' got in there. I've removed it. 
I added the 'Concepts' category as setting up a local environment is a concept that developers need to get to grips with. Happy to remove if it's deemed not appropriate.

**Comment by mburridge** [comment]
I'm guessing the 'Updates' category is for the "What's new for developers" monthly posts.

**Comment by bph** [comment]
"Updates" is also the default category, a way to avoid the dorky "uncategorized" category, if someone misses to assign any category. 

The [description for Updates](https://developer.wordpress.org/news/category/updates/) reads: 
"Find notes about updates to documentation pages, what’s new in Gutenberg plugin, coming in the next WordPress release and more" 

[Concepts](https://developer.wordpress.org/news/category/concepts/) - The three posts that are in the category now, seem to fit the bill @juanmaguitar and I hope these answers your questions :-)

**Comment by juanmaguitar** [comment]
>  @juanmaguitar and I hope these answers your questions :-)

Yes! Thanks a lot for the clarification @bph

**Comment by mburridge** [comment]
Following a suggestion from @bph I've changed the title of the article to "Quick and easy local WordPress development with wp-env"

**Comment by mburridge** [comment]
The article is almost ready to publish. I'm just in the process of fact-checking and verifying one technical point ([here](https://wordpress.slack.com/archives/C02QB2JS7/p1679597399869329) and [here](https://docs.google.com/document/d/1RfQTiRFd3jzqm5VBKXkwT4vaUYmX0N8cLLfKYeZUv30/edit?disco=AAAAss8q50Y)) to ensure that I don't publish inaccurate or misleading content.

**Comment by marybaum** [comment]
Would you like me to do a drive-by later today? I’m afk until 17:00 but can do it then

**Comment by marybaum** [comment]
That’s what I call my copy reviews, because they tend to happen fast and raise the energy level of the piece

**Comment by marybaum** [comment]
I've had my way with this in the drive-by. See what you think! Do check out some text I added about MAMP,  which I used to use, and of course remove it if I have lied.

**Comment by marybaum** [comment]
I also really amped up the drama in the intro. If you think I went overboard, perfectly okay to nuke some of the violins 😜

**Comment by mburridge** [comment]
Thanks for that @marybaum . You've definitely raised the energy level of the article. I have taken the liberty of toning things down a bit in places, or re-wording things so that my "voice" comes through again. Hope you don't mind.

**Comment by mburridge** [comment]
@bph I've done a final run through and kept most of Mary's changes which definitely made the article more dynamic and energetic. I think it's ready to publish now.
Public preview: https://developer.wordpress.org/news/?p=1120&preview=1

**Comment by marybaum** [comment]
I don't mind at all! I wear my heart on my sleeve, and having used MAMP, DTS and Local I kinda knew where the pain points were so I could really twist the knife. So I figured you might want to dial back!

Actually, I did install wp-env and decided having to have hidden files showing to use it (unless I was mistaken?) didn't fit my desktop aesthetic (You can make an art director into a coder, but you'll never get the art director out of the coder ... ;-D )

**Comment by mburridge** [comment]
[Published](https://developer.wordpress.org/news/2023/03/quick-and-easy-local-wordpress-development-with-wp-env/)
