### ISSUE TITLE
How to use nonces the right way

### ISSUE THREAD

**Issue by zzap** [WordPress/developer-blog-content#95]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **bph** December  4, 2022</sup>
Thank you to @zzap for suggesting this topic! 

What would be the flow of such a post? </div>

**Comment by zzap** [comment]
Progress update: I have a structure draft for now. Not reviewable yet.

**Comment by zzap** [comment]
Working on draft: https://docs.google.com/document/d/1g5-HKh1IOpfeSE2huWQwFN3A1z8ksMfZxwdJ6JL2RoY/edit?usp=sharing

**Comment by bph** [comment]
That's a great start! I added a comment regarding the code snippet and made some minor suggestions. Looking forward to read the full post.

**Comment by bph** [comment]
@zzap 

### Pre-publishing checklist: 

- [x] Post Title in Sentence case
- [x] Use "Center Column" template
- [x] Are Category or Categories selected?
- [x] Are Tags identifies?
- [x] Is there an explicit Excerpt?
- [x] Do all images have an alt-text?
- [x] Props added? 
🙌 Publish! 📗

### Post-publishing checklist
- [x] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029))
- [x] add **copy for a social post** as comment to the issue [(Example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
- [x] close the issue with a comment to link to the published post
- [x] close the accompanying discussion with the link to the published post.

**Comment by zzap** [comment]
@bph I feel like existing categories are not quite covering it. Why is there `Block development` and not any other development?

**Comment by zzap** [comment]
This is the public preview https://developer.wordpress.org/news/?p=1746&preview=1&_ppp=e984a00227

**Comment by zzap** [comment]
Published https://developer.wordpress.org/news/2023/08/understand-and-use-wordpress-nonces-properly/

Social copy
>Do you know how to validate and refresh the nonce? Or how to send it to the REST API endpoints? Find out this and much more in this detailed article:
>https://developer.wordpress.org/news/2023/08/understand-and-use-wordpress-nonces-properly/
