### ISSUE TITLE
theme.json custom CSS tutorial

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#97]
### Discussed in https://github.com/WordPress/developer-blog-content/discussions/93

<div type='discussions-op-text'>

<sup>Originally posted by **justintadlock** March 28, 2023</sup>
WordPress 6.2 will allow developers to create per-block CSS via `theme.json`: https://github.com/WordPress/gutenberg/pull/46571

This topic idea is to walk theme authors through the process of using this feature, compare it with using stylesheets, and its relationship with the Styles interface in the editor. It will provide code examples for creating CSS to handle use cases that the built-in design tools are unable to.</div>

**Comment by justintadlock** [comment]
Beginning work on this here: https://docs.google.com/document/d/1JePD4Cb0MnHP50IdU18WEY7zsxYl_YbB3vZ94PcMo0Q/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft is now ready for review in a [Google Doc](https://docs.google.com/document/d/1JePD4Cb0MnHP50IdU18WEY7zsxYl_YbB3vZ94PcMo0Q/edit?usp=sharing).

Note: I still have a screenshot I need to update, but it shouldn't affect the content of the post.

**Comment by marybaum** [comment]
Excellent! I’ll be home in 20 minutes and take a look in the next two hours.MB... from my phoneOn Apr 20, 2023, at 8:39 AM, Justin Tadlock ***@***.***> wrote:﻿
The first draft is now ready for review in a Google Doc.
Note: I still have a screenshot I need to update, but it shouldn't affect the content of the post.

**Comment by marybaum** [comment]
Done!

**Comment by justintadlock** [comment]
Thanks, @marybaum. Great feedback, as always!

**Comment by justintadlock** [comment]
Published: https://developer.wordpress.org/news/2023/04/per-block-css-with-theme-json/

Thanks to @marybaum, @bph, and @carolinan for feedback and review.
